-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc5='進入血色競技場，$n。搏鬥賽要開始了!' WHERE entry=2000000001; /* content: Get in the Ring of Blood, $N. The fight is about to start! */
UPDATE db_script_string SET content_loc5='戰鬥即將開始!' WHERE entry=2000000002; /* content: The battle is about to begin! */
UPDATE db_script_string SET content_loc5='好的，我們走吧!' WHERE entry=2000000017; /* content: Ok, let\'s go! */
UPDATE db_script_string SET content_loc5='哎呀!' WHERE entry=2000000026; /* content: Whoops! */
UPDATE db_script_string SET content_loc5='過來，$n。怒風大人在等著。' WHERE entry=2000000034; /* content: Come, $N. Lord Stormrage awaits. */
UPDATE db_script_string SET content_loc5='龍喉戰士們，集合!你們其中一員已經達到了大領主的官階了!恭敬地鞠躬!對大領主$n表達出你們的尊敬以及效忠!' WHERE entry=2000000035; /* content: Warriors of Dragonmaw, gather \'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N! */
UPDATE db_script_string SET content_loc5='伊利丹王將會在這裡一小段時間。' WHERE entry=2000000036; /* content: Lord Illidan will be here shortly. */
UPDATE db_script_string SET content_loc5='伊利丹王萬歲!' WHERE entry=2000000037; /* content: All hail Lord Illidan! */
UPDATE db_script_string SET content_loc5='伊利丹王，這就是我和其他人曾經跟您說過的龍喉獸人。他將會帶領著我們獲得勝利!' WHERE entry=2000000038; /* content: Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory! */
UPDATE db_script_string SET content_loc5='不過...我的王，我不懂。$n...他這個獸人已經...' WHERE entry=2000000039; /* content: But... My lord, I do not understand. $N... He is the orc that has... */
UPDATE db_script_string SET content_loc5='我的王，事情將會完成。' WHERE entry=2000000040; /* content: It will be done, my lord. */
UPDATE db_script_string SET content_loc5='所以你想讓欺騙莫格，對嗎?在你被傳送至伊利丹王之前，你將會感覺到無法想像的痛苦。而我將會在我自己的報復中取得快感。' WHERE entry=2000000041; /* content: So you thought to make a fool of Mor\'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance. */
UPDATE db_script_string SET content_loc5='我們會再見的，勇敢的$c。' WHERE entry=2000000042; /* content: Until we meet again, brave one. */
UPDATE db_script_string SET content_loc5='完成了...' WHERE entry=2000000044; /* content: It is done... */
UPDATE db_script_string SET content_loc5='在丹莫洛寒冷的日子裡，沒有什麼比熱酒更好的東西了!' WHERE entry=2000000045; /* content: There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right! */
UPDATE db_script_string SET content_loc5='呱呱!不!!這不...呱呱...可能!你騙了我...呱呱...你這個騙子!呱呱!' WHERE entry=2000000047; /* content: Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit! */
UPDATE db_script_string SET content_loc5='現在把這些稀土放到我的培養槽裡去...' WHERE entry=2000000048; /* content: Now let us place this rare earth in my planter... */
UPDATE db_script_string SET content_loc5='在你們長大腦並意識到頭一個跑進軍團屠殺團是自殺行為之前，我還需要把多少個像你們這樣的蠻兵以屍袋送回給你們的媽媽和爸爸?不要點點你的大頭顱好像知道我在說些什麼!' WHERE entry=2000000055; /* content: How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about! */
UPDATE db_script_string SET content_loc5='以群星的名義!靈魂已經被召喚了!' WHERE entry=2000000060; /* content: By the stars! A spirit has been summoned! */
UPDATE db_script_string SET content_loc5='過去的事情誰也說不清，但重要的是我們的未來!' WHERE entry=2000000061; /* content: It\'s a mystery of the past indeed! But a key to our future! */
UPDATE db_script_string SET content_loc5='威脅終止了!$n救了我們大家!' WHERE entry=2000000062; /* content: The threat be over! $N be savin\' us all! */
UPDATE db_script_string SET content_loc5='我們怎能忍受有惡魔的爪牙在這片土地上肆虐橫行!' WHERE entry=2000000065; /* content: We will suffer no demon\'s servant in our lands! */
UPDATE db_script_string SET content_loc5='願安寧和耐心永遠與你同在，$n。' WHERE entry=2000000066; /* content: Peace and patience be with you, $N. Remain strong always. */
UPDATE db_script_string SET content_loc5='你在伊瑟拉的領土之內做什麼，闖入者?你給我離開!這裡不歡迎你這種族類!' WHERE entry=2000000067; /* content: What are you doing in Ysera\'s realm, interloper? Leave us, I say! Your kind are not welcome here! */
UPDATE db_script_string SET content_loc5='你 - 你不是他們的人!我們得在被他們找到之前逃走!快點!' WHERE entry=2000000068; /* content: You -- you\'re not one of them! Let\'s get out of sight before they find us! Hurry! */
UPDATE db_script_string SET content_loc5='他們在追我，$r!快點，在我們被發現前告訴我為什麼你會來這裡!要是讓他們抓到我，就代表你跟我都會死!' WHERE entry=2000000069; /* content: They\'re following me, $R! Quickly, tell me why you\'re here before we\'re discovered! If they catch up to me, it will mean my death and yours! */
UPDATE db_script_string SET content_loc5='年輕的雀鷹，沒有你，尋找烏鴉聖典的工作將會花費好幾年。帶著我們的感謝回到你位於納葛蘭的家。' WHERE entry=2000000070; /* content: It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude. */
UPDATE db_script_string SET content_loc5='就是這個!真的就是這個 - 烏鴉聖典!' WHERE entry=2000000071; /* content: This is it! This is really it -- the Book of the Raven! */
UPDATE db_script_string SET content_loc5='就跟我想的一樣，這塊石板提供了我們需要的證據。如今，我們必須在他對翡翠夢境造成更大傷害前利用這個資訊來引出並打敗這個安祖!' WHERE entry=2000000074; /* content: The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream! */
UPDATE db_script_string SET content_loc5='由於雀鷹已經成功的在搜尋烏鴉石一事上展現了牠的能力，看守者艾雷雅已經著手訓練另一隻雀鷹，可以幫我傳遞遠方的消息。他能夠在你調查石板上出現的鳥靈時幫助我們保持連繫!' WHERE entry=2000000075; /* content: Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet! */
UPDATE db_script_string SET content_loc5='擊碎這塊靈魂石真是太簡單了!' WHERE entry=2000000077; /* content: A simple enough task to break this soulstone! */
UPDATE db_script_string SET content_loc5='我們該與埃瑟里克斯·納拉辛有個了斷了。自然之靈啊，告訴我，去哪裡才能找到其他的靈魂寶石來解除他的魔法?' WHERE entry=2000000079; /* content: Then we must put an end to Athrikus Narassin. Tell me, spirit, where might we find the other soulgems, to undo his magic? */
UPDATE db_script_string SET content_loc5='在大爆炸時，亞米薩蘭正在大陸崩裂的邊界，幾乎沒有什麼倖存者逃過那次劫難。' WHERE entry=2000000081; /* content: In the throes of the Sundering, Ameth\'Aran was at the whim of the terror that gripped the land. There was little hope for survival. */
UPDATE db_script_string SET content_loc5='埃瑟里克斯來到我們面前，他聲稱能把我們從痛苦中解救出來。他給我們施了魔法，讓我們免受傷害。' WHERE entry=2000000082; /* content: Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm. */
UPDATE db_script_string SET content_loc5='當震動停下來的時候，他的真實目的暴露出來了。我們都被困住了，而他在慢慢地汲取我們的能量。' WHERE entry=2000000083; /* content: When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers. */
UPDATE db_script_string SET content_loc5='曾經有數百人被他的法術困住。現在只有一小部分還被囚禁著。他有時也會和我們交談。' WHERE entry=2000000084; /* content: There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes. */
UPDATE db_script_string SET content_loc5='他擔心他的法力會減弱，那塊寶貴的靈魂寶石也會消失和死亡。' WHERE entry=2000000085; /* content: He worried that his power weakened, that soon even we last of his precious soulgems would fade and die. */
UPDATE db_script_string SET content_loc5='%s聞了聞藥劑便急切地打開藥水瓶!' WHERE entry=2000000087; /* content: %s sniffs the elixir then eagerly digs in! */
UPDATE db_script_string SET content_loc5='%s召來了一個信差...' WHERE entry=2000000092; /* content: %s summons a messenger... */
UPDATE db_script_string SET content_loc5='...啊。' WHERE entry=2000000097; /* content: ... oops. */
UPDATE db_script_string SET content_loc5='嗯...等貨送好，我就要去乳酪店吃點東西。' WHERE entry=2000000143; /* content: Hm...after dropping this off, I think I\'ll head to that cheese shop for a snack. */
UPDATE db_script_string SET content_loc5='現在可以吃點心了...' WHERE entry=2000000151; /* content: Now for that snack... */
UPDATE db_script_string SET content_loc5='是啊是啊，生意很忙!' WHERE entry=2000000156; /* content: Yes ma\'am, business is brisk! */
UPDATE db_script_string SET content_loc5='我會的，謝謝你的乳酪!' WHERE entry=2000000157; /* content: Thanks for the cheese! */
UPDATE db_script_string SET content_loc5='該回店裡了...' WHERE entry=2000000158; /* content: Time to get back to the shop... */
UPDATE db_script_string SET content_loc5='我回來了!' WHERE entry=2000000159; /* content: I\'m back! */
UPDATE db_script_string SET content_loc5='呼啊啊啊啊啊啊啊啊!!' WHERE entry=2000000161; /* content: ROARRRRR!! */
UPDATE db_script_string SET content_loc5='夜色鎮...我餓了!!' WHERE entry=2000000162; /* content: DARKSHIRE...I HUNGER!! */
UPDATE db_script_string SET content_loc5='如果你回去狂心就殺你。你不再受歡迎了!' WHERE entry=2000000163; /* content: Frenzyheart kill you if you come back. You no welcome here no more! */
UPDATE db_script_string SET content_loc5='%s盯著西北方，發出了一聲長嘯。' WHERE entry=2000000168; /* content: %s stares to the northwest and lets out a long, drawn out howl. */
UPDATE db_script_string SET content_loc5='%s發出一聲震撼人心的怒吼。' WHERE entry=2000000169; /* content: %s lets forth a mighty howl. */
UPDATE db_script_string SET content_loc5='如你所願...' WHERE entry=2000000195; /* content: As you wish... */
UPDATE db_script_string SET content_loc5='拉利克現在要給你點顏色瞧瞧!' WHERE entry=2000000196; /* content: Raliq teach you lesson now! */
UPDATE db_script_string SET content_loc5='可惡!庫庫許不付錢!死吧!' WHERE entry=2000000197; /* content: F\'woooroonn! Coosh\'coosh pay nothing! Die! */
UPDATE db_script_string SET content_loc5='我選第三個選項:殺了你!' WHERE entry=2000000198; /* content: I choose the third option: KILLING YOU! */
UPDATE db_script_string SET content_loc5='我自由了!水靈會回到我的族人那裡。它將為我們帶來在這塊嚴酷的土地裡生存所需要的智慧。我欠你人情，$n。' WHERE entry=2000000199; /* content: I\'m free!  The spirit of water returns to my people.  It will bring us the wisdom we need to survive in this harsh land.  I am in your debt, $N. */
UPDATE db_script_string SET content_loc5='你已經釋放了我!風再一次的對我的族人耳語，並且賦予我們風的力量。感謝你，陌生人。' WHERE entry=2000000200; /* content: You\'ve freed me!  The winds speak to my people once again and grant us their strength.  I thank you, stranger. */
UPDATE db_script_string SET content_loc5='比索，我的朋友，好久不見啊。' WHERE entry=2000000208; /* content: It has been a long time, Bethor, my friend. */
UPDATE db_script_string SET content_loc5='如果時間允許的話，我們得好好談一下。因為我們有很多事情要討論。' WHERE entry=2000000209; /* content: When time permits, we must speak at length.  For we have much to discuss. */
UPDATE db_script_string SET content_loc5='謝謝你，$n。沒有你的幫助，我永遠無法成為被遺忘者的一員。' WHERE entry=2000000210; /* content: And thank you, $N.  Without your aid I may never have found my way to the Forsaken. */
UPDATE db_script_string SET content_loc5='保重，我的朋友。' WHERE entry=2000000211; /* content: Farewell, my friend. */
UPDATE db_script_string SET content_loc5='%s把信交給了藥劑師札瑪。' WHERE entry=2000000214; /* content: %s gives message to Apothecary Zamah. */
UPDATE db_script_string SET content_loc5='%s怒吼著回應瑪魯卡茲的呼叫。' WHERE entry=2000000224; /* content: %s howls in response to Malukaz\'s call. */
UPDATE db_script_string SET content_loc5='%s表達它的贊同。' WHERE entry=2000000225; /* content: %s expresses its approval. */
UPDATE db_script_string SET content_loc5='願我們與你的連結永遠不會再被切斷，亡靈。' WHERE entry=2000000226; /* content: May our bond with you never be broken again, spirit. */
UPDATE db_script_string SET content_loc5='閃耀貓用非常飢餓的眼神看著薇艾拉。' WHERE entry=2000000390; /* content: Twinkle looks at Viera Sunwhisper with very hungry eyes. */
UPDATE db_script_string SET content_loc5='我想知道這可以將那隻白色的貓射到多遠...' WHERE entry=2000000406; /* content: I wonder how far this would launch that white cat... */
UPDATE db_script_string SET content_loc5='當中和劑混和在湖水裡，被水晶輻射的水看起來變的清澈了。' WHERE entry=2000000633; /* content: As the neutralizing agent mixes into the waters of the lake, the water that was irradiated by the crystal seems to clear. */
UPDATE db_script_string SET content_loc5='泰德昂，試著將中和劑用在突變的生物身上。' WHERE entry=2000000634; /* content: Tedon, go ahead and try the neutralizing agent on the mutated creature. */
UPDATE db_script_string SET content_loc5='看來是時候把你從籠子裡放出來了。' WHERE entry=2000000635; /* content: Looks like it\'s time to let you out of this cage. */
UPDATE db_script_string SET content_loc5='現在，把中和劑放上去...' WHERE entry=2000000636; /* content: Now, to put the neutralizing agent on it... */
UPDATE db_script_string SET content_loc5='成功!' WHERE entry=2000000637; /* content: Success! */
UPDATE db_script_string SET content_loc5='這根本一點用也沒有!如果我們不把支撐杆穩住，這棟建築物絕對會倒塌。' WHERE entry=2000000645; /* content: This won\'t work at all! The buildings will surely collapse if we do not shore up the support beams. */
UPDATE db_script_string SET content_loc5='這完全不行!我們必須把地基弄牢否則這整棟建築都會粉碎!' WHERE entry=2000000646; /* content: This won\'t do at all! We have to secure the foundation or the entire structure will crumble! */
UPDATE db_script_string SET content_loc5='這棟建築物起碼違反了8條法令!' WHERE entry=2000000647; /* content: This structure violates at least 8 different ordinances! */
UPDATE db_script_string SET content_loc5='嗯，這樣看起來好多了。讓我們來看看裡面。' WHERE entry=2000000649; /* content: Hrm, this looks much better. Let\'s have a look on the inside. */
UPDATE db_script_string SET content_loc5='在基爾加丹腐爛的軀體旁，整個後方都被炸開!怎麼有人能在這裡生活?我見過太多了!' WHERE entry=2000000650; /* content: By the foul teat of Kil\'Jaeden\'s rotted torso, the entire backside is blown out! How can someone be expected to live in here? I\'ve seen enough! */
UPDATE db_script_string SET content_loc5='這應該會成功...' WHERE entry=2000000655; /* content: This should do it... */
UPDATE db_script_string SET content_loc5='醒醒啊小生物。從睡眠中醒來吧...你現在安全了。' WHERE entry=2000000656; /* content: Wake up little creature. Wake up from your slumber... You are safe now. */
UPDATE db_script_string SET content_loc5='%s呻吟著。' WHERE entry=2000000657; /* content: %s groans. */
UPDATE db_script_string SET content_loc5='%s坐起身。' WHERE entry=2000000658; /* content: %s sits up. */
UPDATE db_script_string SET content_loc5='我...我在哪裡?這...這是什麼地方?' WHERE entry=2000000659; /* content: Whe... Where am I? What... What is this place? */
UPDATE db_script_string SET content_loc5='%s又昏迷過去。' WHERE entry=2000000661; /* content: %s falls back into a coma. */
UPDATE db_script_string SET content_loc5='那東西到處傳播它的異教我要怎麼把工作完成?' WHERE entry=2000000663; /* content: How can I be expected to get any work done with that thing spreading its heresy? */
UPDATE db_script_string SET content_loc5='我們這裡不需要你的種族。' WHERE entry=2000000665; /* content: We do not need your kind here. */
UPDATE db_script_string SET content_loc5='%s要你跟著他。' WHERE entry=2000000666; /* content: %s urges you to follow him. */
UPDATE db_script_string SET content_loc5='%s指向庫的圖騰。' WHERE entry=2000000667; /* content: %s points to the totem of Coo. */
UPDATE db_script_string SET content_loc5='%s示意你跟著他。' WHERE entry=2000000668; /* content: %s motions for you to follow him. */
UPDATE db_script_string SET content_loc5='[熊怪語]藍色尖峰。' WHERE entry=2000000669; /* content: [Furbolg] Ritk kin\'chikx azul azure summit... */
UPDATE db_script_string SET content_loc5='[熊怪語]飛吧。跳過河流。' WHERE entry=2000000670; /* content: [Furbolg] Coo xip fly... Jump ilos river. Find Tikti. */
UPDATE db_script_string SET content_loc5='%s指向河的對岸。' WHERE entry=2000000671; /* content: %s points across the river. */
UPDATE db_script_string SET content_loc5='%s要你跟著他。' WHERE entry=2000000672; /* content: %s asks that you follow him. */
UPDATE db_script_string SET content_loc5='[熊怪語]你遠道而來。注視河流並順流而去。' WHERE entry=2000000673; /* content: [Furbolg] Far you mixik tak come. Gaze upon the kitch\'kal river. Follow. Ilog to Yor. */
UPDATE db_script_string SET content_loc5='[熊怪語]去南邊搜尋河的底部。' WHERE entry=2000000674; /* content: [Furbolg] Go... Search yitix\'kil bottom river. South! */
UPDATE db_script_string SET content_loc5='[熊怪語]來吧，$n。讓我們一起離開水源，純淨的。' WHERE entry=2000000675; /* content: [Furbolg] Come, $n. Let us leave the water together, purified. */
UPDATE db_script_string SET content_loc5='[熊怪語]我們現在走，一起行動。我們要尋找瓦克。' WHERE entry=2000000676; /* content: [Furbolg] We go now, together. We will seek Vark. */
UPDATE db_script_string SET content_loc5='[熊怪語]跟我去找瓦克。' WHERE entry=2000000677; /* content: [Furbolg] Follow me to Vark. */
UPDATE db_script_string SET content_loc5='[熊怪語]快，$n。瓦克在等你。' WHERE entry=2000000678; /* content: [Furbolg] Hurry, $n. Vark awaits you. */
UPDATE db_script_string SET content_loc5='[熊怪語]謝謝你，$n!' WHERE entry=2000000680; /* content: [Furbolg] Thank you, $n! */
UPDATE db_script_string SET content_loc5='[熊怪語]預言是真的!' WHERE entry=2000000681; /* content: [Furbolg] The prophecy is true! */
UPDATE db_script_string SET content_loc5='[熊怪語]靜松熊怪不會那麼快忘記你的英勇行為!' WHERE entry=2000000682; /* content: [Furbolg] The Stillpine furbolgs will not soon forget your bravery! */
UPDATE db_script_string SET content_loc5='[熊怪語]那些留在靜松要塞的人會像英雄一樣歡迎你!' WHERE entry=2000000683; /* content: [Furbolg] Those remaining at Stillpine Hold will welcome you as a hero! */
UPDATE db_script_string SET content_loc5='阿達曼，可以請你看一下這塊石板並試譯它的符文嗎?' WHERE entry=2000000691; /* content: Adamant, could you please take a look at this tablet and try to decipher the runes? */
UPDATE db_script_string SET content_loc5='當然!為了你什麼都可以，親愛的!' WHERE entry=2000000692; /* content: Of course! Anything for you, darling! */
UPDATE db_script_string SET content_loc5='好吧，讓我看看那塊石板。' WHERE entry=2000000693; /* content: Alright, let me take a look at that tablet. */
UPDATE db_script_string SET content_loc5='%s慢慢地讀著石板，用他們的母語無聲的讀著文字。' WHERE entry=2000000694; /* content: %s slowly reads the tablet, mouthing the words in their native tongue. */
UPDATE db_script_string SET content_loc5='納迦督軍!喔天啊...' WHERE entry=2000000695; /* content: Naga warlord! Oh dear... */
UPDATE db_script_string SET content_loc5='嗯，我接下來要說的話不太中聽，小姑娘。這個石板是納迦用來溝通的東西。他們的領導者，督軍司瑞史提斯，已命令他的納迦用武力佔領這座島剩下的區域。' WHERE entry=2000000696; /* content: Well, you aren\'t going to like what I have to tell you, young missy. This tablet is a naga communication. Their leader, Warlord Sriss\'tiz, has ordered his naga to take the rest of the island by force. */
UPDATE db_script_string SET content_loc5='而且看來他有援軍從納沙塔爾趕來!' WHERE entry=2000000697; /* content: And it looks like he\'s got reinforcements comin\' from Nazjatar! */
UPDATE db_script_string SET content_loc5='我們一定要想想辦法!' WHERE entry=2000000698; /* content: We\'ve got to do something about this! */
UPDATE db_script_string SET content_loc5='謝謝你，阿達曼。我想我知道一個適合的人選。' WHERE entry=2000000699; /* content: Thank you, Adamant. I think I know just the person for the job. */
UPDATE db_script_string SET content_loc5='你們從來都不收信的嗎?' WHERE entry=2000000827; /* content: Don\'t you people ever check the mail? */
UPDATE db_script_string SET content_loc5='我要怎麼遞送所有這些訊息?' WHERE entry=2000000828; /* content: How am I expected to deliver all of these messages? */
UPDATE db_script_string SET content_loc5='我需要重新分配。這份工作快把我逼到極限了...' WHERE entry=2000000829; /* content: I need to be re-assigned. This job is pushing me over the edge... */
UPDATE db_script_string SET content_loc5='他以為他是多麼的重要。總是愛使喚我...我會讓他見識一下。讓他們全部的人見識一下!' WHERE entry=2000000830; /* content: He thinks he\'s so damned important. Always pushing me around... I\'ll show him. I\'ll show all of them! */
UPDATE db_script_string SET content_loc5='要是我可以回到蘑菇灌木叢就好了。我這一生從沒見過這樣成熟的蘑菇叢!' WHERE entry=2000000831; /* content: If only I could get back to the mushroom thicket. I have not seen such a mature cluster in my lifetime! */
UPDATE db_script_string SET content_loc5='可憐的杜里奧斯。那些黑鐵矮人真是該死，幫幫我吧...' WHERE entry=2000005000; /* content: Poor Dorius. If I ever get my hands on those Dark Irons, so help me... */
UPDATE db_script_string SET content_loc5='奧普斯想要一些科爾戈的黃金...和一些蟲子。' WHERE entry=2000005001; /* content: Opus wants some Cuergo\'s Gold... with worm. */
UPDATE db_script_string SET content_loc5='基布雷爾正在接受地精工程學協會的調查。' WHERE entry=2000005003; /* content: Kibler is being investigated by G.E.T.A. */
UPDATE db_script_string SET content_loc5='比修知道寶藏被藏在哪兒了。' WHERE entry=2000005004; /* content: Bijou knows where treasures are hidden. */
UPDATE db_script_string SET content_loc5='龍控制著獸人!?不會吧!' WHERE entry=2000005005; /* content: Dragons controlling orcs!? SQUAWK! */
UPDATE db_script_string SET content_loc5='問問基布雷爾關於寶藏的事情!哇!' WHERE entry=2000005007; /* content: Ask Kibler about the treasure! SQUAWK! */
UPDATE db_script_string SET content_loc5='哇!*咳**咳*我要戒煙!' WHERE entry=2000005008; /* content: SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE db_script_string SET content_loc5='士兵們，幹得好!輕鬆一下吧!' WHERE entry=2000005009; /* content: Well done, soldiers! At ease! */
UPDATE db_script_string SET content_loc5='嘖嘖!樂意幫忙!' WHERE entry=2000005010; /* content: Zug zug! Happy to help! */
UPDATE db_script_string SET content_loc5='神秘的蹄印，燒焦的盾牌，散落的徽章...我們要如何從這所有東西當中理出頭緒來?' WHERE entry=2000005012; /* content: Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this? */
UPDATE db_script_string SET content_loc5='我不認為德拉席特可以找到任何人殺死這隻迅猛龍。我是說，他已經將賞金提高了兩次...' WHERE entry=2000005013; /* content: I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice... */
UPDATE db_script_string SET content_loc5='但這是唯一塞得下布洛葛的建築物!哥布林蓋的建築物都太小了!' WHERE entry=2000005014; /* content: But this the only building that fit Brogg! Goblins make buildings too small! */
UPDATE db_script_string SET content_loc5='我以為我們已經討論過這件事了，布洛葛。你不能待在這個建築物裡。當然你可以塞的進去，但是這樣就沒有位置留給其他人了!' WHERE entry=2000005015; /* content: I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else! */
UPDATE db_script_string SET content_loc5='是的，我們說你可以待在這裡，但這個建築物是我們的總部!我們所有的手冊還有藍圖都儲存在這裡!' WHERE entry=2000005016; /* content: Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here! */
UPDATE db_script_string SET content_loc5='我覺得是因為巨魔的體型太大了!我想我不會現在就說服你離開，但是別以為這個情況可以永久持續下去!' WHERE entry=2000005017; /* content: I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent! */
UPDATE db_script_string SET content_loc5='你最好後退一點。清除魚的內臟很容易弄髒衣服。' WHERE entry=2000005019; /* content: You might wanna stand back. Fish guttin\' is a dirty job. */
UPDATE db_script_string SET content_loc5='很高興看到你以捍衛塞拉摩而自豪，朋友。' WHERE entry=2000005020; /* content: It\'s good to see you defending Theramore with pride, friend. */
UPDATE db_script_string SET content_loc5='等你休息時，我們到酒館去吧。我請客，然後我們可以追憶過去美好的時光。' WHERE entry=2000005021; /* content: When you\'re off duty, let\'s go to the inn. I\'ll buy a round and we can reminisce about the good old days. */
UPDATE db_script_string SET content_loc5='它跑掉了!' WHERE entry=2000005024; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc5='過來跟我談談，我會為你撥開疑雲的。' WHERE entry=2000005026; /* content: Come speak with me, and what once was cloudy shall become crystal clear. */
UPDATE db_script_string SET content_loc5='明天我們將開始訓練這些大有前途的龍，別忘了帶上你的嚼咬玩具。' WHERE entry=2000005028; /* content: Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys. */
UPDATE db_script_string SET content_loc5='我來自底層社會...我們那兒的人民倍受折磨。' WHERE entry=2000005031; /* content: I come from the land down under... where women plague and men sunder. */
UPDATE db_script_string SET content_loc5='它跑掉了!' WHERE entry=2000005035; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc5='既然獵捕鄙惡者的頭顱有獎金可拿，我要趕緊去打獵了。' WHERE entry=2000005037; /* content: I might just have to go hunting for that Wretched beast now that there\'s a bounty on his head. */
UPDATE db_script_string SET content_loc5='這次輪班後我就要去深入調查那份賞金。' WHERE entry=2000005046; /* content: I\'m up to looking into that bounty after this shift. */
UPDATE db_script_string SET content_loc5='玩得開心嗎?' WHERE entry=2000005048; /* content: Having a good time? */
UPDATE db_script_string SET content_loc5='我從虛空接受到另一個讀數。' WHERE entry=2000005049; /* content: I have another reading from the nether. */
UPDATE db_script_string SET content_loc5='偉大的加茲魯維!' WHERE entry=2000005051; /* content: Great Gazlowe! */
UPDATE db_script_string SET content_loc5='嗶!' WHERE entry=2000005053; /* content: Bip! */
UPDATE db_script_string SET content_loc5='嗶!' WHERE entry=2000005054; /* content: Bip! */
UPDATE db_script_string SET content_loc5='嗶!' WHERE entry=2000005055; /* content: Bip! */
UPDATE db_script_string SET content_loc5='愛哭鬼!愛哭鬼!' WHERE entry=2000005057; /* content: Crybaby! Crybaby! */
UPDATE db_script_string SET content_loc5='愛哭鬼想要她的洋娃娃!' WHERE entry=2000005058; /* content: Baby wants her dolly! */
UPDATE db_script_string SET content_loc5='你的洋娃娃會不會游泳啊?哈哈!' WHERE entry=2000005059; /* content: I wonder if your dolly can swim! */
UPDATE db_script_string SET content_loc5='哈哈!我拿到伊莉莎白了!' WHERE entry=2000005060; /* content: Ha ha! I have Betsy! */
UPDATE db_script_string SET content_loc5='我拿到你的洋娃娃了!哈哈!' WHERE entry=2000005061; /* content: I have your dolly! Nyah nyah! */
UPDATE db_script_string SET content_loc5='不要傷害伊莉莎白，你這個壞蛋!' WHERE entry=2000005063; /* content: Don\'t hurt Betsy, you meanie! */
UPDATE db_script_string SET content_loc5='我希望那些穿過的血精靈們不會認為我正在偵察他們!' WHERE entry=2000005064; /* content: I hope those blood elves across the way don\'t think that I\'m spying on them! */
UPDATE db_script_string SET content_loc5='你們是死了，但不是被埋了。現在讓我看看你們的實力吧!' WHERE entry=2000005069; /* content: You\'re dead, not buried. Now show me your best! */
UPDATE db_script_string SET content_loc5='好了，你這堆可憐的爛骨頭。讓我們看看你有什麼本事。攻擊你的對手，我說停的時候你才能停止。' WHERE entry=2000005070; /* content: Alright you sorry sacks of bones. Let\'s see what you\'ve got. Strike your opponent, and don\'t stop till I say so. */
UPDATE db_script_string SET content_loc5='愛德華，泰勒爾出來。準備接受你們的第一輪挑戰。' WHERE entry=2000005071; /* content: Edward. Tyler. Prepare for your first challenge. */
UPDATE db_script_string SET content_loc5='利斯塔，把戰俘帶過來。' WHERE entry=2000005072; /* content: Lysta, summon in the captives. */
UPDATE db_script_string SET content_loc5='利斯塔，召喚亡靈俘虜。' WHERE entry=2000005074; /* content: Lysta, summon in undead captives. */
UPDATE db_script_string SET content_loc5='利斯塔，衝啊...憎惡!' WHERE entry=2000005076; /* content: Lysta, summon forth... the abomination! */
UPDATE db_script_string SET content_loc5='愛德華與泰勒爾，你們做得很好。你們在訓練的過程中穩定的成長。我們下次再來試試你們的近戰技巧。' WHERE entry=2000005077; /* content: Well done Edward and Tyler. You are progressing along in your training quite nicely. We shall test your mettle again soon. */
UPDATE db_script_string SET content_loc5='你救出德盧爾了嗎??不知道他被關在什麼地方。' WHERE entry=2000005078; /* content: Have you freed Drull yet? I don\'t know where he\'s being held. */
UPDATE db_script_string SET content_loc5='我只會拖慢你的速度。但是那些粉紅皮膚的人類是奪不走我的自由的!' WHERE entry=2000005079; /* content: I will only slow you down, but no pink-skinned humans will keep me from freedom! */
UPDATE db_script_string SET content_loc5='%s把零件木箱放在地上。' WHERE entry=2000005080; /* content: %s places the crate of parts on the ground. */
UPDATE db_script_string SET content_loc5='%s抓了一個零件，把它放進他的口袋中...' WHERE entry=2000005081; /* content: %s grabs a part and puts it in his pocket... */
UPDATE db_script_string SET content_loc5='那裡，應該就是那裡...' WHERE entry=2000005082; /* content: There, that should do it... */
UPDATE db_script_string SET content_loc5='讓我幫幫你吧。' WHERE entry=2000005085; /* content: Let me help you with those. */
UPDATE db_script_string SET content_loc5='把這個喝了，它對你有好處。' WHERE entry=2000005086; /* content: Drink this, it will help. */
UPDATE db_script_string SET content_loc5='你會好起來的。' WHERE entry=2000005087; /* content: You\'re going to be just fine. */
UPDATE db_script_string SET content_loc5='沐浴在我的力量中吧!吸取我的力量!為了部落的榮耀而戰!' WHERE entry=2000005091; /* content: Be bathed in my power! Drink in my might! Battle for the glory of the Horde! */
UPDATE db_script_string SET content_loc5='兄弟，這些契約是我的!很快你就將永遠從我眼前消失了!' WHERE entry=2000005092; /* content: The deeds are mine, brother! Soon you shall be out of my way for good! */
UPDATE db_script_string SET content_loc5='請跟著我。' WHERE entry=2000005094; /* content: Please, follow me. */
UPDATE db_script_string SET content_loc5='我並沒有真正弄明白這是什麼，但那些溫泉卻有些奇怪...' WHERE entry=2000005095; /* content: I haven\'t really figured out what it is, but there\'s something strange about the hot springs... */
UPDATE db_script_string SET content_loc5='%s把劍扔進淺水池。' WHERE entry=2000005096; /* content: %s tosses the sword into the shallow pool. */
UPDATE db_script_string SET content_loc5='我發現當我把什麼東西扔進水裡然後再拿回它時，它已經明顯變大了。' WHERE entry=2000005097; /* content: I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it. */
UPDATE db_script_string SET content_loc5='好吧，不管它是什麼，效果很好!' WHERE entry=2000005098; /* content: Well, whatever it is, it works quite well! */
UPDATE db_script_string SET content_loc5='他們說他有時會變成烏鴉。' WHERE entry=2000005109; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc5='他們說他有時會變成烏鴉。' WHERE entry=2000005110; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc5='然後那兔子就一下子咬掉了他的頭...事情就是這樣，我發誓。' WHERE entry=2000005111; /* content: And then the rabbit just bit his head off... I swear. */
UPDATE db_script_string SET content_loc5='呃...這不是魚!' WHERE entry=2000005116; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc5='我把蚯蚓的肚腸弄到鞋子上了。' WHERE entry=2000005117; /* content: I got worm guts on my shoes. */
UPDATE db_script_string SET content_loc5='我好像看到了什麼。' WHERE entry=2000005118; /* content: I think i see something. */
UPDATE db_script_string SET content_loc5='呃...這不是魚!' WHERE entry=2000005119; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc5='我好像看到了什麼。' WHERE entry=2000005120; /* content: I think i see something. */
UPDATE db_script_string SET content_loc5='我希望那是一條魚!' WHERE entry=2000005121; /* content: I hope that was a fish! */
UPDATE db_script_string SET content_loc5='你能想像嗎?' WHERE entry=2000005123; /* content: Can you imagine? */
UPDATE db_script_string SET content_loc5='真的嗎?' WHERE entry=2000005124; /* content: Really? */
UPDATE db_script_string SET content_loc5='哇!' WHERE entry=2000005125; /* content: Wow. */
UPDATE db_script_string SET content_loc5='我父親說那只是一個故事。' WHERE entry=2000005126; /* content: My father says that\'s just a story. */
UPDATE db_script_string SET content_loc5='真的嗎?' WHERE entry=2000005127; /* content: Really? */
UPDATE db_script_string SET content_loc5='哇!' WHERE entry=2000005128; /* content: Wow. */
UPDATE db_script_string SET content_loc5='很好很好。' WHERE entry=2000005129; /* content: That\'s neat. */
UPDATE db_script_string SET content_loc5='哇!' WHERE entry=2000005130; /* content: Wow. */
UPDATE db_script_string SET content_loc5='真的嗎?' WHERE entry=2000005131; /* content: Really? */
UPDATE db_script_string SET content_loc5='快點，你們這幫蠢貨!我們還有任務要執行!' WHERE entry=2000005132; /* content: Look alive, dogs! We got an operation to run here! */
UPDATE db_script_string SET content_loc5='玩得開心嗎?' WHERE entry=2000005133; /* content: Having a good time? */
UPDATE db_script_string SET content_loc5='現在大家看到的是聖光大教堂，這裡是暴風城的精神和宗教中心。' WHERE entry=2000005134; /* content: Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind. */
UPDATE db_script_string SET content_loc5='沒錯，的確是這樣的。聖騎士和牧師們就在大教堂裡接受真知的洗禮。' WHERE entry=2000005135; /* content: Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral. */
UPDATE db_script_string SET content_loc5='現在我們看到的是暴風要塞。在第一次獸人戰爭中，原來的暴風城堡被夷為平地，後來人們在廢墟上重建了暴風要塞。' WHERE entry=2000005137; /* content: Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War. */
UPDATE db_script_string SET content_loc5='部落被擊敗之後，人們回到這裡開始重建這座偉大的城市，以此來紀念那些為保衛我們而獻出生命的勇士。' WHERE entry=2000005138; /* content: When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival. */
UPDATE db_script_string SET content_loc5='好了，嗯...現在讓我們去參觀獻給在兩次獸人戰爭中的英雄們的紀念碑─英雄谷。跟我來吧。' WHERE entry=2000005139; /* content: Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me. */
UPDATE db_script_string SET content_loc5='孩子們，這裡是不是十分壯觀?所有人都要在這些偉大英雄們的注視下進入暴風城。' WHERE entry=2000005140; /* content: Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands. */
UPDATE db_script_string SET content_loc5='多麼震撼人心啊!孩子們，當我們回到學校以後，你們每個人都要寫一份關於這些英雄人物的報告。' WHERE entry=2000005141; /* content: Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people. */
UPDATE db_script_string SET content_loc5='現在，在我們前往神聖區和偉大的聖光大教堂前再好好看一眼。' WHERE entry=2000005142; /* content: Now, take another long look before we make our way to the Holy District and the great Cathedral of Light. */
UPDATE db_script_string SET content_loc5='不要靠近湖邊!那裡有鬼!' WHERE entry=2000005147; /* content: Don\'t go close to the lake! It\'s haunted! */
UPDATE db_script_string SET content_loc5='加入十二個聚焦核心可以使魔法能量變得更加穩固。' WHERE entry=2000005148; /* content: Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability. */
UPDATE db_script_string SET content_loc5='那樣能量流會崩潰，其魔法擾動的結果是會害你嚴重偏頭痛至少一個禮拜。' WHERE entry=2000005151; /* content: The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks. */
UPDATE db_script_string SET content_loc5='應該行得通吧...只要有二十個人幫我們一起施法。' WHERE entry=2000005156; /* content: I suppose that could work, if we had twenty people to cast it with. */
UPDATE db_script_string SET content_loc5='但是如果頻率轉換的結果是將魔法流回饋回去，那會怎麼樣呢?' WHERE entry=2000005157; /* content: But what if the resulting frequency shift were to send magical feedback up the flows? */
UPDATE db_script_string SET content_loc5='可是，那會使魔法聚焦失去平衡，並引起扭曲虛空中的異常波動。' WHERE entry=2000005159; /* content: That will unbalance the magical focus, though, and cause a reverse vibration in the ether. */
UPDATE db_script_string SET content_loc5='為什麼我們不能通過改變魔法陣列的方法去補償流量的變化呢?' WHERE entry=2000005161; /* content: Why can\'t we just shift the array to compensate for the variance in the flux? */
UPDATE db_script_string SET content_loc5='我不這麼認為，我不想再被炸出實驗室了。' WHERE entry=2000005163; /* content: I think not, I don\'t need to be blown up again. */
UPDATE db_script_string SET content_loc5='瑪姬諾曾指出，改變正極能量的流量會使其更加穩定。' WHERE entry=2000005164; /* content: Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow. */
UPDATE db_script_string SET content_loc5='聖騎士是不是在這裡訓練的?' WHERE entry=2000005167; /* content: Is it true that the paladins train here? */
UPDATE db_script_string SET content_loc5='我們為什麼一定要瞭解這些東西呢?' WHERE entry=2000005168; /* content: Why do we have to learn this stuff anyway? */
UPDATE db_script_string SET content_loc5='如果我們改變魔法精華的流向，也許我們就可以改變其極性。' WHERE entry=2000005169; /* content: If we reverse the Essence flows perhaps we can alter the polarity. */
UPDATE db_script_string SET content_loc5='如果我們在泰里安方程式中使用三個聚焦器會發生什麼事呢?應該可以解決這個問題吧?' WHERE entry=2000005170; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc5='如果我們按照正確的次序進行操作，那就應該不會有任何問題。所以我們在開始之前應該好好地研究一下。' WHERE entry=2000005172; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc5='如果我們能在恰當的能量點使用定位魔法來穩定它，那麼它應該是行得通的。' WHERE entry=2000005175; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc5='如果我們在泰里安方程式中使用三個聚焦器會發生什麼事呢?應該可以解決這個問題吧?' WHERE entry=2000005176; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc5='如果我們按照正確的次序進行操作，那就應該不會有任何問題。所以我們在開始之前應該好好地研究一下。' WHERE entry=2000005177; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc5='如果我們能在恰當的能量點使用定位魔法來穩定它，那麼它應該是行得通的。' WHERE entry=2000005178; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc5='你好，查瑞斯。這是我的貨單，你能幫我弄到這些東西嗎?尤其是最後一種材料。' WHERE entry=2000005180; /* content: Hello, Charys. I have my list, could you get me all of that, especially the last ingredient. */
UPDATE db_script_string SET content_loc5='謝謝你，查瑞斯。派格，小甜心，我們走了。' WHERE entry=2000005182; /* content: Thanks, Charys. C\'mon Paige, sweetie. */
UPDATE db_script_string SET content_loc5='媽媽，我能拍拍菲爾嗎?' WHERE entry=2000005183; /* content: Mommy? Can I pet Fizzles? */
UPDATE db_script_string SET content_loc5='繁重的魔法研究讓你身心疲憊嗎?到藍色隱士放鬆一下!' WHERE entry=2000005185; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc5='這裡有暴風城最好的酒!' WHERE entry=2000005186; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc5='到藍色隱士去，那裡每個人都知道你的名字!' WHERE entry=2000005187; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc5='感到憂鬱了?來藍色隱士放鬆一下吧!' WHERE entry=2000005188; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc5='這裡有暴風城最好的酒!' WHERE entry=2000005189; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc5='繁重的魔法研究讓你身心疲憊嗎?到藍色隱士放鬆一下!' WHERE entry=2000005190; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc5='到藍色隱士去，那裡每個人都知道你的名字!' WHERE entry=2000005192; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc5='在藍色隱士有免費的飲料!' WHERE entry=2000005193; /* content: Free drinks at the Blue Recluse! */
UPDATE db_script_string SET content_loc5='感到憂鬱了?來藍色隱士放鬆一下吧!' WHERE entry=2000005194; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc5='繁重的魔法研究讓你身心疲憊嗎?到藍色隱士放鬆一下!' WHERE entry=2000005195; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc5='這裡有暴風城最好的酒!' WHERE entry=2000005196; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc5='到藍色隱士去，那裡每個人都知道你的名字!' WHERE entry=2000005198; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc5='這裡有暴風城最好的酒!' WHERE entry=2000005199; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc5='衝啊!' WHERE entry=2000005200; /* content: Charge! */
UPDATE db_script_string SET content_loc5='衝啊!' WHERE entry=2000005201; /* content: Charge! */
UPDATE db_script_string SET content_loc5='啊，我珍貴的亞米娜!能夠再見到你是多麼美好的一件事。' WHERE entry=2000005202; /* content: Ahh, my precious Ameenah! How wonderful to see you again. */
UPDATE db_script_string SET content_loc5='嗯嗯，如果我這樣的話，請不要介意!' WHERE entry=2000005204; /* content: Hmm, don\'t mind if I do! */
UPDATE db_script_string SET content_loc5='調查正在進行中，炸餅。你難道沒有產品發表或是別的事情可以做嗎?' WHERE entry=2000005205; /* content: It\'s coming along, Wafflefry. Haven\'t you got a product demonstration to do or something? */
UPDATE db_script_string SET content_loc5='成為團體中首位擁有電荷污漬破壞器的人吧!' WHERE entry=2000005206; /* content: Be the first on your block to own the incredible Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc5='酒漬，草漬，連寵物污漬都不是電荷污漬破壞器的對手!' WHERE entry=2000005208; /* content: Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc5='別再遲疑了!現在就下訂購買我的電荷污漬破壞器，不需要額外費用喔!' WHERE entry=2000005209; /* content: Don\'t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge! */
UPDATE db_script_string SET content_loc5='它永遠不會停止。永遠...' WHERE entry=2000005210; /* content: I\'ll never stop. Never... */
UPDATE db_script_string SET content_loc5='嘿，誰來幫我抓住這個東西!' WHERE entry=2000005211; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc5='嗨!你喜歡沙司嗎?沙司很美味，不是嗎?' WHERE entry=2000005214; /* content: Hey! Do you like the sauce? The sauce is good, no? */
UPDATE db_script_string SET content_loc5='什麼?哦，灰燼使者?沒有聽說過...什麼?別煩我!' WHERE entry=2000005215; /* content: The what-bringer? Oh, ASHbringer? Never heard of it... What? Stop bothering me! */
UPDATE db_script_string SET content_loc5='嘿，誰來幫我抓住這個東西!' WHERE entry=2000005218; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc5='那應該會找到泰拉需要的幫助!' WHERE entry=2000005219; /* content: That should get Telaar the assistance it needs! */
UPDATE db_script_string SET content_loc5='別忘記買點飲料和紀念品!' WHERE entry=2000005223; /* content: Don\'t forget to buy refreshments and souvenirs! */
UPDATE db_script_string SET content_loc5='我該服下那透明小藥丸的。' WHERE entry=2000005228; /* content: I should have taken the translucent pill. */
UPDATE db_script_string SET content_loc5='做這種事情才得到這麼點報酬，虧大了!' WHERE entry=2000005229; /* content: I don\'t get paid enough for this bull excrement! */
UPDATE db_script_string SET content_loc5='你等得越久，我所能告訴關於你未來的資訊就越少。' WHERE entry=2000005232; /* content: The longer you wait, the less future you have for me to foretell. */
UPDATE db_script_string SET content_loc5='我可負擔不起這麼高的稅金!' WHERE entry=2000005234; /* content: I can\'t take these taxes! F.I.C.A. me? F.I.C.A. YOU! */
UPDATE db_script_string SET content_loc5='來看看派瑞·卡特勒的諧劇風格，還有幾分鐘就開始!' WHERE entry=2000005302; /* content: Check out the comedy stylings of Perry Gatner in just a few minutes! */
UPDATE db_script_string SET content_loc5='如果你們準備好大笑一場，就前往世界的盡頭小酒館!' WHERE entry=2000005303; /* content: If you are ready to laugh, head over to the World\'s End Tavern! */
UPDATE db_script_string SET content_loc5='現在，牛頭大佬出現在撒塔斯城!每小時整點，在世界的盡頭小酒館，現場演出!' WHERE entry=2000005304; /* content: Now, in Shattrath City: The Tauren Chieftains! Playing in the World\'s End Tavern at the top of the hour! */
UPDATE db_script_string SET content_loc5='你說布洛葛可以待在這裡的!你答應過布洛葛要奪回石槌氏族的領地!' WHERE entry=2000005306; /* content: You said Brogg could stay here! You promised Brogg you\'d help regain Stonemaul clan mound! */
UPDATE db_script_string SET content_loc5='嗯...我的魚竿在哪兒呢?哦，找到了。' WHERE entry=2000005307; /* content: Hmmm... Where is my fishing hook? Oh, there it is. */
UPDATE db_script_string SET content_loc5='來看看魚兒有沒有在咬餌。' WHERE entry=2000005308; /* content: Let\'s see if the fish are biting. */
UPDATE db_script_string SET content_loc5='嗯...我覺得我需要更好的誘餌。我得去我父親的貨車中找找。' WHERE entry=2000005309; /* content: Hmmm... I think I need better bait. I\'ll check my father\'s wagon. */
UPDATE db_script_string SET content_loc5='野豬人肉片!這個應該可以。魚喜歡野豬人的味道。' WHERE entry=2000005310; /* content: Quillboar scraps! These should do the trick. Fish love Quillboar. */
UPDATE db_script_string SET content_loc5='抓到一條了!不知道有沒有守衛快要餓扁了。快來吧，魚兒!' WHERE entry=2000005311; /* content: Caught one! I\'ll see if any of the guards are hungry. Come on Fang! */
UPDATE db_script_string SET content_loc5='你餓了嗎?我抓了一條魚...' WHERE entry=2000005312; /* content: I caught a fish if you are hungry... */
UPDATE db_script_string SET content_loc5='幹得好!你為部落帶來了榮耀，我們感謝你!' WHERE entry=2000005313; /* content: A nice catch it is at that! You bring honor to the Horde boy, We thank you! */
UPDATE db_script_string SET content_loc5='你還想要吃點什麼嗎?' WHERE entry=2000005314; /* content: Would you like something more to eat sir? */
UPDATE db_script_string SET content_loc5='孩子，給我更多的麵包!' WHERE entry=2000005315; /* content: More bread boy! */
UPDATE db_script_string SET content_loc5='遵命，長官。' WHERE entry=2000005316; /* content: Right away sir. */
UPDATE db_script_string SET content_loc5='這是你要的麵包，先生。' WHERE entry=2000005317; /* content: Here is your bread sir. */
UPDATE db_script_string SET content_loc5='啊...太好了。快走吧!' WHERE entry=2000005318; /* content: Aaahh... Very good. Now scat! */
UPDATE db_script_string SET content_loc5='如你所願，長官。' WHERE entry=2000005319; /* content: As you wish sir. */
UPDATE db_script_string SET content_loc5='爸爸，我能出去收集更多的石頭來做項鍊嗎?' WHERE entry=2000005320; /* content: Can I go collect more rocks for my necklace, Papa? */
UPDATE db_script_string SET content_loc5='好的!我會小心的，爸爸!' WHERE entry=2000005322; /* content: Dabu! I will be careful Papa! */
UPDATE db_script_string SET content_loc5='哦...這塊石頭真是漂亮。看看我能不能找到更多這樣的石頭...' WHERE entry=2000005323; /* content: Ooohh... This rock is nice and colorful. Let\'s see if I can find more like it... */
UPDATE db_script_string SET content_loc5='嗯...那塊石頭很不錯，但是太小了一點。' WHERE entry=2000005324; /* content: Hmm... That rock is nice, but too small. */
UPDATE db_script_string SET content_loc5='這石頭很適合拿來製作長矛，我敢打賭，我的朋友格魯克會喜歡的!非常鋒利...希望他會喜歡。' WHERE entry=2000005326; /* content: I bet my friend Gruk would like this rock for the spear he is making! It\'s very sharp... I hope he likes it. */
UPDATE db_script_string SET content_loc5='嗯...這些石頭應該足夠做一條項鍊啦。無論如何，我現在得回家啦。' WHERE entry=2000005327; /* content: There... That should be enough rocks to make a necklace. I should probably get home now anyway. */
UPDATE db_script_string SET content_loc5='我要送你一個喬遷之喜的禮物，加爾。' WHERE entry=2000005328; /* content: I brought you a housewarming gift, Jarl. */
UPDATE db_script_string SET content_loc5='不要緊，打開吧。我想你會喜歡它。' WHERE entry=2000005329; /* content: Go on, open it. I think you\'ll like it. */
UPDATE db_script_string SET content_loc5='加爾?' WHERE entry=2000005330; /* content: Jarl? */
UPDATE db_script_string SET content_loc5='除非這是我可以吃的東西，不然我不要。' WHERE entry=2000005331; /* content: Unless it\'s something I can eat, I don\'t want it. */
UPDATE db_script_string SET content_loc5='加爾，自從我來了以後你一點都不像從前的你。到底發生了什麼事?' WHERE entry=2000005332; /* content: Jarl, you haven\'t been yourself ever since I arrived. What\'s going on? */
UPDATE db_script_string SET content_loc5='沒事。想不想幫我攪拌一下那些青蛙腿燉肉呢?' WHERE entry=2000005333; /* content: Nothing. Wanna help me whip up some frog leg stew? */
UPDATE db_script_string SET content_loc5='我到這裡來是為了看你，加爾!結果我看你竟然住在一個空蕩蕩的小屋裡，四周是鳥不生蛋的地方，並且嘴裡講的竟然是關於青蛙的事情?你真是沒救了!' WHERE entry=2000005334; /* content: I came out here to visit you, Jarl! And I find you living in an empty cabin in the middle of nowhere, babbling about frogs? You\'re hopeless! */
UPDATE db_script_string SET content_loc5='而我下決心要找出更多相關的東西...如果你還需要我的幫助，你知道我會在哪裡。' WHERE entry=2000005335; /* content: And I am determined to find out more... So if you need my help again, you know where I\'ll be. */
UPDATE db_script_string SET content_loc5='安娜雅...?我的雙眼沒有欺騙我嗎?真的是你嗎?' WHERE entry=2000005336; /* content: Anaya...? Do my eyes deceive me? Is it really you? */
UPDATE db_script_string SET content_loc5='歲月對我和你都很殘酷，我的愛人...但最後我們還是重逢了。' WHERE entry=2000005337; /* content: The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited. */
UPDATE db_script_string SET content_loc5='命運是如此殘酷，它讓我們在分別了數千年之後才能重逢...' WHERE entry=2000005338; /* content: That the fates should be so cruel as to permit us only this after a thousand years apart... */
UPDATE db_script_string SET content_loc5='我的愛人，你恨我嗎?我在萬般無奈之下摧毀了你的軀殼，因為只有這樣才能讓你從痛苦中永久地解脫。' WHERE entry=2000005339; /* content: Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage. */
UPDATE db_script_string SET content_loc5='親愛的，不要為此而感到內疚。你使我從無盡的苦楚和折磨中解脫了出來，我只會為此而更加愛你。' WHERE entry=2000005340; /* content: Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more. */
UPDATE db_script_string SET content_loc5='但是，即使是這經過數千年的分離才換來的重逢也是如此短暫...我和這個世界的聯結正在逐漸減弱，我正在慢慢地離開它...離開你...' WHERE entry=2000005341; /* content: Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away... */
UPDATE db_script_string SET content_loc5='不!安娜雅...安娜雅!請不要離開我!不...' WHERE entry=2000005342; /* content: No! Anaya... Anaya! Don\'t leave me! Please... */
UPDATE db_script_string SET content_loc5='再見了，塞瑞利恩，我的愛人。我們終能再見...' WHERE entry=2000005343; /* content: Farewell, Cerellean, until we are joined once again... */
UPDATE db_script_string SET content_loc5='怎麼辦，我的愛人?沒有你，我怎麼辦...沒有你...我如何有勇氣在這個世界上生存...' WHERE entry=2000005345; /* content: How, my love? How will I find the strength to face the ages of the world without you by my side... */
UPDATE db_script_string SET content_loc5='嗨，吉札!哈拉薩米區又有十七份訂單了。重綠礦石的市場已全部崩潰了，正如你所預期。' WHERE entry=2000005362; /* content: Hail, Gezhe!  Seventeen more orders have been placed in the Hara\'samid Sector.  The markets of heavy veldarite have all but collapsed, as you predicted. */
UPDATE db_script_string SET content_loc5='海拉茲出口物價正在上升，長官。我們已收買了適宜的課稅官員，走私品這幾天就會開始到貨了。' WHERE entry=2000005363; /* content: Heraazi exports are on the rise, sir.  We\'ve already bribed the appropriate taxation officers and contraband will begin to arrive within days. */
UPDATE db_script_string SET content_loc5='沒什麼特別的事。帶些真正的消息回來好嗎?' WHERE entry=2000005364; /* content: Nothing surprising there.  Come back with some real news, will you? */
UPDATE db_script_string SET content_loc5='正如我所預期。非常好，退下吧。' WHERE entry=2000005365; /* content: As expected.  Very well, dismissed. */
UPDATE db_script_string SET content_loc5='尊命，長官。' WHERE entry=2000005366; /* content: By your leave, sir. */
UPDATE db_script_string SET content_loc5='如果你在這裡，那就表明你已經準備好去研究召喚惡魔的方法了。我們將從最低級的生物召喚開始，然後再慢慢進階。讓我們開始吧。' WHERE entry=2000005367; /* content: If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. */
UPDATE db_script_string SET content_loc5='最容易召喚的是小鬼。你的能力也許已經遠遠超過召喚小鬼的水準，但是我們為了保證召喚教學的完整性，所以還是從召喚它開始吧。' WHERE entry=2000005368; /* content: The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him. */
UPDATE db_script_string SET content_loc5='這些邪惡的小傢伙就是小鬼。它很小而且很瘦弱，顯然是不能做為肉盾使用的，而它的威力也不大。這種召喚生物最好是在多人組隊的時候作為支援力量使用。' WHERE entry=2000005369; /* content: This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. */
UPDATE db_script_string SET content_loc5='現在你已經瞭解了小鬼的特性，那麼讓我們繼續研究下一種你可以召喚的生物:虛無行者。' WHERE entry=2000005370; /* content: Now that you have had a chance to study the imp, let us move on to the next minion you will be able to summon, the voidwalker. */
UPDATE db_script_string SET content_loc5='這種惡魔被稱為虛無行者。它的力量和耐力都非常驚人，可以出色地勝任防禦任務。首先控制它來攻擊你的敵人，這樣就能保證你在有肉盾保護的情況下安全地使用法術和技能。' WHERE entry=2000005371; /* content: This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life. */
UPDATE db_script_string SET content_loc5='如果你還沒有看見過虛空行者，那你一定要去看看。這種生物看起來就極具氣勢，而且在戰場上也能發揮很強的作用。接下來，讓我們看看所有男性學員都在熱切期盼的召喚生物:魅魔。' WHERE entry=2000005372; /* content: If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. */
UPDATE db_script_string SET content_loc5='好了。除了和前面那兩種召喚生物的外形有著明顯的差異之外，魅魔的攻擊能力也非常可觀。然而，她的防禦力很差，所有很難作為肉盾來使用。' WHERE entry=2000005373; /* content: All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. */
UPDATE db_script_string SET content_loc5='努力學習，總有一天你們也可以召喚魅魔的，但現在我們要繼續課程了，下一講是惡魔獵犬。' WHERE entry=2000005374; /* content: Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter. */
UPDATE db_script_string SET content_loc5='現在你們看到的就是惡魔獵犬。這種生物擁有法力燃燒等多種技能，這些技能在對付施法型的敵人時是十分有用的。' WHERE entry=2000005375; /* content: What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. */
UPDATE db_script_string SET content_loc5='當遇見施法者的時候，這種惡魔是你最好的朋友。現在，讓我們進行一下講的課程。這種召喚生物主要被用來幫助你更快地旅行。它就是惡魔戰馬。' WHERE entry=2000005376; /* content: When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed. */
UPDATE db_script_string SET content_loc5='所有的召喚生物都介紹完畢了。召喚課程已經結束。新的課程將會很快開始，如果你要想要得到進一步的提高，那就請不要走遠，先在周圍轉轉。' WHERE entry=2000005378; /* content: There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. */
UPDATE db_script_string SET content_loc5='呼!我的幸運帽在這。我到處在找它。' WHERE entry=2000005379; /* content: Phew! There\'s my lucky hat. I\'ve been looking for it everywhere. */
UPDATE db_script_string SET content_loc5='我不知道我在想什麼，沒帶我的劍就出去了。如果我有看到它在這裡就會帶著它了...' WHERE entry=2000005380; /* content: I don\'t know what I was thinking, going out without my sword. I would\'ve put it on if I\'d seen it here... */
UPDATE db_script_string SET content_loc5='我不可能不穿我的披風就出門。我希望它在這裡...' WHERE entry=2000005381; /* content: I can\'t possibly go out without my cloak. I hope it\'s in here... */
UPDATE db_script_string SET content_loc5='在這裡!我發誓我上次看的時候它不在這裡...' WHERE entry=2000005382; /* content: There it is! I could\'ve sworn it wasn\'t here last time I checked... */
UPDATE db_script_string SET content_loc5='沒有一個好聽的床邊故事我沒辦法睡。現在我可以好好休息了。' WHERE entry=2000005383; /* content: I can\'t sleep without a good bedtime story. Now I\'m certain to rest well. */
UPDATE db_script_string SET content_loc5='牧師在寧靜的祈禱中跪下。' WHERE entry=2000005409; /* content: The priest kneels in silent prayer. */
UPDATE db_script_string SET content_loc5='聖光，給我力量。' WHERE entry=2000005410; /* content: Light, give me strength. */
UPDATE db_script_string SET content_loc5='聖光，引領墮落的人們從不真實到真實，從黑暗到光明，和從死亡到不朽。' WHERE entry=2000005411; /* content: Light, lead the fallen from untruth to truth, from darkness to Light and from death to immortality. */
UPDATE db_script_string SET content_loc5='不～～～～!!!' WHERE entry=2000005415; /* content: NOOOOO!!! */
UPDATE db_script_string SET content_loc5='朋友...我讓你失望了...' WHERE entry=2000005416; /* content: Friends... I\'ve failed you... */
UPDATE db_script_string SET content_loc5='不我的朋友...我們讓你失望了...我們讓你失望了。' WHERE entry=2000005417; /* content: No my friend... we failed you... we failed you. */
UPDATE db_script_string SET content_loc5='%s拾起納迦旗。' WHERE entry=2000005418; /* content: %s picks up the naga flag. */
UPDATE db_script_string SET content_loc5='是什麼大事，火花?你為何發起這次會面?' WHERE entry=2000005419; /* content: What\'s the big idea, Spark? Why\'d you call for this meeting? */
UPDATE db_script_string SET content_loc5='是什麼大事?你差點毀了我的掩護，白痴!我跟你說過要把指南針和航海地圖放到安全一點的地方 - 不是任何蠢蛋都會發現的大庭廣眾之下。' WHERE entry=2000005420; /* content: What\'s the big idea? You nearly blew my cover, idiot! I told you to put the compass and navigation maps somewhere safe - not out in the open for any fool to discover. */
UPDATE db_script_string SET content_loc5='主人已經努力掩飾艾克索達的下落。你可能會毀了整個運作，包括我們在裡面的間諜掩護。' WHERE entry=2000005421; /* content: The Master has gone to great lengths to secure information about the whereabouts of the Exodar. You could have blown the entire operation, including the cover of our spy on the inside. */
UPDATE db_script_string SET content_loc5='放輕鬆，火花!一切都在我的掌控中。我們將會在艾克索達下方開始探採 - 讓我們兩人都變得非常、非常富有。' WHERE entry=2000005422; /* content: Relax, Spark! I have it all under control. We\'ll strip mine the Exodar right out from under \'em - making both you and I very, very rich in the process. */
UPDATE db_script_string SET content_loc5='放輕鬆?你知道凱爾薩斯怎麼對付那些辜負他的人嗎，吉索?永遠的痛苦與折磨...別搞砸了，笨蛋。' WHERE entry=2000005423; /* content: Relax? Do you know what Kael\'thas does to those that fail him, Geezle? Eternal suffering and pain... Do NOT screw this up, fool. */
UPDATE db_script_string SET content_loc5='我們的血謎斥候已和我們聯絡上。那個笨蛋，費倫，很快就會門戶洞開毫無防禦 - 足以讓我們一舉拿下!現在趁我還沒把你蒸發前快離開我的視線...' WHERE entry=2000005424; /* content: Our Bloodmyst scouts have located our contact. The fool, Velen, will soon leave himself open and defenseless -- long enough for us to strike! Now get out of my sight before I vaporize you... */
UPDATE db_script_string SET content_loc5='是的，長官。不會再有下次了...' WHERE entry=2000005425; /* content: Yes, sir. It won\'t happen again... */
UPDATE db_script_string SET content_loc5='非常感謝你!' WHERE entry=2000005544; /* content: You have my thanks! */
UPDATE db_script_string SET content_loc5='我的佩劍阿契厄斯伴隨了我一生，但是現在我的靈魂已經脫離了痛苦，我已經不再需要它了。' WHERE entry=2000005546; /* content: My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer. */
UPDATE db_script_string SET content_loc5='我希望能得到我女兒的愛，也希望我犯下的罪惡能夠得到寬恕。' WHERE entry=2000005547; /* content: I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins. */

SET NAMES 'latin1';
