-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc8='Иезекииль сказал, что у вас есть одна книга...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc8='Пусть маршал Виндзор знает, что я готова.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc8='Я готова, как и мои войска. Давайте закончим этот маскарад!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc8='Уделите мне минутку вашего времени, сэр.' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc8='Я готова, Оронок. Давай уничтожим Цируха и освободим духов!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc8='Поверните ключ, чтобы запустить механизм.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc8='Открой дверь во внутренний двор.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc8='Идем!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc8='Я готова.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc8='Ты свободен, Дугал! Выбирайся отсюда!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc8='Выбирайся отсюда, Тобиас, ты свободен!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc8='Расскажите подробнее.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc8='Что еще вы хотели сказать?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc8='Я не сделала ни одной ошибки.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc8='Ты совсем свихнулся, Нефарий. Ты разговариваешь загадками.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc8='Давай.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc8='Не могу, Валестраз! Ведь есть же какой-то способ тебя вылечить!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc8='Валестраз, нет!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc8='Давай разберемся.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc8='Посмотрим, что у тебя есть.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc8='Я не актер.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc8='Хорошо, тогда я попробую.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc8='Никогда еще не была так готова!' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc8='Волк будет побежден.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc8='Управление Рубакой' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc8='Управление Волком' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc8='Управление Призванным демоном' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc8='Управление Чернокнижником' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc8='Управление Некролитом' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc8='Управление Боевым вождем Черноруком' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc8='Контроль над пехотинцем людей' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc8='Управление Кудесником' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc8='Управление Священником' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc8='Управление королем Ллейном' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc8='Пожалуйста, расставь фигуры заново: мы хотим сыграть еще раз.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc8='А почему, бабушка, у тебя такие большие уши?' WHERE entry=-3532019; /* content: Oh, grandmother, what big ears you have. */
UPDATE gossip_texts SET content_loc8='О, бабушка, какие у тебя большие глаза!' WHERE entry=-3532020; /* content: Oh, grandmother, what big eyes you have. */
UPDATE gossip_texts SET content_loc8='О, бабушка, какая у тебя большая добыча!' WHERE entry=-3532021; /* content: Oh, grandmother, what phat lewts you have. */
UPDATE gossip_texts SET content_loc8='Мои спутники и я – с вами, леди Праудмур.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='Мы готовы встретить любого, кого пошлет Архимонд, леди Праудмур.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='До новой встречи, леди Праудмур!' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='Я с тобой, Тралл.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc8='Нам нечего бояться.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc8='До встречи, Тралл.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc8='Любая ваша помощь будет неоценима, жрица.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc8='Мы готовы забрать тебя отсюда, Тралл! Пошли!' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc8='Мне нужна упаковка зажигательных бомб.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc8='Тарета тебя не видит, Тралл.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc8='Все очень непросто, Тралл. Тебе сейчас лучше будет укрыться в горах, пока не пришли новые бойцы Блэкмора. Мы проследим, чтобы Тарета оказалась в безопасности.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc8='Мы готовы, Тралл!' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc8='Странный волшебник?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc8='Мельница Таррен' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc8='Я с тобой, Акама.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc8='Я готова, Акама!' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc8='Мы готовы встретиться с Иллиданом лицом к лицу.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc8='Спасибо на добром слове, но мы хотим побродить по Зул\'Аману.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */

SET NAMES 'latin1';
