-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc8='Расскажите подробнее.' WHERE entry=-3409000; -- content: Tell me more.
UPDATE gossip_texts SET content_loc8='Посмотрим, что у тебя есть.' WHERE entry=-3509001; -- content: Let\'s see what you have.
UPDATE gossip_texts SET content_loc8='Я не актер.' WHERE entry=-3532001; -- content: I\'m not an actor.
UPDATE gossip_texts SET content_loc8='Управление Боевым вождем Черноруком' WHERE entry=-3532011; -- content: Control Warchief Blackhand
UPDATE gossip_texts SET content_loc8='Мы готовы забрать тебя отсюда, Тралл! Пошли!' WHERE entry=-3560000; -- content: We are ready to get you out of here, Thrall. Let\'s go!
UPDATE gossip_texts SET content_loc8='Мне нужна упаковка зажигательных бомб.' WHERE entry=-3560001; -- content: I need a pack of Incendiary Bombs.
UPDATE gossip_texts SET content_loc8='Тарета тебя не видит, Тралл.' WHERE entry=-3560002; -- content: Taretha cannot see you, Thrall.
UPDATE gossip_texts SET content_loc8='Все очень непросто, Тралл. Тебе сейчас лучше будет укрыться в горах, пока не пришли новые бойцы Блэкмора. Мы проследим, чтобы Тарета оказалась в безопасности.' WHERE entry=-3560003; -- content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe.
UPDATE gossip_texts SET content_loc8='Мы готовы, Тралл!' WHERE entry=-3560004; -- content: We\'re ready, Thrall.
UPDATE gossip_texts SET content_loc8='Странный волшебник?' WHERE entry=-3560005; -- content: Strange wizard?
UPDATE gossip_texts SET content_loc8='Мельница Таррен' WHERE entry=-3560007; -- content: Tarren Mill.
UPDATE gossip_texts SET content_loc8='Я с тобой, Акама.' WHERE entry=-3564000; -- content: I\'m with you, Akama.

SET NAMES 'latin1';
