-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc7='[PH] SD3 texto desconocido' WHERE entry=-3000000; /* content: [PH] SD3 unknown text */
UPDATE gossip_texts SET content_loc7='Ezekiel dijo que tú podrías tener cierto libro...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc7='Haz saber al mariscal Windsor que ya estoy lista.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc7='Estoy lista; y también lo están mis tropas. ¡Acabemos con esta farsa!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc7='Necesito un momento de su tiempo, señor.' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc7='Estoy preparada, Oronok. ¡Destruyamos a Cyrukh y liberemos los elementos!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc7='Por qué ... sí, por supuesto. Tengo algo que mostrarle dentro de este edificio, Sr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc7='Gira la llave para poner en marcha la máquina.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc7='Estoy listo, anacoreta. Comencemos el exorcismo.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc7='Por favor, abre la cerradura de la puerta del patio.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc7='¡Que empiece la sesión!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc7='Estoy lista para empezar.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc7='¡Eres libre, Dughal! ¡Márchate!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc7='¡Sal de aquí, Tobias! ¡Eres libre!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc7='Tu esclavitud ha llegado a su fin, Doom\'rel. ¡Te desafío!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc7='Cuéntame más.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc7='¿Qué más tienes que decir?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc7='Nos desafiaste y hemos venido. ¿De dónde es este maestro del que hablas?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc7='No he cometido ningún error.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc7='Has perdido la cabeza, Nefarius. Hablas con acertijos.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc7='Hazlo, por favor.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc7='¡No puedo, Vaelastrasz! ¡Tiene que haber algo que podamos hacer para curarte!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc7='¡¡¡Vaelastrasz, no!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc7='Comprobémoslo.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc7='Veamos qué tienes.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc7='Teletransportarme a la biblioteca del guardián' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc7='No soy actriz.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc7='De acuerdo, lo intentaré.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc7='Nunca he estado más preparada.' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc7='El lobo está bajando.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc7='Controlar bruto orco' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc7='Controlar lobo orco' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc7='Controlar belcebú invocado' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc7='Controlar orco brujo' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc7='Controlar necrólito orco' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc7='Controlar jefe de guerra Puño Negro' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc7='Controlar lacayo humano' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc7='Control del Cargador Humano' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc7='Control de Elemento de Agua Conjurada' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc7='Controlar conjurador humano' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc7='Controlar clérigo humano' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc7='Controlar rey Llane' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc7='Reinicia el tablero, queremos jugar de nuevo.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc7='Oh, abuela, qué orejas tan grandes tienes.' WHERE entry=-3532019; /* content: Oh, grandmother, what big ears you have. */
UPDATE gossip_texts SET content_loc7='Oh, abuelita, qué ojos más grandes tienes.' WHERE entry=-3532020; /* content: Oh, grandmother, what big eyes you have. */
UPDATE gossip_texts SET content_loc7='Oh, abuela, qué equipamiento de élite que tienes.' WHERE entry=-3532021; /* content: Oh, grandmother, what phat lewts you have. */
UPDATE gossip_texts SET content_loc7='Mis compañeros y yo estamos contigo, Lady Valiente.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Estamos listos para cualquier cosa que Archimonde nos mande, lady Valiente.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Hasta que nos volvamos a encontrar, Lady Valiente.' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Estoy contigo, Thrall.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc7='No tenemos nada que temer.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc7='Hasta que nos volvamos a encontrar, Thrall.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc7='Agradecería cualquier ayuda que me pudieras prestar, sacerdotisa.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc7='Estamos listos para sacarte de aquí, Thrall. ¡Vamos!' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc7='Necesito un paquete de bombas incendiarias.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc7='Taretha no puede verte, Thrall.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc7='La situación es bastante compleja, Thrall. Por ahora lo mejor será que te dirijas a las montañas antes de que aparezcan los hombres de Lodonegro. Me aseguraré de que Taretha no corra peligro.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc7='Estamos listos, Thrall.' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc7='¿Un zahorí extraño?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc7='Te sacaremos. Taretha. No te preocupes. Dudo que el mago se aleje demasiado.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc7='Molino Tarren.' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc7='Estoy contigo, Akama.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc7='Estoy listo, Akama.' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc7='Estamos listos para enfrentarnos a Illidan.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc7='Gracias por tu interés, pero tenemos intención de explorar Zul\'Aman.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */

SET NAMES 'latin1';
