-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE locales_page_Text SET text_loc3='managed to get the better of the ugly brute, but he\'s now nursing a nasty cut on his arm. Looks like I\'ll have to do the chores for a while. DAY THREE Cold. Snowed a bit around noon. DAY FOUR The lad was back and in good spirits today, so we took our first look at the trolls. Frostmane, I\'d say, judging by the markings on their skin and the various trinkets they wore on their bodies. ' WHERE entry=81; /* text: managed to get the better of the ugly brute, but he\'s now nursing a nasty cut on his arm. Looks like I\'ll have to do the chores for a while. DAY THREE Cold. Snowed a bit around noon. DAY FOUR The lad was back and in good spirits today, so we took our first look at the trolls. Frostmane, I\'d say, judging by the markings on their skin and the various trinkets they wore on their bodies. */
UPDATE locales_page_Text SET text_loc3='DAY FIVE Had the lad watch over the camp and I snuck over to the cave and took a look around. The trolls\' numbers are somewhat troublesome. The Mountaineers might have to be summoned in force if the cave is to be cleared of the troll infestation. I realize I have not mentioned the troggs of late. They appear in the area in greater numbers, but they are so primitive that they do not pose much of a threat. Time may say if this is true or not. ' WHERE entry=82; /* text: DAY FIVE Had the lad watch over the camp and I snuck over to the cave and took a look around. The trolls\' numbers are somewhat troublesome. The Mountaineers might have to be summoned in force if the cave is to be cleared of the troll infestation. I realize I have not mentioned the troggs of late. They appear in the area in greater numbers, but they are so primitive that they do not pose much of a threat. Time may say if this is true or not. */
UPDATE locales_page_Text SET text_loc3='And not a drop of ale for almost a week now. DAY SIX Cold again. Snows. Trolls. No ale. DAY SEVEN Snow below so white, Sky above so blue, Wolves will howl the night, Not a drop of brew. DAY EIGHT The trolls are perhaps not as large a problem as we initially thought. They have some ' WHERE entry=83; /* text: And not a drop of ale for almost a week now. DAY SIX Cold again. Snows. Trolls. No ale. DAY SEVEN Snow below so white, Sky above so blue, Wolves will howl the night, Not a drop of brew. DAY EIGHT The trolls are perhaps not as large a problem as we initially thought. They have some */
UPDATE locales_page_Text SET text_loc3='A Report on the State of the Frostmane Trolls in the General Area of Dun Morogh The trolls situated in Dun Morogh are largely centralized in Frostmane Hold, a mountain cave on the western border. They have sufficient numbers to cause some concern, however, they seem more than content to stay in their cave. This is, no doubt, because they do not wish to incur the wrath of the dwarves again, and risk total extermination. Their actions can be considered territorial, if anything, and it is ' WHERE entry=88; /* text: A Report on the State of the Frostmane Trolls in the General Area of Dun Morogh The trolls situated in Dun Morogh are largely centralized in Frostmane Hold, a mountain cave on the western border. They have sufficient numbers to cause some concern, however, they seem more than content to stay in their cave. This is, no doubt, because they do not wish to incur the wrath of the dwarves again, and risk total extermination. Their actions can be considered territorial, if anything, and it is */
UPDATE locales_page_Text SET text_loc3='my belief that they pose no real threat to us, so long as we do not encroach upon their territory. This may be a situation unappealing to the dwarven populace, but given the dispersal of military resources, it may be prudent to relegate the extermination of the trolls to a lower level of importance, and continue to focus on the threat posed by the troggs and the Dark Irons. Enclosed, you will also find a copy of my brother Grelin\'s report on Anvilmar. Signed, Senir Whitebeard ' WHERE entry=89; /* text: my belief that they pose no real threat to us, so long as we do not encroach upon their territory. This may be a situation unappealing to the dwarven populace, but given the dispersal of military resources, it may be prudent to relegate the extermination of the trolls to a lower level of importance, and continue to focus on the threat posed by the troggs and the Dark Irons. Enclosed, you will also find a copy of my brother Grelin\'s report on Anvilmar. Signed, Senir Whitebeard */
UPDATE locales_page_Text SET text_loc3='A Report on the State of the Frostmane Trolls in the General Area of Coldridge Valley Prepared by Grelin Whitebeard, Senate Special Envoy From the time that I have spent observing the movement of the Frostmane trolls in the Coldridge Valley area, I have determined that they pose no large threat to dwarven settlements in the area. Moreover, they are a threat that can be eliminated with little additional support from the army. Through the assistance of Mountaineers already stationed in ' WHERE entry=90; /* text: A Report on the State of the Frostmane Trolls in the General Area of Coldridge Valley Prepared by Grelin Whitebeard, Senate Special Envoy From the time that I have spent observing the movement of the Frostmane trolls in the Coldridge Valley area, I have determined that they pose no large threat to dwarven settlements in the area. Moreover, they are a threat that can be eliminated with little additional support from the army. Through the assistance of Mountaineers already stationed in */
UPDATE locales_page_Text SET text_loc3='Coldridge Valley and mercenaries (paid with funds set aside by the Senate prior to my dispatchment), I am confident that the problem will be solved in short order. This action has been authorized with the sanction given to me by King Bronzebeard. ' WHERE entry=91; /* text: Coldridge Valley and mercenaries (paid with funds set aside by the Senate prior to my dispatchment), I am confident that the problem will be solved in short order. This action has been authorized with the sanction given to me by King Bronzebeard. */
UPDATE locales_page_Text SET text_loc3='In the years that followed, after Stormwind betrayed the Stonemasons\' Guild, Sir Erlgadin grew bitter about the role of the nobles within the Kingdom.  He no longer wished to uphold the position that his father\'s bloodline had earned for him in the House of Nobles.
But I digress.  The purpose of this story is not to act as a political treatise or a biography.  This is the account of my experiences hunting big game in the green hills of Stranglethorn.' WHERE entry=98; /* text: In the years that followed, after Stormwind betrayed the Stonemasons\' Guild, Sir Erlgadin grew bitter about the role of the nobles within the Kingdom.  He no longer wished to uphold the position that his father\'s bloodline had earned for him in the House of Nobles.
But I digress.  The purpose of this story is not to act as a political treatise or a biography.  This is the account of my experiences hunting big game in the green hills of Stranglethorn. */
UPDATE locales_page_Text SET text_loc3='Here lies Uther the Lightbringer
First Paladin - Founder of the Order of the Silver Hand

Uther lived and died to defend the kingdom of Lordaeron. Though he was betrayed by his most beloved student, we believe that his spirit lives on. He continues to watch over us, even as the shadows close in around our ruined land. His light is the light of all humanity - and so long as we honor his example, it shall never fade. 
									- Anonymous' WHERE entry=292; /* text: Here lies Uther the Lightbringer
First Paladin - Founder of the Order of the Silver Hand

Uther lived and died to defend the kingdom of Lordaeron. Though he was betrayed by his most beloved student, we believe that his spirit lives on. He continues to watch over us, even as the shadows close in around our ruined land. His light is the light of all humanity - and so long as we honor his example, it shall never fade. 
									- Anonymous */
UPDATE locales_page_Text SET text_loc3='It should be noted here that this report bearer was instrumental in not only the success of our mission, but also in the defeat of Ivar the Foul, the rescue of Erland, and the deliverance of this report. We extend our gratitude, and recommend that command acknowledges this individual with awards befitting such meritorious conduct as was displayed in the field. -Deathstalker Rane Yorick, Mission Leader ' WHERE entry=386; /* text: It should be noted here that this report bearer was instrumental in not only the success of our mission, but also in the defeat of Ivar the Foul, the rescue of Erland, and the deliverance of this report. We extend our gratitude, and recommend that command acknowledges this individual with awards befitting such meritorious conduct as was displayed in the field. -Deathstalker Rane Yorick, Mission Leader */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures9330_Gammerita_sepia_256"/> </BODY> </HTML> ' WHERE entry=1190; /* text: <HTML> <BODY> <IMG src="InterfacePictures9330_Gammerita_sepia_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="InterfacePicturesLinken_sepia_256px"/>
</BODY>
</HTML>' WHERE entry=1371; /* text: <HTML>
<BODY>
<IMG src="InterfacePicturesLinken_sepia_256px"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePicturesLinken_sepia_256px"/> </BODY> </HTML> ' WHERE entry=1391; /* text: <HTML> <BODY> <IMG src="InterfacePicturesLinken_sepia_256px"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
Chapter 1: THE NORTHERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_north" align="left"/>
<P align="right">The Northern<BR/>
Pylon accepts<BR/>
yellow, red,<BR/>
and green<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using yellow crystals as the main source of power.</P>
</BODY>
</HTML>' WHERE entry=1511; /* text: <HTML>
<BODY>
<H1 align="center">
Chapter 1: THE NORTHERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_north" align="left"/>
<P align="right">The Northern<BR/>
Pylon accepts<BR/>
yellow, red,<BR/>
and green<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using yellow crystals as the main source of power.</P>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
NORTHERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_north"/>
</BODY>
</HTML>' WHERE entry=1513; /* text: <HTML>
<BODY>
<H1 align="center">
NORTHERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_north"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
Chapter 2: THE EASTERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_east" align="left"/>
<P align="right">The Eastern<BR/>
Pylon accepts<BR/>
blue, yellow,<BR/>
and green<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using blue crystals as the main source of power.</P>
</BODY>
</HTML>' WHERE entry=1514; /* text: <HTML>
<BODY>
<H1 align="center">
Chapter 2: THE EASTERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_east" align="left"/>
<P align="right">The Eastern<BR/>
Pylon accepts<BR/>
blue, yellow,<BR/>
and green<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using blue crystals as the main source of power.</P>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
EASTERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_east"/>
</BODY>
</HTML>' WHERE entry=1516; /* text: <HTML>
<BODY>
<H1 align="center">
EASTERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_east"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <H1 align="center"> EASTERN PYLON TABLE DIAGRAM </H1> <BR/> <IMG src="InterfacePictures11482_crystals_east"/> </BODY> </HTML> ' WHERE entry=1530; /* text: <HTML> <BODY> <H1 align="center"> EASTERN PYLON TABLE DIAGRAM </H1> <BR/> <IMG src="InterfacePictures11482_crystals_east"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
Chapter 3: THE WESTERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_west" align="left"/>
<P align="right">The Western<BR/>
Pylon accepts<BR/>
red, green,<BR/>
and blue<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using red crystals as the main source of power.</P>
</BODY>
</HTML>' WHERE entry=1531; /* text: <HTML>
<BODY>
<H1 align="center">
Chapter 3: THE WESTERN PYLON
</H1>
<BR/>
<BR/>
<IMG src="InterfacePictures11482_crystals_mini_west" align="left"/>
<P align="right">The Western<BR/>
Pylon accepts<BR/>
red, green,<BR/>
and blue<BR/>
crystals.</P>
<BR/>
<BR/>
<BR/>
<BR/>
<P align="left">The Pylon focuses on the energy that can be created using red crystals as the main source of power.</P>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">
WESTERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_west"/>
</BODY>
</HTML>' WHERE entry=1533; /* text: <HTML>
<BODY>
<H1 align="center">
WESTERN PYLON TABLE DIAGRAM
</H1>
<BR/>
<IMG src="InterfacePictures11482_crystals_west"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <H1 align="center"> WESTERN PYLON TABLE DIAGRAM </H1> <BR/> <IMG src="InterfacePictures11482_crystals_west"/> </BODY> </HTML> ' WHERE entry=1550; /* text: <HTML> <BODY> <H1 align="center"> WESTERN PYLON TABLE DIAGRAM </H1> <BR/> <IMG src="InterfacePictures11482_crystals_west"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="InterfacePictures11733_blackrock_256"/>
</BODY>
</HTML>
' WHERE entry=1639; /* text: <HTML>
<BODY>
<IMG src="InterfacePictures11733_blackrock_256"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="InterfacePictures11733_bldbank_256"/>
</BODY>
</HTML>
' WHERE entry=1640; /* text: <HTML>
<BODY>
<IMG src="InterfacePictures11733_bldbank_256"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="InterfacePictures11733_ungoro_256"/>
</BODY>
</HTML>
' WHERE entry=1641; /* text: <HTML>
<BODY>
<IMG src="InterfacePictures11733_ungoro_256"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> ' WHERE entry=1642; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_blasted_256"/> </BODY> </HTML> ' WHERE entry=1643; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_blasted_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> ' WHERE entry=1644; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> ' WHERE entry=1645; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_bldbank_256"/> </BODY> </HTML> ' WHERE entry=1646; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_bldbank_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_blasted_256"/> </BODY> </HTML> ' WHERE entry=1647; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_blasted_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> ' WHERE entry=1648; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> ' WHERE entry=1649; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_bldbank_256"/> </BODY> </HTML> ' WHERE entry=1650; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_bldbank_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_whipper_256"/> </BODY> </HTML> ' WHERE entry=1651; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_whipper_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML>
' WHERE entry=1652; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> ' WHERE entry=1690; /* text: <HTML> <BODY> <IMG src="InterfacePictures11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='Hi Felnok! My studies in the Burning Steppes are proceeding splendidly.  And I owe $N a lot for all $ghis:her; help!  Here\'s what I need to continue: A steelcoil bumber-bitzel A 17-guage ice-spanner 12 pounds of duck feathers A jar of that glue you make Thanks a lot Felnok, and when we see each other again remind me not to put coal in your boots! -Tinkee ' WHERE entry=1710; /* text: Hi Felnok! My studies in the Burning Steppes are proceeding splendidly.  And I owe $N a lot for all $ghis:her; help!  Here\'s what I need to continue: A steelcoil bumber-bitzel A 17-guage ice-spanner 12 pounds of duck feathers A jar of that glue you make Thanks a lot Felnok, and when we see each other again remind me not to put coal in your boots! -Tinkee */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <IMG src="InterfacePictures14679_Tirion_256"/> </BODY> </HTML> ' WHERE entry=2370; /* text: <HTML> <BODY> <IMG src="InterfacePictures14679_Tirion_256"/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='Welcome to the World of Warcraft!

We Mage\'s are the most powerfull Magic user\'s We combine Fire and Frost to get maximum effect And we will help evrything that need\'s it So go and learn the magic of exploring !

' WHERE entry=2602; /* text: Welcome to the World of Warcraft!

We Mage\'s are the most powerfull Magic user\'s We combine Fire and Frost to get maximum effect And we will help evrything that need\'s it So go and learn the magic of exploring ! */
UPDATE locales_page_Text SET text_loc3='Welcome to the World of Warcraft!

Warlock a mysterious class... We are the most powerfull when it come\'s to using magic I know "mage is most powerfull with spells bla bla bla..." Forget that we Warlock\'s evolved from Mage\'s so we actualy are more powerfull....

' WHERE entry=2603; /* text: Welcome to the World of Warcraft!

Warlock a mysterious class... We are the most powerfull when it come\'s to using magic I know "mage is most powerfull with spells bla bla bla..." Forget that we Warlock\'s evolved from Mage\'s so we actualy are more powerfull.... */
UPDATE locales_page_Text SET text_loc3='Welcome to the World of Warcraft!

Our Tribe has awakened youre power\'s my child... Now you are a Druid so called Hybrid.. You combine the force of the warrior, the intelect of the Mage\'s, The rejuvination magic from the Shaman\'s.... We are unique you must alway\'s help youre friend\'s, becouse we Druid\'s are the Ultimate support a humanoid can get!

' WHERE entry=2604; /* text: Welcome to the World of Warcraft!

Our Tribe has awakened youre power\'s my child... Now you are a Druid so called Hybrid.. You combine the force of the warrior, the intelect of the Mage\'s, The rejuvination magic from the Shaman\'s.... We are unique you must alway\'s help youre friend\'s, becouse we Druid\'s are the Ultimate support a humanoid can get! */
UPDATE locales_page_Text SET text_loc3='Credit\'s Main:
Quest scripter\'s:
==============================
Shultz. Thesleby. Rest of !rpg Team.

' WHERE entry=2605; /* text: Credit\'s Main:
Quest scripter\'s:
==============================
Shultz. Thesleby. Rest of !rpg Team. */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">A TREATISE ON MILITARY RANKS</H1>
<BR/>
<BR/>
<IMG src="InterfacePvPRankBadgesPvPRankAlliance" align="left"/>
<BR/>
<P align="right">What follows are</P>
<P align="right">the military ranks</P>
<P align="right">of the Alliance,</P>
<P align="right">proceeded by such</P>
<P align="right">information as is</P>
<P align="right">known for the races</P>
<P align="right">of the Horde.  Each</P>
<P align="right">is presented in two</P>
<P align="right">sections, the officers and then the enlisted, with the ranks of each listed in descending order from highest to lowest.  Long live the Alliance!</P>
</BODY>
</HTML>' WHERE entry=2654; /* text: <HTML>
<BODY>
<H1 align="center">A TREATISE ON MILITARY RANKS</H1>
<BR/>
<BR/>
<IMG src="InterfacePvPRankBadgesPvPRankAlliance" align="left"/>
<BR/>
<P align="right">What follows are</P>
<P align="right">the military ranks</P>
<P align="right">of the Alliance,</P>
<P align="right">proceeded by such</P>
<P align="right">information as is</P>
<P align="right">known for the races</P>
<P align="right">of the Horde.  Each</P>
<P align="right">is presented in two</P>
<P align="right">sections, the officers and then the enlisted, with the ranks of each listed in descending order from highest to lowest.  Long live the Alliance!</P>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">Grand Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Field Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Commander</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Lieutenant Commander</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2655; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">Grand Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Field Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Commander</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Lieutenant Commander</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Knight-Champion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Knight-Captain</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Knight-Lieutenant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Knight</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2656; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Knight-Champion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Knight-Captain</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Knight-Lieutenant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Knight</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">ENLISTED RANKS OF THE ALLIANCE</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">Sergeant Major</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Master Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Corporal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Private</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2657; /* text: <HTML>
<BODY>
<H1 align="center">ENLISTED RANKS OF THE ALLIANCE</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">Sergeant Major</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Master Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Corporal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Private</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">High Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Lieutenant General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Champion</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2658; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">High Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Lieutenant General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Champion</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML> <BODY> <H1 align="center">ENLISTED RANKS OF THE HORDE</H1><BR/> <IMG src="InterfacePvPRankBadgesPvPRank01"/><BR/> <P align="right">First Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank04"/><BR/> <P align="right">Senior Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank03"/><BR/> <P align="right">Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank02"/><BR/> <P align="right">Grunt</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank01"/><BR/> <P align="right">Scout</P><BR/><BR/> </BODY> </HTML> ' WHERE entry=2660; /* text: <HTML> <BODY> <H1 align="center">ENLISTED RANKS OF THE HORDE</H1><BR/> <IMG src="InterfacePvPRankBadgesPvPRank01"/><BR/> <P align="right">First Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank04"/><BR/> <P align="right">Senior Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank03"/><BR/> <P align="right">Sergeant</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank02"/><BR/> <P align="right">Grunt</P><BR/><BR/> <IMG src="InterfacePvPRankBadgesPvPRank01"/><BR/> <P align="right">Scout</P><BR/><BR/> </BODY> </HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">MILITARY RANKS OF THE HORDE &amp; ALLIANCE</H1>
<BR/>
<BR/>
<IMG src="InterfacePvPRankBadgesPvPRankHorde" align="left"/>
<BR/>
<P align="right">Throm\'ka!  In this</P>
<P align="right">book you will find</P>
<P align="right">many listings of</P>
<P align="right">the military ranks</P>
<P align="right">of the Horde and</P>
<P align="right">the puny Alliance.</P>
<P align="right">First will come the</P>
<P align="right">Horde, then the Alliance,</P>
<P align="right">each with listings of officers and enlisted ranks.  As is fitting, the strongest are listed at the top, with the weaker listed below them.</P>
</BODY>
</HTML>' WHERE entry=2661; /* text: <HTML>
<BODY>
<H1 align="center">MILITARY RANKS OF THE HORDE &amp; ALLIANCE</H1>
<BR/>
<BR/>
<IMG src="InterfacePvPRankBadgesPvPRankHorde" align="left"/>
<BR/>
<P align="right">Throm\'ka!  In this</P>
<P align="right">book you will find</P>
<P align="right">many listings of</P>
<P align="right">the military ranks</P>
<P align="right">of the Horde and</P>
<P align="right">the puny Alliance.</P>
<P align="right">First will come the</P>
<P align="right">Horde, then the Alliance,</P>
<P align="right">each with listings of officers and enlisted ranks.  As is fitting, the strongest are listed at the top, with the weaker listed below them.</P>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">High Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Lieutenant General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Champion</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2662; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">High Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Warlord</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Lieutenant General</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Champion</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Centurion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Legionnaire</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Blood Guard</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Stone Guard</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2663; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Centurion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Legionnaire</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Blood Guard</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Stone Guard</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">HORDE ENLISTED RANKS</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">First Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Senior Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Grunt</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Scout</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2664; /* text: <HTML>
<BODY>
<H1 align="center">HORDE ENLISTED RANKS</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">First Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Senior Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Grunt</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Scout</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">Grand Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Field Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Commander</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Lieutenant Commander</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2665; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 1</P>
<IMG src="InterfacePvPRankBadgesPvPRank14" align="left"/><BR/>
<P align="right">Grand Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank13" align="left"/><BR/>
<P align="right">Field Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank12" align="left"/><BR/>
<P align="right">Marshal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank11" align="left"/><BR/>
<P align="right">Commander</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank10" align="left"/><BR/>
<P align="right">Lieutenant Commander</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='Item Text Missing:2822' WHERE entry=2822; /* text: Item Text Missing:2822 */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Centurion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Legionnaire</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Blood Guard</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Stone Guard</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2854; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE HORDE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Centurion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Legionnaire</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Blood Guard</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Stone Guard</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">ENLISTED RANKS OF THE HORDE</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">First Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Senior Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Grunt</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Scout</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2855; /* text: <HTML>
<BODY>
<H1 align="center">ENLISTED RANKS OF THE HORDE</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">First Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Senior Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Grunt</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Scout</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Knight-Champion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Knight-Captain</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Knight-Lieutenant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Knight</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2856; /* text: <HTML>
<BODY>
<H1 align="center">OFFICER RANKS OF THE ALLIANCE</H1><BR/>
<P align="center">Part 2</P>
<IMG src="InterfacePvPRankBadgesPvPRank09" align="left"/><BR/>
<P align="right">Knight-Champion</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank08" align="left"/><BR/>
<P align="right">Knight-Captain</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank07" align="left"/><BR/>
<P align="right">Knight-Lieutenant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank06" align="left"/><BR/>
<P align="right">Knight</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<H1 align="center">ALLIANCE ENLISTED RANKS</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">Sergeant Major</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Master Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Corporal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Private</P><BR/><BR/>
</BODY>
</HTML>' WHERE entry=2857; /* text: <HTML>
<BODY>
<H1 align="center">ALLIANCE ENLISTED RANKS</H1><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank05" align="left"/><BR/>
<P align="right">Sergeant Major</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank04" align="left"/><BR/>
<P align="right">Master Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank03" align="left"/><BR/>
<P align="right">Sergeant</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank02" align="left"/><BR/>
<P align="right">Corporal</P><BR/><BR/>
<IMG src="InterfacePvPRankBadgesPvPRank01" align="left"/><BR/>
<P align="right">Private</P><BR/><BR/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='Esteemed leaders of the Horde,$B$BIt is with great pleasure that I - Lor\'themar Theron, Regent Lord of Quel\'Thalas - announce the fall of the Scourge commander known to us as Dar\'Khan Drathir.$B$BDar\'Khan\'s foothold in our lands was brought up by critics of the sin\'dorei race at numerous previous negotiations.  We hope this event addresses any and all previous objections your graces might have harbored.$B$B<Signed>Lor\'themar Theron' WHERE entry=2923; /* text: Esteemed leaders of the Horde,$B$BIt is with great pleasure that I - Lor\'themar Theron, Regent Lord of Quel\'Thalas - announce the fall of the Scourge commander known to us as Dar\'Khan Drathir.$B$BDar\'Khan\'s foothold in our lands was brought up by critics of the sin\'dorei race at numerous previous negotiations.  We hope this event addresses any and all previous objections your graces might have harbored.$B$B<Signed>Lor\'themar Theron */
UPDATE locales_page_Text SET text_loc3='Esteemed leaders of the Horde,$B$BIt is with great pleasure that I - Lor\'themar Theron, Regent Lord of Quel\'Thalas - announce the fall of the Scourge commander known to us as Dar\'Khan Drathir.$B$BDar\'Khan\'s foothold in our lands was brought up by critics of the sin\'dorei race at numerous previous negotiations.  We hope this event addresses any and all previous objections your graces might have harbored.$B$B<Signed>Lor\'themar Theron' WHERE entry=2924; /* text: Esteemed leaders of the Horde,$B$BIt is with great pleasure that I - Lor\'themar Theron, Regent Lord of Quel\'Thalas - announce the fall of the Scourge commander known to us as Dar\'Khan Drathir.$B$BDar\'Khan\'s foothold in our lands was brought up by critics of the sin\'dorei race at numerous previous negotiations.  We hope this event addresses any and all previous objections your graces might have harbored.$B$B<Signed>Lor\'themar Theron */
UPDATE locales_page_Text SET text_loc3='Trans-dimensional Ship Repair for Simpletons, by Jamus Kaesi$B$B<The thin pages of this book are made from a shimmering material and are filled with highly technical diagrams of how to maintain and repair a trans-dimensional ship. This particular copy is open to a chapter entitled \'Vector Coil Breaches and How to Avoid Them.\'>' WHERE entry=2925; /* text: Trans-dimensional Ship Repair for Simpletons, by Jamus Kaesi$B$B<The thin pages of this book are made from a shimmering material and are filled with highly technical diagrams of how to maintain and repair a trans-dimensional ship. This particular copy is open to a chapter entitled \'Vector Coil Breaches and How to Avoid Them.\'> */
UPDATE locales_page_Text SET text_loc3='$B$BPS - Our grand magister has received word back from Outland regarding Thrall\'s question.  The answer is, with great certainty, yes.' WHERE entry=2926; /* text: $B$BPS - Our grand magister has received word back from Outland regarding Thrall\'s question.  The answer is, with great certainty, yes. */
UPDATE locales_page_Text SET text_loc3='PS - Our grand magister has received word back from Outland regarding Thrall\'s question.  The answer is, with great certainty, yes.$B$B<This letter bears the additional seal of Lady Sylvanas Windrunner>' WHERE entry=2927; /* text: PS - Our grand magister has received word back from Outland regarding Thrall\'s question.  The answer is, with great certainty, yes.$B$B<This letter bears the additional seal of Lady Sylvanas Windrunner> */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<IMG src="InterfacePictures24475_gordawg_256"/>
</BODY>
</HTML>' WHERE entry=2944; /* text: <HTML>
<BODY>
<IMG src="InterfacePictures24475_gordawg_256"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='Servant.

These orcs are becoming more than a minor annoyance. I want you to personally see to it that our forces attacking the defenders at the Dark Portal direct all of their energy into laying waste to Thrallmar.

Consider this an order,

Arazzius' WHERE entry=2981; /* text: Servant.

These orcs are becoming more than a minor annoyance. I want you to personally see to it that our forces attacking the defenders at the Dark Portal direct all of their energy into laying waste to Thrallmar.

Consider this an order,

Arazzius */
UPDATE locales_page_Text SET text_loc3='Servant.

These orcs are becoming more than a minor annoyance. I want you to personally see to it that our forces attacking the defenders at the Dark Portal direct all of their energy into laying waste to Thrallmar.

Consider this an order,

Arazzius' WHERE entry=2982; /* text: Servant.

These orcs are becoming more than a minor annoyance. I want you to personally see to it that our forces attacking the defenders at the Dark Portal direct all of their energy into laying waste to Thrallmar.

Consider this an order,

Arazzius */
UPDATE locales_page_Text SET text_loc3='<HTML>
<BODY>
<BR/>
<H1 align="center">LAMENT OF THE HIGHBORNE</H1>
<BR/>
<IMG src="InterfaceFlavorImagesBloodElfLogo-small"/>
</BODY>
</HTML>' WHERE entry=2990; /* text: <HTML>
<BODY>
<BR/>
<H1 align="center">LAMENT OF THE HIGHBORNE</H1>
<BR/>
<IMG src="InterfaceFlavorImagesBloodElfLogo-small"/>
</BODY>
</HTML> */
UPDATE locales_page_Text SET text_loc3='The mighty creature\'s maw opened wide, tossing bolts of icy water toward our vessel. Those terrible jaws clamped down upon the bow of our ship, tearing it from the hull. Sailors and cargo were thrown violently into the sea as the remnants of the ship disappeared beneath the waves.$B$BThe last thing I remember was flying from the broken hull, hitting the inky waters, and plunging beneath the waves. The world went dark and I thought for certain I\'d drawn my last breath. When I awoke in Theramore\'s infirmary, I knew someone had to tell our story.' WHERE entry=3036; /* text: The mighty creature\'s maw opened wide, tossing bolts of icy water toward our vessel. Those terrible jaws clamped down upon the bow of our ship, tearing it from the hull. Sailors and cargo were thrown violently into the sea as the remnants of the ship disappeared beneath the waves.$B$BThe last thing I remember was flying from the broken hull, hitting the inky waters, and plunging beneath the waves. The world went dark and I thought for certain I\'d drawn my last breath. When I awoke in Theramore\'s infirmary, I knew someone had to tell our story. */
UPDATE locales_page_Text SET text_loc3='First Watch, Eight Bells$BWatches changed.  All is well.' WHERE entry=3045; /* text: First Watch, Eight Bells$BWatches changed.  All is well. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, One Bell$BCedric found attempting to break into Captain\'s wine cabinet.  Disciplined.' WHERE entry=3046; /* text: Middle Watch, One Bell$BCedric found attempting to break into Captain\'s wine cabinet.  Disciplined. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, Two Bells$BCedric climbed rigging, became tangled and fell.  Attended by ship\'s surgeon.  Sent below to sober up.' WHERE entry=3047; /* text: Middle Watch, Two Bells$BCedric climbed rigging, became tangled and fell.  Attended by ship\'s surgeon.  Sent below to sober up. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, Four Bells$BBottle of rum found in Cedric\'s pants.  Disciplined.' WHERE entry=3049; /* text: Middle Watch, Four Bells$BBottle of rum found in Cedric\'s pants.  Disciplined. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, Five Bells$BCedric\'s clothes found.  Cedric found separately.  Cedric disciplined.' WHERE entry=3050; /* text: Middle Watch, Five Bells$BCedric\'s clothes found.  Cedric found separately.  Cedric disciplined. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, Six Bells$BCedric singing loudly.  Woke Captain.  Cedric disciplined by Captain.' WHERE entry=3051; /* text: Middle Watch, Six Bells$BCedric singing loudly.  Woke Captain.  Cedric disciplined by Captain. */
UPDATE locales_page_Text SET text_loc3='Middle Watch, Eight Bells$BWatches changed.  All quiet.  Two men sent to locate Cedric.$B' WHERE entry=3052; /* text: Middle Watch, Eight Bells$BWatches changed.  All quiet.  Two men sent to locate Cedric.$B */
UPDATE locales_page_Text SET text_loc3='Morning Watch, One Bell$BFire in Captain\'s quarters.  All hands roused.  Throwing powder overboard. ' WHERE entry=3053; /* text: Morning Watch, One Bell$BFire in Captain\'s quarters.  All hands roused.  Throwing powder overboard. */
UPDATE locales_page_Text SET text_loc3='Howdy! You have found a loot bug in TBC-DB. We are terribly sorry about that, and we will try and fix it just as SOON as possible. However, You need to help us a little bit. If you will go to http://udb.no-ip.org/ and fill out a TBC-DB loot bug report, with the location you found this, we will try and get it fixed ASAP. Thanks, the TBC-DB team!' WHERE entry=9999; /* text: Howdy! You have found a loot bug in TBC-DB. We are terribly sorry about that, and we will try and fix it just as SOON as possible. However, You need to help us a little bit. If you will go to http://udb.no-ip.org/ and fill out a TBC-DB loot bug report, with the location you found this, we will try and get it fixed ASAP. Thanks, the TBC-DB team! */

SET NAMES 'latin1';
