-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='Zaldimar Wefhellt' WHERE `word_id` = 72463; -- locales_points_of_interest - icon_name : entry=2
UPDATE `trans_words` SET `content_loc3`='Keryn Sylvius' WHERE `word_id` = 72902; -- locales_points_of_interest - icon_name : entry=5
UPDATE `trans_words` SET `content_loc3`='Lyria Du Lac' WHERE `word_id` = 72897; -- locales_points_of_interest - icon_name : entry=7
UPDATE `trans_words` SET `content_loc3`='Tomas' WHERE `word_id` = 73402; -- locales_points_of_interest - icon_name : entry=10
UPDATE `trans_words` SET `content_loc3`='Michelle Belle' WHERE `word_id` = 74081; -- locales_points_of_interest - icon_name : entry=11
UPDATE `trans_words` SET `content_loc3`='Eldrin' WHERE `word_id` = 73064; -- locales_points_of_interest - icon_name : entry=16
UPDATE `trans_words` SET `content_loc3`='Erma' WHERE `word_id` = 77425; -- locales_points_of_interest - icon_name : entry=17
UPDATE `trans_words` SET `content_loc3`='Stormwind Locksmith' WHERE `word_id` = 127250; -- locales_points_of_interest - icon_name : entry=25
UPDATE `trans_words` SET `content_loc3`='Woo Ping' WHERE `word_id` = 79677; -- locales_points_of_interest - icon_name : entry=27
UPDATE `trans_words` SET `content_loc3`='Lucan Cordell' WHERE `word_id` = 73281; -- locales_points_of_interest - icon_name : entry=43
UPDATE `trans_words` SET `content_loc3`='Shaina Fuller' WHERE `word_id` = 74079; -- locales_points_of_interest - icon_name : entry=45
UPDATE `trans_words` SET `content_loc3`='Arnold Leland' WHERE `word_id` = 76689; -- locales_points_of_interest - icon_name : entry=46
UPDATE `trans_words` SET `content_loc3`='Ironforge Shaman Trainer' WHERE `word_id` = 127251; -- locales_points_of_interest - icon_name : entry=65
UPDATE `trans_words` SET `content_loc3`='Maxan Anvol' WHERE `word_id` = 73179; -- locales_points_of_interest - icon_name : entry=81
UPDATE `trans_words` SET `content_loc3`='Hogral Bakkan' WHERE `word_id` = 73184; -- locales_points_of_interest - icon_name : entry=82
UPDATE `trans_words` SET `content_loc3`='Gremlock Pilsnor' WHERE `word_id` = 73601; -- locales_points_of_interest - icon_name : entry=86
UPDATE `trans_words` SET `content_loc3`='Thamner Pol' WHERE `word_id` = 74077; -- locales_points_of_interest - icon_name : entry=87
UPDATE `trans_words` SET `content_loc3`='Paxton Ganter' WHERE `word_id` = 73602; -- locales_points_of_interest - icon_name : entry=88
UPDATE `trans_words` SET `content_loc3`='Alassin' WHERE `word_id` = 78742; -- locales_points_of_interest - icon_name : entry=95
UPDATE `trans_words` SET `content_loc3`='Seriadne' WHERE `word_id` = 78737; -- locales_points_of_interest - icon_name : entry=112
UPDATE `trans_words` SET `content_loc3`='Kal' WHERE `word_id` = 75285; -- locales_points_of_interest - icon_name : entry=113
UPDATE `trans_words` SET `content_loc3`='Dazalar' WHERE `word_id` = 75284; -- locales_points_of_interest - icon_name : entry=114
UPDATE `trans_words` SET `content_loc3`='Orgrimmar Eastern Zeppelin Tower' WHERE `word_id` = 127252; -- locales_points_of_interest - icon_name : entry=182
UPDATE `trans_words` SET `content_loc3`='Orgrimmar Western Zeppelin Tower' WHERE `word_id` = 127253; -- locales_points_of_interest - icon_name : entry=183
UPDATE `trans_words` SET `content_loc3`='Xon\'cha' WHERE `word_id` = 78714; -- locales_points_of_interest - icon_name : entry=185
UPDATE `trans_words` SET `content_loc3`='Exodar, Auctioneer' WHERE `word_id` = 127254; -- locales_points_of_interest - icon_name : entry=190
UPDATE `trans_words` SET `content_loc3`='Exodar, bank' WHERE `word_id` = 127255; -- locales_points_of_interest - icon_name : entry=191
UPDATE `trans_words` SET `content_loc3`='Exodar, Guild Master' WHERE `word_id` = 127257; -- locales_points_of_interest - icon_name : entry=193
UPDATE `trans_words` SET `content_loc3`='Exodar, Inn' WHERE `word_id` = 127258; -- locales_points_of_interest - icon_name : entry=194
UPDATE `trans_words` SET `content_loc3`='Exodar, Mailbox' WHERE `word_id` = 127259; -- locales_points_of_interest - icon_name : entry=195
UPDATE `trans_words` SET `content_loc3`='Exodar, Stable Master' WHERE `word_id` = 127260; -- locales_points_of_interest - icon_name : entry=196
UPDATE `trans_words` SET `content_loc3`='Exodar, Weapon Master' WHERE `word_id` = 127261; -- locales_points_of_interest - icon_name : entry=197
UPDATE `trans_words` SET `content_loc3`='Exodar, Druid Trainer' WHERE `word_id` = 127262; -- locales_points_of_interest - icon_name : entry=198
UPDATE `trans_words` SET `content_loc3`='Exodar, Hunter Trainers' WHERE `word_id` = 127263; -- locales_points_of_interest - icon_name : entry=199
UPDATE `trans_words` SET `content_loc3`='Exodar, Mage Trainers' WHERE `word_id` = 127264; -- locales_points_of_interest - icon_name : entry=200
UPDATE `trans_words` SET `content_loc3`='Exodar, Paladin Trainers' WHERE `word_id` = 127265; -- locales_points_of_interest - icon_name : entry=201
UPDATE `trans_words` SET `content_loc3`='Exodar, Priest Trainers' WHERE `word_id` = 127266; -- locales_points_of_interest - icon_name : entry=202
UPDATE `trans_words` SET `content_loc3`='Exodar, Shaman Trainer' WHERE `word_id` = 127267; -- locales_points_of_interest - icon_name : entry=203
UPDATE `trans_words` SET `content_loc3`='Exodar, Warrior Trainers' WHERE `word_id` = 127268; -- locales_points_of_interest - icon_name : entry=204
UPDATE `trans_words` SET `content_loc3`='Exodar, Alchemist Trainers' WHERE `word_id` = 127269; -- locales_points_of_interest - icon_name : entry=205
UPDATE `trans_words` SET `content_loc3`='Exodar, Blacksmithing Trainers' WHERE `word_id` = 127270; -- locales_points_of_interest - icon_name : entry=206
UPDATE `trans_words` SET `content_loc3`='Exodar, Enchanters' WHERE `word_id` = 127271; -- locales_points_of_interest - icon_name : entry=207
UPDATE `trans_words` SET `content_loc3`='Exodar, Engineering' WHERE `word_id` = 127272; -- locales_points_of_interest - icon_name : entry=208
UPDATE `trans_words` SET `content_loc3`='Exodar, First Aid Trainer' WHERE `word_id` = 127273; -- locales_points_of_interest - icon_name : entry=209
UPDATE `trans_words` SET `content_loc3`='Exodar, Fishing Trainer' WHERE `word_id` = 127274; -- locales_points_of_interest - icon_name : entry=210
UPDATE `trans_words` SET `content_loc3`='Exodar, Herbalist Trainer' WHERE `word_id` = 127275; -- locales_points_of_interest - icon_name : entry=211
UPDATE `trans_words` SET `content_loc3`='Exodar, Jewelcrafters' WHERE `word_id` = 127276; -- locales_points_of_interest - icon_name : entry=213
UPDATE `trans_words` SET `content_loc3`='Exodar, Leatherworking' WHERE `word_id` = 127277; -- locales_points_of_interest - icon_name : entry=214
UPDATE `trans_words` SET `content_loc3`='Exodar, Mining Trainers' WHERE `word_id` = 127278; -- locales_points_of_interest - icon_name : entry=215
UPDATE `trans_words` SET `content_loc3`='Exodar, Skinning Trainer' WHERE `word_id` = 127279; -- locales_points_of_interest - icon_name : entry=216
UPDATE `trans_words` SET `content_loc3`='Exodar, Tailors' WHERE `word_id` = 127280; -- locales_points_of_interest - icon_name : entry=217
UPDATE `trans_words` SET `content_loc3`='Exodar, Cook' WHERE `word_id` = 127281; -- locales_points_of_interest - icon_name : entry=218
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Innkeeper' WHERE `word_id` = 127282; -- locales_points_of_interest - icon_name : entry=219
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Stable Master' WHERE `word_id` = 127283; -- locales_points_of_interest - icon_name : entry=220
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Hunter Trainer' WHERE `word_id` = 127284; -- locales_points_of_interest - icon_name : entry=221
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Mage Trainer' WHERE `word_id` = 127285; -- locales_points_of_interest - icon_name : entry=222
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Paladin Trainer' WHERE `word_id` = 127286; -- locales_points_of_interest - icon_name : entry=223
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Priest Trainer' WHERE `word_id` = 127287; -- locales_points_of_interest - icon_name : entry=224
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Shaman Trainer' WHERE `word_id` = 127288; -- locales_points_of_interest - icon_name : entry=225
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Warrior Trainer' WHERE `word_id` = 127289; -- locales_points_of_interest - icon_name : entry=226
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Alchemist' WHERE `word_id` = 127290; -- locales_points_of_interest - icon_name : entry=227
UPDATE `trans_words` SET `content_loc3`='Odesyus\' Landing, Blacksmith' WHERE `word_id` = 127291; -- locales_points_of_interest - icon_name : entry=228
UPDATE `trans_words` SET `content_loc3`='Odesyus\' Landing, Cook' WHERE `word_id` = 127292; -- locales_points_of_interest - icon_name : entry=229
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Engineering Trainer' WHERE `word_id` = 127293; -- locales_points_of_interest - icon_name : entry=230
UPDATE `trans_words` SET `content_loc3`='Azure Watch, First Aid Trainer' WHERE `word_id` = 127294; -- locales_points_of_interest - icon_name : entry=231
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Herbalist' WHERE `word_id` = 127296; -- locales_points_of_interest - icon_name : entry=233
UPDATE `trans_words` SET `content_loc3`='Stillpine Hold, Leatherworker' WHERE `word_id` = 127297; -- locales_points_of_interest - icon_name : entry=234
UPDATE `trans_words` SET `content_loc3`='Azure Watch, Mining Trainer' WHERE `word_id` = 127298; -- locales_points_of_interest - icon_name : entry=235
UPDATE `trans_words` SET `content_loc3`='Stillpine Hold, Skinner' WHERE `word_id` = 127299; -- locales_points_of_interest - icon_name : entry=236
UPDATE `trans_words` SET `content_loc3`='Odesyus\' Landing, Tailor' WHERE `word_id` = 127300; -- locales_points_of_interest - icon_name : entry=237
UPDATE `trans_words` SET `content_loc3`='Krunn' WHERE `word_id` = 74864; -- locales_points_of_interest - icon_name : entry=238
UPDATE `trans_words` SET `content_loc3`='Mishiki' WHERE `word_id` = 74875; -- locales_points_of_interest - icon_name : entry=239
UPDATE `trans_words` SET `content_loc3`='Lau\'Tiki' WHERE `word_id` = 77040; -- locales_points_of_interest - icon_name : entry=240
UPDATE `trans_words` SET `content_loc3`='Rawrk' WHERE `word_id` = 77042; -- locales_points_of_interest - icon_name : entry=241
UPDATE `trans_words` SET `content_loc3`='Mukdrak' WHERE `word_id` = 79192; -- locales_points_of_interest - icon_name : entry=242
UPDATE `trans_words` SET `content_loc3`='Dwukk' WHERE `word_id` = 74863; -- locales_points_of_interest - icon_name : entry=243
UPDATE `trans_words` SET `content_loc3`='Miao\'zan' WHERE `word_id` = 74874; -- locales_points_of_interest - icon_name : entry=244
UPDATE `trans_words` SET `content_loc3`='Swart' WHERE `word_id` = 74862; -- locales_points_of_interest - icon_name : entry=247
UPDATE `trans_words` SET `content_loc3`='Kaplak' WHERE `word_id` = 74859; -- locales_points_of_interest - icon_name : entry=248
UPDATE `trans_words` SET `content_loc3`='Tai\'jin' WHERE `word_id` = 75379; -- locales_points_of_interest - icon_name : entry=249
UPDATE `trans_words` SET `content_loc3`='Un\'Thuwa' WHERE `word_id` = 76982; -- locales_points_of_interest - icon_name : entry=250
UPDATE `trans_words` SET `content_loc3`='Thotar' WHERE `word_id` = 74860; -- locales_points_of_interest - icon_name : entry=251
UPDATE `trans_words` SET `content_loc3`='Shoja\'my' WHERE `word_id` = 78713; -- locales_points_of_interest - icon_name : entry=252
UPDATE `trans_words` SET `content_loc3`='Archibald' WHERE `word_id` = 79680; -- locales_points_of_interest - icon_name : entry=274
UPDATE `trans_words` SET `content_loc3`='Anya Maulray' WHERE `word_id` = 78739; -- locales_points_of_interest - icon_name : entry=275
UPDATE `trans_words` SET `content_loc3`='Undercity Locksmith' WHERE `word_id` = 127301; -- locales_points_of_interest - icon_name : entry=277
UPDATE `trans_words` SET `content_loc3`='Bowen Brisboise' WHERE `word_id` = 75208; -- locales_points_of_interest - icon_name : entry=285
UPDATE `trans_words` SET `content_loc3`='Rand Rhobart' WHERE `word_id` = 77256; -- locales_points_of_interest - icon_name : entry=286
UPDATE `trans_words` SET `content_loc3`='Shelene Rhobart' WHERE `word_id` = 75240; -- locales_points_of_interest - icon_name : entry=287
UPDATE `trans_words` SET `content_loc3`='Faruza' WHERE `word_id` = 73913; -- locales_points_of_interest - icon_name : entry=288
UPDATE `trans_words` SET `content_loc3`='Clyde Kellen' WHERE `word_id` = 76812; -- locales_points_of_interest - icon_name : entry=289
UPDATE `trans_words` SET `content_loc3`='Carolai Anise' WHERE `word_id` = 73931; -- locales_points_of_interest - icon_name : entry=292
UPDATE `trans_words` SET `content_loc3`='Austil de Mon' WHERE `word_id` = 73930; -- locales_points_of_interest - icon_name : entry=293
UPDATE `trans_words` SET `content_loc3`='Rupert Boch' WHERE `word_id` = 73926; -- locales_points_of_interest - icon_name : entry=294
UPDATE `trans_words` SET `content_loc3`='Morganus' WHERE `word_id` = 78741; -- locales_points_of_interest - icon_name : entry=296
UPDATE `trans_words` SET `content_loc3`='Thunder Bluff Zeppelin' WHERE `word_id` = 127302; -- locales_points_of_interest - icon_name : entry=300
UPDATE `trans_words` SET `content_loc3`='Mooranta' WHERE `word_id` = 77537; -- locales_points_of_interest - icon_name : entry=302
UPDATE `trans_words` SET `content_loc3`='Bulrug' WHERE `word_id` = 78740; -- locales_points_of_interest - icon_name : entry=318
UPDATE `trans_words` SET `content_loc3`='Ansekhwa' WHERE `word_id` = 79679; -- locales_points_of_interest - icon_name : entry=319
UPDATE `trans_words` SET `content_loc3`='Seikwa' WHERE `word_id` = 78736; -- locales_points_of_interest - icon_name : entry=337
UPDATE `trans_words` SET `content_loc3`='Shattrath Cantina' WHERE `word_id` = 127303; -- locales_points_of_interest - icon_name : entry=340
UPDATE `trans_words` SET `content_loc3`='Shattrath Taxi' WHERE `word_id` = 127304; -- locales_points_of_interest - icon_name : entry=341
UPDATE `trans_words` SET `content_loc3`='Shattrath Alchemist' WHERE `word_id` = 127305; -- locales_points_of_interest - icon_name : entry=342
UPDATE `trans_words` SET `content_loc3`='Shattrath Armor/Weapon Crafter' WHERE `word_id` = 127306; -- locales_points_of_interest - icon_name : entry=343
UPDATE `trans_words` SET `content_loc3`='Shattrath Cook' WHERE `word_id` = 127307; -- locales_points_of_interest - icon_name : entry=344
UPDATE `trans_words` SET `content_loc3`='Shattrath Enchanters' WHERE `word_id` = 127308; -- locales_points_of_interest - icon_name : entry=345
UPDATE `trans_words` SET `content_loc3`='Shattrath First Aid' WHERE `word_id` = 127309; -- locales_points_of_interest - icon_name : entry=346
UPDATE `trans_words` SET `content_loc3`='Shattrath Jewelcrafter' WHERE `word_id` = 127310; -- locales_points_of_interest - icon_name : entry=347
UPDATE `trans_words` SET `content_loc3`='Shattrath Leatherworker' WHERE `word_id` = 127311; -- locales_points_of_interest - icon_name : entry=348
UPDATE `trans_words` SET `content_loc3`='Shattrath Skinner' WHERE `word_id` = 127312; -- locales_points_of_interest - icon_name : entry=349
UPDATE `trans_words` SET `content_loc3`='Shattrath Mana Loom' WHERE `word_id` = 127313; -- locales_points_of_interest - icon_name : entry=350
UPDATE `trans_words` SET `content_loc3`='Shattrath Alchemy Lab' WHERE `word_id` = 127314; -- locales_points_of_interest - icon_name : entry=351
UPDATE `trans_words` SET `content_loc3`='Shattrath Bank Aldor' WHERE `word_id` = 127315; -- locales_points_of_interest - icon_name : entry=352
UPDATE `trans_words` SET `content_loc3`='Shattrath Bank Scryer' WHERE `word_id` = 127316; -- locales_points_of_interest - icon_name : entry=353
UPDATE `trans_words` SET `content_loc3`='Shattrath Inn Aldor' WHERE `word_id` = 127317; -- locales_points_of_interest - icon_name : entry=354
UPDATE `trans_words` SET `content_loc3`='Shattrath Inn Scryer' WHERE `word_id` = 127318; -- locales_points_of_interest - icon_name : entry=355
UPDATE `trans_words` SET `content_loc3`='Shattrath Stable Aldor' WHERE `word_id` = 127319; -- locales_points_of_interest - icon_name : entry=356
UPDATE `trans_words` SET `content_loc3`='Shattrath Stable Scryer' WHERE `word_id` = 127320; -- locales_points_of_interest - icon_name : entry=357
UPDATE `trans_words` SET `content_loc3`='Shattrath Battlemasters Alliance' WHERE `word_id` = 127321; -- locales_points_of_interest - icon_name : entry=358
UPDATE `trans_words` SET `content_loc3`='Shattrath Battlemasters Horde' WHERE `word_id` = 127322; -- locales_points_of_interest - icon_name : entry=359
UPDATE `trans_words` SET `content_loc3`='Shattrath Arena Battlemasters' WHERE `word_id` = 127323; -- locales_points_of_interest - icon_name : entry=360
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Auction House' WHERE `word_id` = 127326; -- locales_points_of_interest - icon_name : entry=367
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Auction House' WHERE `word_id` = 127326; -- locales_points_of_interest - icon_name : entry=368
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Bank' WHERE `word_id` = 127327; -- locales_points_of_interest - icon_name : entry=369
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Bank' WHERE `word_id` = 127327; -- locales_points_of_interest - icon_name : entry=370
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Flight Master' WHERE `word_id` = 127328; -- locales_points_of_interest - icon_name : entry=371
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Guild House' WHERE `word_id` = 127329; -- locales_points_of_interest - icon_name : entry=372
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Inn' WHERE `word_id` = 127330; -- locales_points_of_interest - icon_name : entry=373
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Inn' WHERE `word_id` = 127330; -- locales_points_of_interest - icon_name : entry=374
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Mailbox' WHERE `word_id` = 127331; -- locales_points_of_interest - icon_name : entry=375
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Weapon Master' WHERE `word_id` = 127333; -- locales_points_of_interest - icon_name : entry=377
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Battlemasters' WHERE `word_id` = 127334; -- locales_points_of_interest - icon_name : entry=378
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Druid Trainer' WHERE `word_id` = 127335; -- locales_points_of_interest - icon_name : entry=379
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Hunter Trainer' WHERE `word_id` = 127336; -- locales_points_of_interest - icon_name : entry=380
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Mage Trainer' WHERE `word_id` = 127337; -- locales_points_of_interest - icon_name : entry=381
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Paladin Trainer' WHERE `word_id` = 127338; -- locales_points_of_interest - icon_name : entry=382
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Priest Trainer' WHERE `word_id` = 127339; -- locales_points_of_interest - icon_name : entry=383
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Rogue Trainer' WHERE `word_id` = 127340; -- locales_points_of_interest - icon_name : entry=384
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Warlock Trainers' WHERE `word_id` = 127341; -- locales_points_of_interest - icon_name : entry=385
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Alchemy' WHERE `word_id` = 127342; -- locales_points_of_interest - icon_name : entry=386
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Blacksmithing' WHERE `word_id` = 127343; -- locales_points_of_interest - icon_name : entry=387
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Cooking' WHERE `word_id` = 127344; -- locales_points_of_interest - icon_name : entry=388
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Enchanting' WHERE `word_id` = 127345; -- locales_points_of_interest - icon_name : entry=389
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Engineering' WHERE `word_id` = 127346; -- locales_points_of_interest - icon_name : entry=390
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, First Aid' WHERE `word_id` = 127347; -- locales_points_of_interest - icon_name : entry=391
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Fishing' WHERE `word_id` = 127348; -- locales_points_of_interest - icon_name : entry=392
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Herbalism' WHERE `word_id` = 127349; -- locales_points_of_interest - icon_name : entry=393
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Jewelcrafting' WHERE `word_id` = 127350; -- locales_points_of_interest - icon_name : entry=395
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Leatherworking' WHERE `word_id` = 127351; -- locales_points_of_interest - icon_name : entry=396
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Mining' WHERE `word_id` = 127352; -- locales_points_of_interest - icon_name : entry=397
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Skinning' WHERE `word_id` = 127353; -- locales_points_of_interest - icon_name : entry=398
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Tailoring' WHERE `word_id` = 127354; -- locales_points_of_interest - icon_name : entry=399
UPDATE `trans_words` SET `content_loc3`='Silvermoon City, Mana Loom' WHERE `word_id` = 127355; -- locales_points_of_interest - icon_name : entry=400
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Innkeeper' WHERE `word_id` = 127356; -- locales_points_of_interest - icon_name : entry=401
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Stable Master' WHERE `word_id` = 127357; -- locales_points_of_interest - icon_name : entry=402
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Hunter Trainer' WHERE `word_id` = 127358; -- locales_points_of_interest - icon_name : entry=403
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Mage Trainer' WHERE `word_id` = 127359; -- locales_points_of_interest - icon_name : entry=404
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Priest Trainer' WHERE `word_id` = 127361; -- locales_points_of_interest - icon_name : entry=406
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Rogue Trainer' WHERE `word_id` = 127362; -- locales_points_of_interest - icon_name : entry=407
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Warlock Trainer' WHERE `word_id` = 127363; -- locales_points_of_interest - icon_name : entry=408
UPDATE `trans_words` SET `content_loc3`='Saltheril\'s Haven, Alchemist' WHERE `word_id` = 127364; -- locales_points_of_interest - icon_name : entry=409
UPDATE `trans_words` SET `content_loc3`='Farstrider Retreat, Blacksmith' WHERE `word_id` = 127365; -- locales_points_of_interest - icon_name : entry=410
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Cook' WHERE `word_id` = 127366; -- locales_points_of_interest - icon_name : entry=411
UPDATE `trans_words` SET `content_loc3`='Saltheril\'s Haven, Enchanter' WHERE `word_id` = 127367; -- locales_points_of_interest - icon_name : entry=412
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, First Aid Trainer' WHERE `word_id` = 127368; -- locales_points_of_interest - icon_name : entry=413
UPDATE `trans_words` SET `content_loc3`='Saltheril\'s Haven, Herbalist' WHERE `word_id` = 127369; -- locales_points_of_interest - icon_name : entry=414
UPDATE `trans_words` SET `content_loc3`='Falconwing Square, Jewelcrafter' WHERE `word_id` = 127370; -- locales_points_of_interest - icon_name : entry=415
UPDATE `trans_words` SET `content_loc3`='Darnassus Mage Trainer' WHERE `word_id` = 127373; -- locales_points_of_interest - icon_name : entry=438
UPDATE `trans_words` SET `content_loc3`='Darnassus Paladin Trainer' WHERE `word_id` = 127374; -- locales_points_of_interest - icon_name : entry=439
UPDATE `trans_words` SET `content_loc3`='Exodar, Battlemasters' WHERE `word_id` = 127375; -- locales_points_of_interest - icon_name : entry=441
UPDATE `trans_words` SET `content_loc3`='Arena Battlemaster Exodar' WHERE `word_id` = 127376; -- locales_points_of_interest - icon_name : entry=442

SET NAMES 'latin1';
