-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc7='¡Éxito!' WHERE entry=2000000637; /* content: Success! */

SET NAMES 'latin1';
