-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_creature SET name_loc8='[UNUSED] JEFF CHOW TEST',subname_loc8='No Clothes NPC' WHERE entry=4045; /* name: [UNUSED] JEFF CHOW TEST */ .* subname: No Clothes NPC */
UPDATE locales_creature SET name_loc8='World Demon Trainer',subname_loc8='Demon Trainer' WHERE entry=5006; /* name: World Demon Trainer */ .* subname: Demon Trainer */
UPDATE locales_creature SET name_loc8='World Guild Tabbard Vendor',subname_loc8='Guild Tabard Vendor' WHERE entry=5061; /* name: World Guild Tabbard Vendor */ .* subname: Guild Tabard Vendor */
UPDATE locales_creature SET name_loc8='Innkeeper Sentinel Hill',subname_loc8='Innkeeper' WHERE entry=8999; /* name: Innkeeper Sentinel Hill */ .* subname: Innkeeper */
UPDATE locales_creature SET name_loc8='Wynne Larsone',subname_loc8='Robe Merchant' WHERE entry=11111; /* name: Wynne Larsone */ .* subname: Robe Merchant */
UPDATE locales_creature SET subname_loc8='The Head of The Black Flight' WHERE entry=11583; /* subname: The Head of The Black Flight */
UPDATE locales_creature SET subname_loc8='DO NOT DELETE' WHERE entry=12999; /* subname: DO NOT DELETE */
UPDATE locales_creature SET subname_loc8='Aldor: Quartermaster' WHERE entry=19321; /* subname: Aldor: Quartermaster */
UPDATE locales_creature SET name_loc8='Barnu Cragcrush',subname_loc8='Stable Master' WHERE entry=19325; /* name: Barnu Cragcrush */ .* subname: Stable Master */
UPDATE locales_creature SET subname_loc8='Scryers: Quartermaster' WHERE entry=19331; /* subname: Scryers: Quartermaster */
UPDATE locales_creature SET name_loc8='Hurlog Horde',subname_loc8='Warsong Gulch Battlemaster' WHERE entry=20002; /* name: Hurlog Horde */ .* subname: Warsong Gulch Battlemaster */
UPDATE locales_creature SET subname_loc8='Silverwing Supply Officer (Neutral)' WHERE entry=20010; /* subname: Silverwing Supply Officer (Neutral) */
UPDATE locales_creature SET subname_loc8='Silverwing Supply Officer (Friendly)' WHERE entry=20011; /* subname: Silverwing Supply Officer (Friendly) */
UPDATE locales_creature SET subname_loc8='Silverwing Supply Officer (Honored)' WHERE entry=20012; /* subname: Silverwing Supply Officer (Honored) */
UPDATE locales_creature SET subname_loc8='Silverwing Supply Officer (Revered)' WHERE entry=20013; /* subname: Silverwing Supply Officer (Revered) */
UPDATE locales_creature SET subname_loc8='Silverwing Supply Officer (Exalted)' WHERE entry=20014; /* subname: Silverwing Supply Officer (Exalted) */
UPDATE locales_creature SET subname_loc8='Warsong Supply Officer (Honored)' WHERE entry=20022; /* subname: Warsong Supply Officer (Honored) */
UPDATE locales_creature SET subname_loc8='Windrider Keeper' WHERE entry=20494; /* subname: Windrider Keeper */
UPDATE locales_creature SET name_loc8='Inscriber Saalyn',subname_loc8='Aldor Inscriptions' WHERE entry=20807; /* name: Inscriber Saalyn */ .* subname: Aldor Inscriptions */
UPDATE locales_creature SET name_loc8='Inscriber Veredis',subname_loc8='Scryer Inscriptions' WHERE entry=20808; /* name: Inscriber Veredis */ .* subname: Scryer Inscriptions */
UPDATE locales_creature SET subname_loc8='Ticket Redeemer' WHERE entry=24495; /* subname: Ticket Redeemer */

SET NAMES 'latin1';
