-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc8='Cipher of Damnation belongs to us now!' WHERE entry=-23; -- content: Cipher of Damnation belongs to us now!
UPDATE creature_ai_texts SET content_loc8='The master will know of this incursion. You will be hunted for all eternity!' WHERE entry=-24; -- content: The master will know of this incursion. You will be hunted for all eternity!
UPDATE creature_ai_texts SET content_loc8='%s is splashed by the blood and becomes irradiated!' WHERE entry=-31; -- content: %s is splashed by the blood and becomes irradiated!
UPDATE creature_ai_texts SET content_loc8='So dark...' WHERE entry=-73; -- content: So dark...
UPDATE creature_ai_texts SET content_loc8='Aaaaahhh! So close to escaping.' WHERE entry=-74; -- content: Aaaaahhh! So close to escaping.
UPDATE creature_ai_texts SET content_loc8='%s skitters out from the shadows...' WHERE entry=-75; -- content: %s skitters out from the shadows...
UPDATE creature_ai_texts SET content_loc8='Get it while it\'s hot!' WHERE entry=-142; -- content: Get it while it\'s hot!
UPDATE creature_ai_texts SET content_loc8='You hear a faint unlocking sound...' WHERE entry=-146; -- content: You hear a faint unlocking sound...
UPDATE creature_ai_texts SET content_loc8='The Brotherhood shall prevail!' WHERE entry=-173; -- content: The Brotherhood shall prevail!
UPDATE creature_ai_texts SET content_loc8='Aaaahhhhhh!' WHERE entry=-212; -- content: Aaaahhhhhh!
UPDATE creature_ai_texts SET content_loc8='Wit a reward like dis, how could they refuse, mon?' WHERE entry=-317; -- content: Wit a reward like dis, how could they refuse, mon?
UPDATE creature_ai_texts SET content_loc8='Sands consume you!' WHERE entry=-320; -- content: Sands consume you!
UPDATE creature_ai_texts SET content_loc8='%s calls for reinforcements!' WHERE entry=-343; -- content: %s calls for reinforcements!
UPDATE creature_ai_texts SET content_loc8='%s\'s death cry has stirred the nearby silithid hive.' WHERE entry=-344; -- content: %s\'s death cry has stirred the nearby silithid hive.
UPDATE creature_ai_texts SET content_loc8='Think I\'m starting to wear a rut in the paving stones.' WHERE entry=-423; -- content: Think I\'m starting to wear a rut in the paving stones.
UPDATE creature_ai_texts SET content_loc8='Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here.' WHERE entry=-424; -- content: Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here.
UPDATE creature_ai_texts SET content_loc8='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE entry=-425; -- content: Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.
UPDATE creature_ai_texts SET content_loc8='Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.' WHERE entry=-426; -- content: Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.
UPDATE creature_ai_texts SET content_loc8='As if I don\'t have better things to do in my old age than carry buckets of water.' WHERE entry=-427; -- content: As if I don\'t have better things to do in my old age than carry buckets of water.
UPDATE creature_ai_texts SET content_loc8='O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.' WHERE entry=-428; -- content: O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.
UPDATE creature_ai_texts SET content_loc8='Ah, damn it all! Clever trap. Too bad you\'ll never live to tell the tale...' WHERE entry=-640; -- content: Ah, damn it all! Clever trap. Too bad you\'ll never live to tell the tale...
UPDATE creature_ai_texts SET content_loc8='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE entry=-641; -- content: At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.
UPDATE creature_ai_texts SET content_loc8='Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared.' WHERE entry=-642; -- content: Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared.
UPDATE creature_ai_texts SET content_loc8='%s lets out a deep roar, alerting nearby allies and becoming enraged!' WHERE entry=-648; -- content: %s lets out a deep roar, alerting nearby allies and becoming enraged!
UPDATE creature_ai_texts SET content_loc8='%s goes into a drunken rage!' WHERE entry=-649; -- content: %s goes into a drunken rage!
UPDATE creature_ai_texts SET content_loc8='You have chosen death.' WHERE entry=-661; -- content: You have chosen death.
UPDATE creature_ai_texts SET content_loc8='%s growls in your direction before taking time to sniff you.' WHERE entry=-662; -- content: %s growls in your direction before taking time to sniff you.
UPDATE creature_ai_texts SET content_loc8='%s faces southeast and whimpers before looking back at you. ' WHERE entry=-663; -- content: %s faces southeast and whimpers before looking back at you.
UPDATE creature_ai_texts SET content_loc8='%s chips and splinters!' WHERE entry=-694; -- content: %s chips and splinters!
UPDATE creature_ai_texts SET content_loc8='ATTACK WITH THE FULL FORCE OF NETHERWING, MY CHILDREN! ATTACK!' WHERE entry=-698; -- content: ATTACK WITH THE FULL FORCE OF NETHERWING, MY CHILDREN! ATTACK!
UPDATE creature_ai_texts SET content_loc8='Lord Illidan, bless me with the power of the flight!' WHERE entry=-699; -- content: Lord Illidan, bless me with the power of the flight!
UPDATE creature_ai_texts SET content_loc8='I have... failed.' WHERE entry=-700; -- content: I have... failed.
UPDATE creature_ai_texts SET content_loc8='My strength.... is... returning!' WHERE entry=-742; -- content: My strength.... is... returning!
UPDATE creature_ai_texts SET content_loc8='You\'ve restored my health! I\'m in your debt, $N.' WHERE entry=-743; -- content: You\'ve restored my health! I\'m in your debt, $N.
UPDATE creature_ai_texts SET content_loc8='You\'ve found a cure! We will crush our enemies!' WHERE entry=-744; -- content: You\'ve found a cure! We will crush our enemies!
UPDATE creature_ai_texts SET content_loc8='The %s flies up through the trees, free of Terokk\'s corruption.' WHERE entry=-747; -- content: The %s flies up through the trees, free of Terokk\'s corruption.
UPDATE creature_ai_texts SET content_loc8='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!' WHERE entry=-748; -- content: SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!
UPDATE creature_ai_texts SET content_loc8='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!' WHERE entry=-749; -- content: SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!
UPDATE creature_ai_texts SET content_loc8='DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!' WHERE entry=-750; -- content: DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!
UPDATE creature_ai_texts SET content_loc8='COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...' WHERE entry=-751; -- content: COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...
UPDATE creature_ai_texts SET content_loc8='I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!' WHERE entry=-752; -- content: I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!
UPDATE creature_ai_texts SET content_loc8='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?' WHERE entry=-753; -- content: HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?
UPDATE creature_ai_texts SET content_loc8='YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT!' WHERE entry=-754; -- content: YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT!
UPDATE creature_ai_texts SET content_loc8='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?' WHERE entry=-755; -- content: I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?
UPDATE creature_ai_texts SET content_loc8='%s puts his club away and begins swinging wildly!' WHERE entry=-797; -- content: %s puts his club away and begins swinging wildly!
UPDATE creature_ai_texts SET content_loc8='%s begins to retaliate all attacks against him!' WHERE entry=-807; -- content: %s begins to retaliate all attacks against him!
UPDATE creature_ai_texts SET content_loc8='Never underestimate the other ethereal\'s greed.' WHERE entry=-816; -- content: Never underestimate the other ethereal\'s greed.
UPDATE creature_ai_texts SET content_loc8='This evil cannot be allowed to enter this world!  Come my children!' WHERE entry=-825; -- content: This evil cannot be allowed to enter this world!  Come my children!
UPDATE creature_ai_texts SET content_loc8='%s attacks Karang\'s Banner!' WHERE entry=-828; -- content: %s attacks Karang\'s Banner!
UPDATE creature_ai_texts SET content_loc8='%s charges!' WHERE entry=-829; -- content: %s charges!
UPDATE creature_ai_texts SET content_loc8='%s shimmers and becomes intangible.' WHERE entry=-830; -- content: %s shimmers and becomes intangible.
UPDATE creature_ai_texts SET content_loc8='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE entry=-831; -- content: Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!
UPDATE creature_ai_texts SET content_loc8='It should have been me!' WHERE entry=-912; -- content: It should have been me!
UPDATE creature_ai_texts SET content_loc8='I\'ll never forget you, my love.' WHERE entry=-914; -- content: I\'ll never forget you, my love.
UPDATE creature_ai_texts SET content_loc8='We should never have come along.' WHERE entry=-916; -- content: We should never have come along.
UPDATE creature_ai_texts SET content_loc8='More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!' WHERE entry=-924; -- content: More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!
UPDATE creature_ai_texts SET content_loc8='This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.' WHERE entry=-925; -- content: This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.
UPDATE creature_ai_texts SET content_loc8='I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.' WHERE entry=-926; -- content: I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.
UPDATE creature_ai_texts SET content_loc8='Intruders! Attack the intruders!' WHERE entry=-927; -- content: Intruders! Attack the intruders!
UPDATE creature_ai_texts SET content_loc8='Southshore shall pay in blood!' WHERE entry=-928; -- content: Southshore shall pay in blood!
UPDATE creature_ai_texts SET content_loc8='I have risen!' WHERE entry=-929; -- content: I have risen!
UPDATE creature_ai_texts SET content_loc8='Revenge shall be mine at last!' WHERE entry=-930; -- content: Revenge shall be mine at last!
UPDATE creature_ai_texts SET content_loc8='The undead shall feast on your soul, $N.' WHERE entry=-931; -- content: The undead shall feast on your soul, $N.
UPDATE creature_ai_texts SET content_loc8='Help me! Help! Assassins in the hills! To arms! To arms!' WHERE entry=-932; -- content: Help me! Help! Assassins in the hills! To arms! To arms!
UPDATE creature_ai_texts SET content_loc8='Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!' WHERE entry=-933; -- content: Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!
UPDATE creature_ai_texts SET content_loc8='%s grabs the back of his neck and his eyes go wide.' WHERE entry=-934; -- content: %s grabs the back of his neck and his eyes go wide.
UPDATE creature_ai_texts SET content_loc8='Assassins... save... th... Magistraaa...' WHERE entry=-935; -- content: Assassins... save... th... Magistraaa...
UPDATE creature_ai_texts SET content_loc8='Off with you, $N.' WHERE entry=-936; -- content: Off with you, $N.
UPDATE creature_ai_texts SET content_loc8='Move along, $c.' WHERE entry=-937; -- content: Move along, $c.
UPDATE creature_ai_texts SET content_loc8='Do not push it citizen!' WHERE entry=-938; -- content: Do not push it citizen!
UPDATE creature_ai_texts SET content_loc8='I love the smell of nether in the morning.' WHERE entry=-960; -- content: I love the smell of nether in the morning.
UPDATE creature_ai_texts SET content_loc8='It smells like...' WHERE entry=-961; -- content: It smells like...
UPDATE creature_ai_texts SET content_loc8='...victory.' WHERE entry=-962; -- content: ...victory.
UPDATE creature_ai_texts SET content_loc8='Looks like today was the wrong day to quit mana tapping...' WHERE entry=-963; -- content: Looks like today was the wrong day to quit mana tapping...
UPDATE creature_ai_texts SET content_loc8='Core overload detected. System malfunction detected...' WHERE entry=-966; -- content: Core overload detected. System malfunction detected...
UPDATE creature_ai_texts SET content_loc8='Beat or be beaten! This is the way of the Legion!' WHERE entry=-967; -- content: Beat or be beaten! This is the way of the Legion!
UPDATE creature_ai_texts SET content_loc8='Burn their bodies, shred their skins, crush their creaking carapaces!' WHERE entry=-968; -- content: Burn their bodies, shred their skins, crush their creaking carapaces!
UPDATE creature_ai_texts SET content_loc8='Crush these stinking husks!' WHERE entry=-969; -- content: Crush these stinking husks!
UPDATE creature_ai_texts SET content_loc8='Smash them! Grind the bones into the dirt!' WHERE entry=-970; -- content: Smash them! Grind the bones into the dirt!
UPDATE creature_ai_texts SET content_loc8='Harder, maggots! We must keep the sunwell clear for the master\'s return!' WHERE entry=-971; -- content: Harder, maggots! We must keep the sunwell clear for the master\'s return!
UPDATE creature_ai_texts SET content_loc8='Grraaarrr! You think to make an icicle out of me? Come down, then I will add real fire to your life.' WHERE entry=-973; -- content: Grraaarrr! You think to make an icicle out of me? Come down, then I will add real fire to your life.
UPDATE creature_ai_texts SET content_loc8='Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!' WHERE entry=-974; -- content: Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!
UPDATE creature_ai_texts SET content_loc8='Must you follow me everywhere? <sigh>' WHERE entry=-975; -- content: Must you follow me everywhere? <sigh>
UPDATE creature_ai_texts SET content_loc8='Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares!' WHERE entry=-976; -- content: Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares!
UPDATE creature_ai_texts SET content_loc8='Are you hungry? I\'m hungry. I just can\'t stand the thought of cured ham steak from Thultash again. If only we could get some of that succulent roasted quail!' WHERE entry=-977; -- content: Are you hungry? I\'m hungry. I just can\'t stand the thought of cured ham steak from Thultash again. If only we could get some of that succulent roasted quail!
UPDATE creature_ai_texts SET content_loc8='Hahaha! That fool will never find out what I\'m up to! Or, if he does, it\'ll be too late for the draenei!' WHERE entry=-978; -- content: Hahaha! That fool will never find out what I\'m up to! Or, if he does, it\'ll be too late for the draenei!
UPDATE creature_ai_texts SET content_loc8='Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones!' WHERE entry=-979; -- content: Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones!
UPDATE creature_ai_texts SET content_loc8='I cannot wait to see the results of this latest batch!' WHERE entry=-980; -- content: I cannot wait to see the results of this latest batch!
UPDATE creature_ai_texts SET content_loc8='Are They all.... Dead?' WHERE entry=-981; -- content: Are They all.... Dead?
UPDATE creature_ai_texts SET content_loc8='Is someone there? Tirion my old friend, is that you? Have you come to save us?' WHERE entry=-982; -- content: Is someone there? Tirion my old friend, is that you? Have you come to save us?
UPDATE creature_ai_texts SET content_loc8='You dare! Now feel my wrath!' WHERE entry=-983; -- content: You dare! Now feel my wrath!
UPDATE creature_ai_texts SET content_loc8='Who dares?! I will destroy you!' WHERE entry=-984; -- content: Who dares?! I will destroy you!
UPDATE creature_ai_texts SET content_loc8='Mistress!! They seek to destroy your work!' WHERE entry=-985; -- content: Mistress!! They seek to destroy your work!
UPDATE creature_ai_texts SET content_loc8='Drohn\'s brew is the stuff legends are made of! Come taste the legend!' WHERE entry=-997; -- content: Drohn\'s brew is the stuff legends are made of! Come taste the legend!
UPDATE creature_ai_texts SET content_loc8='We drink for the Horde! Do you drink for the Horde? Come show us at Drohn\'s Distillery!' WHERE entry=-998; -- content: We drink for the Horde! Do you drink for the Horde? Come show us at Drohn\'s Distillery!
UPDATE creature_ai_texts SET content_loc8='Hey you, the tall one... Want to put some hair on your chest? Drohn\'s Distillery can help you out!' WHERE entry=-999; -- content: Hey you, the tall one... Want to put some hair on your chest? Drohn\'s Distillery can help you out!
UPDATE creature_ai_texts SET content_loc8='Drohn\'s Distillery has the best brew money can buy! They were voted "Outstanding Brew" by Monthly Goblin Brew!' WHERE entry=-1000; -- content: Drohn\'s Distillery has the best brew money can buy! They were voted "Outstanding Brew" by Monthly Goblin Brew!
UPDATE creature_ai_texts SET content_loc8='If you wanna live life to the fullest, you gotta try T\'chali\'s Voodoo Brew!' WHERE entry=-1001; -- content: If you wanna live life to the fullest, you gotta try T\'chali\'s Voodoo Brew!
UPDATE creature_ai_texts SET content_loc8='T\'chali\'s Voodoo Brews helps keep the party going! Check out the party at Brewfest!' WHERE entry=-1002; -- content: T\'chali\'s Voodoo Brews helps keep the party going! Check out the party at Brewfest!
UPDATE creature_ai_texts SET content_loc8='Hey you! T\'chali\'s Voodoo Brewers have got a brew that won\'t kill you! But they\'ve also got a brew that might...' WHERE entry=-1003; -- content: Hey you! T\'chali\'s Voodoo Brewers have got a brew that won\'t kill you! But they\'ve also got a brew that might...
UPDATE creature_ai_texts SET content_loc8='T\'chali\'s Voodoo Brewery has the best brew you can find! They were voted "Best Brew" by the Goblin Brew Weekly!' WHERE entry=-1004; -- content: T\'chali\'s Voodoo Brewery has the best brew you can find! They were voted "Best Brew" by the Goblin Brew Weekly!
UPDATE creature_ai_texts SET content_loc8='Whoah! Walk by again girl!' WHERE entry=-1005; -- content: Whoah! Walk by again girl!
UPDATE creature_ai_texts SET content_loc8='Hey! Sweet cheeks, over here!' WHERE entry=-1006; -- content: Hey! Sweet cheeks, over here!
UPDATE creature_ai_texts SET content_loc8='Hey, hey sweet thing! Looking good!' WHERE entry=-1007; -- content: Hey, hey sweet thing! Looking good!
UPDATE creature_ai_texts SET content_loc8='Hey, hey! Nice build you got there honey!' WHERE entry=-1008; -- content: Hey, hey! Nice build you got there honey!
UPDATE creature_ai_texts SET content_loc8='Yo! Big lady! You think you\'re big enough to handle me?' WHERE entry=-1009; -- content: Yo! Big lady! You think you\'re big enough to handle me?
UPDATE creature_ai_texts SET content_loc8='Hey tough stuff! Hey, $c! Do you like money? I\'m loaded! How about you come over here and check out my gold coins?' WHERE entry=-1010; -- content: Hey tough stuff! Hey, $c! Do you like money? I\'m loaded! How about you come over here and check out my gold coins?
UPDATE creature_ai_texts SET content_loc8='This will teach you to lay off the herb, $r.' WHERE entry=-1019; -- content: This will teach you to lay off the herb, $r.
UPDATE creature_ai_texts SET content_loc8='The Scarlet Crusade shall not fail in it\'s mission!' WHERE entry=-1030; -- content: The Scarlet Crusade shall not fail in it\'s mission!
UPDATE creature_ai_texts SET content_loc8='These undead atrocities will be destroyed!' WHERE entry=-1031; -- content: These undead atrocities will be destroyed!
UPDATE creature_ai_texts SET content_loc8='These lands shall be cleansed!' WHERE entry=-1032; -- content: These lands shall be cleansed!
UPDATE creature_ai_texts SET content_loc8='The Agamand Mills is held by the Scourge, $c. Join us!' WHERE entry=-1034; -- content: The Agamand Mills is held by the Scourge, $c. Join us!
UPDATE creature_ai_texts SET content_loc8='Tell the Warden this prison is ours now!' WHERE entry=-1041; -- content: Tell the Warden this prison is ours now!
UPDATE creature_ai_texts SET content_loc8='I\'ll crush your skull beneath my boot!' WHERE entry=-1042; -- content: I\'ll crush your skull beneath my boot!
UPDATE creature_ai_texts SET content_loc8='Death to the Warden\'s men!' WHERE entry=-1043; -- content: Death to the Warden\'s men!
UPDATE creature_ai_texts SET content_loc8='Fresh meat!' WHERE entry=-1044; -- content: Fresh meat!
UPDATE creature_ai_texts SET content_loc8='More of the Warden\'s errand boys!' WHERE entry=-1045; -- content: More of the Warden\'s errand boys!
UPDATE creature_ai_texts SET content_loc8='How dare you enter my sanctum!' WHERE entry=-1047; -- content: How dare you enter my sanctum!
UPDATE creature_ai_texts SET content_loc8='You are in the presence of a god!' WHERE entry=-1048; -- content: You are in the presence of a god!
UPDATE creature_ai_texts SET content_loc8='%s seems to no longer be able to cast spells...' WHERE entry=-1058; -- content: %s seems to no longer be able to cast spells...
UPDATE creature_ai_texts SET content_loc8='Hey folks, go easy on me... it\'s my first time.' WHERE entry=-1059; -- content: Hey folks, go easy on me... it\'s my first time.
UPDATE creature_ai_texts SET content_loc8='Come on! These jokes are epic!' WHERE entry=-1076; -- content: Come on! These jokes are epic!
UPDATE creature_ai_texts SET content_loc8='How desperate do you have to be for allies that you recruit your livestock?' WHERE entry=-1083; -- content: How desperate do you have to be for allies that you recruit your livestock?
UPDATE creature_ai_texts SET content_loc8='I own a dog, but I\'m not giving him a sword.' WHERE entry=-1084; -- content: I own a dog, but I\'m not giving him a sword.
UPDATE creature_ai_texts SET content_loc8='Now that the show\'s done, can someone run me through Scarlet Monestary?' WHERE entry=-1087; -- content: Now that the show\'s done, can someone run me through Scarlet Monestary?
UPDATE creature_ai_texts SET content_loc8='Is it just me, or is the Horde about the ugliest enemy we could find?' WHERE entry=-1109; -- content: Is it just me, or is the Horde about the ugliest enemy we could find?
UPDATE creature_ai_texts SET content_loc8='Look who\'s here, it\'s Raliq the drunk... His momma\'s so fat dragon\'s won\'t eat her...' WHERE entry=-1116; -- content: Look who\'s here, it\'s Raliq the drunk... His momma\'s so fat dragon\'s won\'t eat her...
UPDATE creature_ai_texts SET content_loc8='They dont\'t know where to store the leftovers!' WHERE entry=-1117; -- content: They dont\'t know where to store the leftovers!
UPDATE creature_ai_texts SET content_loc8='Wow! The laughs dont\'t drop very often here, do they?' WHERE entry=-1118; -- content: Wow! The laughs dont\'t drop very often here, do they?
UPDATE creature_ai_texts SET content_loc8='Kill $N!' WHERE entry=-1119; -- content: Kill $N!
UPDATE creature_ai_texts SET content_loc8='Come, $n. See what the Nightmare brings...' WHERE entry=-1139; -- content: Come, $n. See what the Nightmare brings...
UPDATE creature_ai_texts SET content_loc8='The Nightmare cannot be stopped!' WHERE entry=-1140; -- content: The Nightmare cannot be stopped!
UPDATE creature_ai_texts SET content_loc8='%s squeezes the last bit of life out of $n and swallows their soul.' WHERE entry=-1141; -- content: %s squeezes the last bit of life out of $n and swallows their soul.
UPDATE creature_ai_texts SET content_loc8='I\'ll rip the secrets from your flesh!' WHERE entry=-1200; -- content: I\'ll rip the secrets from your flesh!
UPDATE creature_ai_texts SET content_loc8='Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!' WHERE entry=-1206; -- content: Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!
UPDATE creature_ai_texts SET content_loc8='Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!' WHERE entry=-1207; -- content: Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!
UPDATE creature_ai_texts SET content_loc8='Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!' WHERE entry=-1208; -- content: Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!
UPDATE creature_ai_texts SET content_loc8='Where? Where are the Shards! You cannot hide them from us!' WHERE entry=-1209; -- content: Where? Where are the Shards! You cannot hide them from us!
UPDATE creature_ai_texts SET content_loc8='Your world will die, mortals! Your doom is now at hand!' WHERE entry=-1210; -- content: Your world will die, mortals! Your doom is now at hand!
UPDATE creature_ai_texts SET content_loc8='Your own strength feeds me!' WHERE entry=-1211; -- content: Your own strength feeds me!
UPDATE creature_ai_texts SET content_loc8='Ha! This place is not yet worthy of my infliction.' WHERE entry=-1212; -- content: Ha! This place is not yet worthy of my infliction.
UPDATE creature_ai_texts SET content_loc8='%s raises his hammer menacingly...' WHERE entry=-1219; -- content: %s raises his hammer menacingly...
UPDATE creature_ai_texts SET content_loc8='Skywing! I will free you from your curse over my dead body!' WHERE entry=-1220; -- content: Skywing! I will free you from your curse over my dead body!
UPDATE creature_ai_texts SET content_loc8='Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides!' WHERE entry=-1226; -- content: Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides!
UPDATE creature_ai_texts SET content_loc8='Cabal Summoner summons a Cabal Deathsworn to his aid!' WHERE entry=-1247; -- content: Cabal Summoner summons a Cabal Deathsworn to his aid!
UPDATE creature_ai_texts SET content_loc8='Cabal Summoner summons a Cabal Acolyte to his aid!' WHERE entry=-1248; -- content: Cabal Summoner summons a Cabal Acolyte to his aid!
UPDATE creature_ai_texts SET content_loc8='I\'m not feeling so well...' WHERE entry=-1287; -- content: I\'m not feeling so well...
UPDATE creature_ai_texts SET content_loc8='Foolish mortal, you serve me now!' WHERE entry=-1295; -- content: Foolish mortal, you serve me now!
UPDATE creature_ai_texts SET content_loc8='The power of the light is truly great and merciful.' WHERE entry=-1296; -- content: The power of the light is truly great and merciful.
UPDATE creature_ai_texts SET content_loc8='We shall be reunited once more, my love...' WHERE entry=-1297; -- content: We shall be reunited once more, my love...
UPDATE creature_ai_texts SET content_loc8='At last, it ends...' WHERE entry=-1298; -- content: At last, it ends...
UPDATE creature_ai_texts SET content_loc8='Stranger, find the fallen Prince Menethil and end his reign of terror.' WHERE entry=-1299; -- content: Stranger, find the fallen Prince Menethil and end his reign of terror.
UPDATE creature_ai_texts SET content_loc8='Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas...' WHERE entry=-1300; -- content: Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas...
UPDATE creature_ai_texts SET content_loc8='I won\'t make it... go... go on without me...' WHERE entry=-1301; -- content: I won\'t make it... go... go on without me...
UPDATE creature_ai_texts SET content_loc8='Death take me! I cannot go on! I have nothing left...' WHERE entry=-1302; -- content: Death take me! I cannot go on! I have nothing left...
UPDATE creature_ai_texts SET content_loc8='Will someone please give my little kitten a good home?' WHERE entry=-1315; -- content: Will someone please give my little kitten a good home?
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper lays an egg!' WHERE entry=-1317; -- content: Silithid Creeper lays an egg!
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg begins to crack and open...' WHERE entry=-1318; -- content: Silithid Creeper Egg begins to crack and open...
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg splits open!' WHERE entry=-1319; -- content: Silithid Creeper Egg splits open!
UPDATE creature_ai_texts SET content_loc8='Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!' WHERE entry=-1320; -- content: Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!
UPDATE creature_ai_texts SET content_loc8='What ... have you done...' WHERE entry=-1321; -- content: What ... have you done...
UPDATE creature_ai_texts SET content_loc8='Pray that the chilling embrace of Teron Gorefiend does not reach out for you...' WHERE entry=-1322; -- content: Pray that the chilling embrace of Teron Gorefiend does not reach out for you...
UPDATE creature_ai_texts SET content_loc8='It is you who have invaded our home. Gorefiend will avenge us!' WHERE entry=-1323; -- content: It is you who have invaded our home. Gorefiend will avenge us!
UPDATE creature_ai_texts SET content_loc8='We will never dissipate, mortal... Our fate is tied to Gorefiend...' WHERE entry=-1324; -- content: We will never dissipate, mortal... Our fate is tied to Gorefiend...
UPDATE creature_ai_texts SET content_loc8='We are bound here... eternally. It is the will of Gorefiend.' WHERE entry=-1325; -- content: We are bound here... eternally. It is the will of Gorefiend.
UPDATE creature_ai_texts SET content_loc8='Gorefiend will have your head, interloper!' WHERE entry=-1326; -- content: Gorefiend will have your head, interloper!
UPDATE creature_ai_texts SET content_loc8='Face the wrath of Bristlelimb!' WHERE entry=-1418; -- content: Face the wrath of Bristlelimb!
UPDATE creature_ai_texts SET content_loc8='How dare you trifle with my playthings!' WHERE entry=-2000; -- content: How dare you trifle with my playthings!

SET NAMES 'latin1';
