-- File generated by Mangos Online Translation Editor (MOTE) v2.05
SET NAMES 'utf8';
UPDATE `locales_creature` SET `name_loc8`='Waypoint (Only GM can see it)',`subname_loc8`='Visual' WHERE `entry`=1;
UPDATE `locales_creature` SET `subname_loc8`='The Head of The Black Flight' WHERE `entry`=11583;
UPDATE `locales_creature` SET `subname_loc8`='Aldor: Quartermaster' WHERE `entry`=19321;
UPDATE `locales_creature` SET `subname_loc8`='Scryers: Quartermaster' WHERE `entry`=19331;
UPDATE `locales_creature` SET `subname_loc8`='Ticket Redeemer' WHERE `entry`=24495;

SET NAMES 'latin1';
