-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc8='Cipher of Damnation belongs to us now!' WHERE entry=-23; /* content: Cipher of Damnation belongs to us now! */
UPDATE creature_ai_texts SET content_loc8='Get it while it\'s hot!' WHERE entry=-142; /* content: Get it while it\'s hot! */
UPDATE creature_ai_texts SET content_loc8='Aaaahhhhhh!' WHERE entry=-212; /* content: Aaaahhhhhh! */
UPDATE creature_ai_texts SET content_loc8='%s\'s death cry has stirred the nearby silithid hive.' WHERE entry=-344; /* content: %s\'s death cry has stirred the nearby silithid hive. */
UPDATE creature_ai_texts SET content_loc8='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE entry=-425; /* content: Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya. */
UPDATE creature_ai_texts SET content_loc8='Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.' WHERE entry=-426; /* content: Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like. */
UPDATE creature_ai_texts SET content_loc8='O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.' WHERE entry=-428; /* content: O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city. */
UPDATE creature_ai_texts SET content_loc8='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE entry=-641; /* content: At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you. */
UPDATE creature_ai_texts SET content_loc8='%s faces southeast and whimpers before looking back at you. ' WHERE entry=-663; /* content: %s faces southeast and whimpers before looking back at you. */
UPDATE creature_ai_texts SET content_loc8='I have... failed.' WHERE entry=-700; /* content: I have... failed. */
UPDATE creature_ai_texts SET content_loc8='You\'ve restored my health! I\'m in your debt, $N.' WHERE entry=-743; /* content: You\'ve restored my health! I\'m in your debt, $N. */
UPDATE creature_ai_texts SET content_loc8='You\'ve found a cure! We will crush our enemies!' WHERE entry=-744; /* content: You\'ve found a cure! We will crush our enemies! */
UPDATE creature_ai_texts SET content_loc8='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!' WHERE entry=-748; /* content: SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT! */
UPDATE creature_ai_texts SET content_loc8='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!' WHERE entry=-749; /* content: SMOTTS! HEY, SMOTTS! COME OUT AND PLAY! */
UPDATE creature_ai_texts SET content_loc8='DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!' WHERE entry=-750; /* content: DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY! */
UPDATE creature_ai_texts SET content_loc8='COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...' WHERE entry=-751; /* content: COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS... */
UPDATE creature_ai_texts SET content_loc8='I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!' WHERE entry=-752; /* content: I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM! */
UPDATE creature_ai_texts SET content_loc8='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?' WHERE entry=-753; /* content: HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE? */
UPDATE creature_ai_texts SET content_loc8='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?' WHERE entry=-755; /* content: I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK? */
UPDATE creature_ai_texts SET content_loc8='Never underestimate the other ethereal\'s greed.' WHERE entry=-816; /* content: Never underestimate the other ethereal\'s greed. */
UPDATE creature_ai_texts SET content_loc8='%s attacks Karang\'s Banner!' WHERE entry=-828; /* content: %s attacks Karang\'s Banner! */
UPDATE creature_ai_texts SET content_loc8='%s shimmers and becomes intangible.' WHERE entry=-830; /* content: %s shimmers and becomes intangible. */
UPDATE creature_ai_texts SET content_loc8='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE entry=-831; /* content: Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results! */
UPDATE creature_ai_texts SET content_loc8='%s grabs the back of his neck and his eyes go wide.' WHERE entry=-934; /* content: %s grabs the back of his neck and his eyes go wide. */
UPDATE creature_ai_texts SET content_loc8='Off with you, $N.' WHERE entry=-936; /* content: Off with you, $N. */
UPDATE creature_ai_texts SET content_loc8='Move along, $c.' WHERE entry=-937; /* content: Move along, $c. */
UPDATE creature_ai_texts SET content_loc8='Looks like today was the wrong day to quit mana tapping...' WHERE entry=-963; /* content: Looks like today was the wrong day to quit mana tapping... */
UPDATE creature_ai_texts SET content_loc8='Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares!' WHERE entry=-976; /* content: Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares! */
UPDATE creature_ai_texts SET content_loc8='Are you hungry? I\'m hungry. I just can\'t stand the thought of cured ham steak from Thultash again. If only we could get some of that succulent roasted quail!' WHERE entry=-977; /* content: Are you hungry? I\'m hungry. I just can\'t stand the thought of cured ham steak from Thultash again. If only we could get some of that succulent roasted quail! */
UPDATE creature_ai_texts SET content_loc8='Hahaha! That fool will never find out what I\'m up to! Or, if he does, it\'ll be too late for the draenei!' WHERE entry=-978; /* content: Hahaha! That fool will never find out what I\'m up to! Or, if he does, it\'ll be too late for the draenei! */
UPDATE creature_ai_texts SET content_loc8='Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones!' WHERE entry=-979; /* content: Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones! */
UPDATE creature_ai_texts SET content_loc8='Are They all.... Dead?' WHERE entry=-981; /* content: Are They all.... Dead? */
UPDATE creature_ai_texts SET content_loc8='Mistress!! They seek to destroy your work!' WHERE entry=-985; /* content: Mistress!! They seek to destroy your work! */
UPDATE creature_ai_texts SET content_loc8='Drohn\'s brew is the stuff legends are made of! Come taste the legend!' WHERE entry=-997; /* content: Drohn\'s brew is the stuff legends are made of! Come taste the legend! */
UPDATE creature_ai_texts SET content_loc8='We drink for the Horde! Do you drink for the Horde? Come show us at Drohn\'s Distillery!' WHERE entry=-998; /* content: We drink for the Horde! Do you drink for the Horde? Come show us at Drohn\'s Distillery! */
UPDATE creature_ai_texts SET content_loc8='Hey you, the tall one... Want to put some hair on your chest? Drohn\'s Distillery can help you out!' WHERE entry=-999; /* content: Hey you, the tall one... Want to put some hair on your chest? Drohn\'s Distillery can help you out! */
UPDATE creature_ai_texts SET content_loc8='Drohn\'s Distillery has the best brew money can buy! They were voted "Outstanding Brew" by Monthly Goblin Brew!' WHERE entry=-1000; /* content: Drohn\'s Distillery has the best brew money can buy! They were voted "Outstanding Brew" by Monthly Goblin Brew! */
UPDATE creature_ai_texts SET content_loc8='T\'chali\'s Voodoo Brews helps keep the party going! Check out the party at Brewfest!' WHERE entry=-1002; /* content: T\'chali\'s Voodoo Brews helps keep the party going! Check out the party at Brewfest! */
UPDATE creature_ai_texts SET content_loc8='Hey you! T\'chali\'s Voodoo Brewers have got a brew that won\'t kill you! But they\'ve also got a brew that might...' WHERE entry=-1003; /* content: Hey you! T\'chali\'s Voodoo Brewers have got a brew that won\'t kill you! But they\'ve also got a brew that might... */
UPDATE creature_ai_texts SET content_loc8='T\'chali\'s Voodoo Brewery has the best brew you can find! They were voted "Best Brew" by the Goblin Brew Weekly!' WHERE entry=-1004; /* content: T\'chali\'s Voodoo Brewery has the best brew you can find! They were voted "Best Brew" by the Goblin Brew Weekly! */
UPDATE creature_ai_texts SET content_loc8='Whoah! Walk by again girl!' WHERE entry=-1005; /* content: Whoah! Walk by again girl! */
UPDATE creature_ai_texts SET content_loc8='Hey, hey sweet thing! Looking good!' WHERE entry=-1007; /* content: Hey, hey sweet thing! Looking good! */
UPDATE creature_ai_texts SET content_loc8='Hey, hey! Nice build you got there honey!' WHERE entry=-1008; /* content: Hey, hey! Nice build you got there honey! */
UPDATE creature_ai_texts SET content_loc8='Hey tough stuff! Hey, $c! Do you like money? I\'m loaded! How about you come over here and check out my gold coins?' WHERE entry=-1010; /* content: Hey tough stuff! Hey, $c! Do you like money? I\'m loaded! How about you come over here and check out my gold coins? */
UPDATE creature_ai_texts SET content_loc8='This will teach you to lay off the herb, $r.' WHERE entry=-1019; /* content: This will teach you to lay off the herb, $r. */
UPDATE creature_ai_texts SET content_loc8='The Scarlet Crusade shall not fail in it\'s mission!' WHERE entry=-1030; /* content: The Scarlet Crusade shall not fail in it\'s mission! */
UPDATE creature_ai_texts SET content_loc8='The Agamand Mills is held by the Scourge, $c. Join us!' WHERE entry=-1034; /* content: The Agamand Mills is held by the Scourge, $c. Join us! */
UPDATE creature_ai_texts SET content_loc8='You are in the presence of a god!' WHERE entry=-1048; /* content: You are in the presence of a god! */
UPDATE creature_ai_texts SET content_loc8='%s seems to no longer be able to cast spells...' WHERE entry=-1058; /* content: %s seems to no longer be able to cast spells... */
UPDATE creature_ai_texts SET content_loc8='Come on! These jokes are epic!' WHERE entry=-1076; /* content: Come on! These jokes are epic! */
UPDATE creature_ai_texts SET content_loc8='Look who\'s here, it\'s Raliq the drunk... His momma\'s so fat dragon\'s won\'t eat her...' WHERE entry=-1116; /* content: Look who\'s here, it\'s Raliq the drunk... His momma\'s so fat dragon\'s won\'t eat her... */
UPDATE creature_ai_texts SET content_loc8='They dont\'t know where to store the leftovers!' WHERE entry=-1117; /* content: They dont\'t know where to store the leftovers! */
UPDATE creature_ai_texts SET content_loc8='Wow! The laughs dont\'t drop very often here, do they?' WHERE entry=-1118; /* content: Wow! The laughs dont\'t drop very often here, do they? */
UPDATE creature_ai_texts SET content_loc8='Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!' WHERE entry=-1206; /* content: Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair! */
UPDATE creature_ai_texts SET content_loc8='Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!' WHERE entry=-1207; /* content: Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might! */
UPDATE creature_ai_texts SET content_loc8='Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!' WHERE entry=-1208; /* content: Cower, little worms! Your heroes are nothing! Your saviors will be our first feast! */
UPDATE creature_ai_texts SET content_loc8='Where? Where are the Shards! You cannot hide them from us!' WHERE entry=-1209; /* content: Where? Where are the Shards! You cannot hide them from us! */
UPDATE creature_ai_texts SET content_loc8='Your world will die, mortals! Your doom is now at hand!' WHERE entry=-1210; /* content: Your world will die, mortals! Your doom is now at hand! */
UPDATE creature_ai_texts SET content_loc8='Your own strength feeds me!' WHERE entry=-1211; /* content: Your own strength feeds me! */
UPDATE creature_ai_texts SET content_loc8='Ha! This place is not yet worthy of my infliction.' WHERE entry=-1212; /* content: Ha! This place is not yet worthy of my infliction. */
UPDATE creature_ai_texts SET content_loc8='Skywing! I will free you from your curse over my dead body!' WHERE entry=-1220; /* content: Skywing! I will free you from your curse over my dead body! */
UPDATE creature_ai_texts SET content_loc8='Cabal Summoner summons a Cabal Deathsworn to his aid!' WHERE entry=-1247; /* content: Cabal Summoner summons a Cabal Deathsworn to his aid! */
UPDATE creature_ai_texts SET content_loc8='Cabal Summoner summons a Cabal Acolyte to his aid!' WHERE entry=-1248; /* content: Cabal Summoner summons a Cabal Acolyte to his aid! */
UPDATE creature_ai_texts SET content_loc8='Foolish mortal, you serve me now!' WHERE entry=-1295; /* content: Foolish mortal, you serve me now! */
UPDATE creature_ai_texts SET content_loc8='At last, it ends...' WHERE entry=-1298; /* content: At last, it ends... */
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper lays an egg!' WHERE entry=-1317; /* content: Silithid Creeper lays an egg! */
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg begins to crack and open...' WHERE entry=-1318; /* content: Silithid Creeper Egg begins to crack and open... */
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg splits open!' WHERE entry=-1319; /* content: Silithid Creeper Egg splits open! */
UPDATE creature_ai_texts SET content_loc8='Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!' WHERE entry=-1320; /* content: Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients! */
UPDATE creature_ai_texts SET content_loc8='How dare you trifle with my playthings!' WHERE entry=-2000; /* content: How dare you trifle with my playthings! */

SET NAMES 'latin1';
