-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc8`='Hey there, $N. How can I help you?' WHERE `word_id`=192037; -- locales_npc_text - Text0_1 : entry=2
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=354
UPDATE `trans_words`SET `content_loc8`='I\'m sad to see that the furbolgs could have been corrupted so easily, before they were our friends.' WHERE `word_id`=214162; -- locales_npc_text - Text1_0 : entry=3461
UPDATE `trans_words`SET `content_loc8`='You have truly accelled in your knowledge of enchanting. There is much more to learn, if you are willing. Speak to Taladan, in the Craftsmen\'s Terrace in Darnassus.' WHERE `word_id`=193746; -- locales_npc_text - Text0_1 : entry=5191
UPDATE `trans_words`SET `content_loc8`='You have nearly reached the pinnacle of your training. To become the greatest enchanter you can possibly be, you have one more instructor to seek out. Her name is Annora, and you may find her in Uldaman.' WHERE `word_id`=193793; -- locales_npc_text - Text0_1 : entry=5244
UPDATE `trans_words`SET `content_loc8`='You are eager, that is good. However, you are not yet ready to train with the likes of me.' WHERE `word_id`=193794; -- locales_npc_text - Text0_1 : entry=5246
UPDATE `trans_words`SET `content_loc8`='Your education is nearly complete. One final task is all that stands between you and the culmination of all your efforts.' WHERE `word_id`=193801; -- locales_npc_text - Text0_1 : entry=5255
UPDATE `trans_words`SET `content_loc8`='You have worked your way up, time to see the boss. Go to Josef and tell him you are ready.' WHERE `word_id`=193974; -- locales_npc_text - Text0_1 : entry=5557
UPDATE `trans_words`SET `content_loc8`='The Stormpike Guard is in need of your assistance in the fight against the Frostwolf Clan, $N. Speak to Brogun Stoneshield on the Warrior\'s Terrace and he will help you find your way to Alterac Valley.' WHERE `word_id`=194630; -- locales_npc_text - Text1_1 : entry=7496
UPDATE `trans_words`SET `content_loc8`='The Silverwing Sentinels can use all the help they can get in their fight against the Warsong Outriders. $N, go to Stormwind Keep and speak with Elfarran if you wish to assist them.' WHERE `word_id`=194638; -- locales_npc_text - Text1_0 : entry=7501
UPDATE `trans_words`SET `content_loc8`='There is one that I know of here in Thunder Bluff that can aid you in your journey to Alterac Valley. On the Hunter Rise look for Taim Ragetotem. May you find what you are looking for $N.' WHERE `word_id`=194644; -- locales_npc_text - Text1_0 : entry=7505
UPDATE `trans_words`SET `content_loc8`='<Greatmother Geyah smiles at you.>$B$BYou remind me of my son, $N.$B$BHe was an immovable mountain: A pillar of strength and honor.$B$B<Geyahs eyes well up with tears.>$B$BHe sacrificed himself so that we could survive. So that generations of orcs after him could be born into a world without the blood curse... Without Guldan and his dark Horde...$B$B<Geyah stares into the distance, lost in thought.>$B$BOh Durotan, how I wish you could be here. Your people so desperately need you...' WHERE `word_id`=278220; -- locales_npc_text - Text0_1 : entry=9822
UPDATE `trans_words`SET `content_loc8`='Greatmother Geyahs violet eyes lock onto yours.>$B$BYes...' WHERE `word_id`=278221; -- locales_npc_text - Text0_1 : entry=9824
UPDATE `trans_words`SET `content_loc8`='<Tears stream down Greatmother Geyahs face.>$B$BI... I... Durotan survived to have a child? The child Draka told me of before they left... It was their greatest fear... To raise a child in this world. On the other side of that gate was their only hope. I dared not tell Durotan, but secretly, I begged the spirits to watch over them - to protect their child and to give them strength.$B$BI... I must see my grandchild. I must see him. Please, I am too weak. You must tell him. Before I leave this world...' WHERE `word_id`=278222; -- locales_npc_text - Text0_1 : entry=9825
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text2_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text4_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text6_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text7_1 : entry=10734
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=10872
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11459
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11584
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11907
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=13481
UPDATE `trans_words`SET `content_loc8`='Greetings, $C.$B$BWhen the Alliance controls Wintergrasp Fortress, I will open a portal for those who wish to travel there.$B$BThe next battle begins in $3975w:$3976w$3782w:$3784w$3785w.' WHERE `word_id`=199538; -- locales_npc_text - Text0_1 : entry=14083
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=14170
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_0 : entry=14536
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_0 : entry=14536
UPDATE `trans_words`SET `content_loc8`='Iam Here, Commander' WHERE `word_id`=196931; -- locales_npc_text - Text0_1 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196932; -- locales_npc_text - Text1_0 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Arxes! Send help! Im pinned down in the mines, I...Im not sure where iam exactly but i had the presence of mind to drop tracers on the gro8und behind me' WHERE `word_id`=196933; -- locales_npc_text - Text1_1 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Copy, Status report, Soldier.' WHERE `word_id`=196936; -- locales_npc_text - Text0_1 : entry=20564
UPDATE `trans_words`SET `content_loc8`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196937; -- locales_npc_text - Text1_0 : entry=20564

SET NAMES 'latin1';
