-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc2='Lion\'s Pride Inn' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind Auction House' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind Bank' WHERE entry=19; /* icon_name: Stormwind Bank */
UPDATE locales_points_of_interest SET icon_name_loc2='The Deeprun Tram' WHERE entry=21; /* icon_name: The Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind Gryphon Master' WHERE entry=23; /* icon_name: Stormwind Gryphon Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind Locksmith' WHERE entry=25; /* icon_name: Stormwind Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Stormwind' WHERE entry=29; /* icon_name: Battlemasters Stormwind */
UPDATE locales_points_of_interest SET icon_name_loc2='Hunter Lodge' WHERE entry=33; /* icon_name: Hunter Lodge */
UPDATE locales_points_of_interest SET icon_name_loc2='Wizard\'s Sanctum' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc2='Cathedral Of Light' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind - Rogue House' WHERE entry=36; /* icon_name: Stormwind - Rogue House */
UPDATE locales_points_of_interest SET icon_name_loc2='Stormwind Barracks' WHERE entry=39; /* icon_name: Stormwind Barracks */
UPDATE locales_points_of_interest SET icon_name_loc2='The Vault' WHERE entry=51; /* icon_name: The Vault */
UPDATE locales_points_of_interest SET icon_name_loc2='Ironforge Gryphon Master' WHERE entry=53; /* icon_name: Ironforge Gryphon Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Stonefire Tavern' WHERE entry=55; /* icon_name: Stonefire Tavern */
UPDATE locales_points_of_interest SET icon_name_loc2='Ironforge Mailbox' WHERE entry=56; /* icon_name: Ironforge Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Bixi and Buliwyf' WHERE entry=58; /* icon_name: Bixi and Buliwyf */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Ironforge' WHERE entry=59; /* icon_name: Battlemasters Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc2='Hall of Arms' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc2='Hall of Mysteries' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc2='Ironforge Rogue Trainer' WHERE entry=63; /* icon_name: Ironforge Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Ironforge Warlock Trainer' WHERE entry=64; /* icon_name: Ironforge Warlock Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Ironforge Shaman Trainer' WHERE entry=65; /* icon_name: Ironforge Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Deepmountain Mining Guild' WHERE entry=74; /* icon_name: Deepmountain Mining Guild */
UPDATE locales_points_of_interest SET icon_name_loc2='Thunderbrew Distillery' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Auction House' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Bank' WHERE entry=90; /* icon_name: Darnassus Bank */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Hippogryph Master' WHERE entry=91; /* icon_name: Darnassus Hippogryph Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Guild Master' WHERE entry=92; /* icon_name: Darnassus Guild Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Inn' WHERE entry=93; /* icon_name: Darnassus Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Mailbox' WHERE entry=94; /* icon_name: Darnassus Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Darnassus' WHERE entry=97; /* icon_name: Battlemasters Darnassus */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Druid Trainer' WHERE entry=98; /* icon_name: Darnassus Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Hunter Trainer' WHERE entry=99; /* icon_name: Darnassus Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Rogue Trainer' WHERE entry=100; /* icon_name: Darnassus Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Warrior\'s Terrace' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Alchemy Trainer' WHERE entry=102; /* icon_name: Darnassus Alchemy Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Cooking Trainer' WHERE entry=103; /* icon_name: Darnassus Cooking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Enchanting Trainer' WHERE entry=104; /* icon_name: Darnassus Enchanting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus First Aid Trainer' WHERE entry=105; /* icon_name: Darnassus First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Fishing Trainer' WHERE entry=106; /* icon_name: Darnassus Fishing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Leatherworking Trainer' WHERE entry=108; /* icon_name: Darnassus Leatherworking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Skinning Trainer' WHERE entry=109; /* icon_name: Darnassus Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Tailor' WHERE entry=110; /* icon_name: Darnassus Tailor */
UPDATE locales_points_of_interest SET icon_name_loc2='Dolanaar Inn' WHERE entry=111; /* icon_name: Dolanaar Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='The Sky Tower' WHERE entry=177; /* icon_name: The Sky Tower */
UPDATE locales_points_of_interest SET icon_name_loc2='Orgrimmar Inn' WHERE entry=179; /* icon_name: Orgrimmar Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Orgrimmar Mailbox' WHERE entry=180; /* icon_name: Orgrimmar Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Orgrimmar Eastern Zeppelin Tower' WHERE entry=182; /* icon_name: Orgrimmar Eastern Zeppelin Tower */
UPDATE locales_points_of_interest SET icon_name_loc2='Orgrimmar Western Zeppelin Tower' WHERE entry=183; /* icon_name: Orgrimmar Western Zeppelin Tower */
UPDATE locales_points_of_interest SET icon_name_loc2='Sayoc & Hanashi' WHERE entry=184; /* icon_name: Sayoc & Hanashi */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Orgrimmar' WHERE entry=187; /* icon_name: Battlemasters Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Auctioneer' WHERE entry=190; /* icon_name: Exodar, Auctioneer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, bank' WHERE entry=191; /* icon_name: Exodar, bank */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Hippogryph Master' WHERE entry=192; /* icon_name: Exodar, Hippogryph Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Guild Master' WHERE entry=193; /* icon_name: Exodar, Guild Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Inn' WHERE entry=194; /* icon_name: Exodar, Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Mailbox' WHERE entry=195; /* icon_name: Exodar, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Stable Master' WHERE entry=196; /* icon_name: Exodar, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Weapon Master' WHERE entry=197; /* icon_name: Exodar, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Druid Trainer' WHERE entry=198; /* icon_name: Exodar, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Hunter Trainers' WHERE entry=199; /* icon_name: Exodar, Hunter Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Mage Trainers' WHERE entry=200; /* icon_name: Exodar, Mage Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Paladin Trainers' WHERE entry=201; /* icon_name: Exodar, Paladin Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Priest Trainers' WHERE entry=202; /* icon_name: Exodar, Priest Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Shaman Trainer' WHERE entry=203; /* icon_name: Exodar, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Warrior Trainers' WHERE entry=204; /* icon_name: Exodar, Warrior Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Alchemist Trainers' WHERE entry=205; /* icon_name: Exodar, Alchemist Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Blacksmithing Trainers' WHERE entry=206; /* icon_name: Exodar, Blacksmithing Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Enchanters' WHERE entry=207; /* icon_name: Exodar, Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Engineering' WHERE entry=208; /* icon_name: Exodar, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, First Aid Trainer' WHERE entry=209; /* icon_name: Exodar, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Fishing Trainer' WHERE entry=210; /* icon_name: Exodar, Fishing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Herbalist Trainer' WHERE entry=211; /* icon_name: Exodar, Herbalist Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Jewelcrafters' WHERE entry=213; /* icon_name: Exodar, Jewelcrafters */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Leatherworking' WHERE entry=214; /* icon_name: Exodar, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Mining Trainers' WHERE entry=215; /* icon_name: Exodar, Mining Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Skinning Trainer' WHERE entry=216; /* icon_name: Exodar, Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Tailors' WHERE entry=217; /* icon_name: Exodar, Tailors */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Cook' WHERE entry=218; /* icon_name: Exodar, Cook */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Innkeeper' WHERE entry=219; /* icon_name: Azure Watch, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Stable Master' WHERE entry=220; /* icon_name: Azure Watch, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Hunter Trainer' WHERE entry=221; /* icon_name: Azure Watch, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Mage Trainer' WHERE entry=222; /* icon_name: Azure Watch, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Paladin Trainer' WHERE entry=223; /* icon_name: Azure Watch, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Priest Trainer' WHERE entry=224; /* icon_name: Azure Watch, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Shaman Trainer' WHERE entry=225; /* icon_name: Azure Watch, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Warrior Trainer' WHERE entry=226; /* icon_name: Azure Watch, Warrior Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Alchemist' WHERE entry=227; /* icon_name: Azure Watch, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc2='Odesyus\' Landing, Blacksmith' WHERE entry=228; /* icon_name: Odesyus\' Landing, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc2='Odesyus\' Landing, Cook' WHERE entry=229; /* icon_name: Odesyus\' Landing, Cook */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Engineering Trainer' WHERE entry=230; /* icon_name: Azure Watch, Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, First Aid Trainer' WHERE entry=231; /* icon_name: Azure Watch, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Ammen Ford, Fisherwoman' WHERE entry=232; /* icon_name: Ammen Ford, Fisherwoman */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Herbalist' WHERE entry=233; /* icon_name: Azure Watch, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc2='Stillpine Hold, Leatherworker' WHERE entry=234; /* icon_name: Stillpine Hold, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc2='Azure Watch, Mining Trainer' WHERE entry=235; /* icon_name: Azure Watch, Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Stillpine Hold, Skinner' WHERE entry=236; /* icon_name: Stillpine Hold, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc2='Odesyus\' Landing, Tailor' WHERE entry=237; /* icon_name: Odesyus\' Landing, Tailor */
UPDATE locales_points_of_interest SET icon_name_loc2='Razor Hill Inn' WHERE entry=253; /* icon_name: Razor Hill Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Tailoring Trainer' WHERE entry=254; /* icon_name: Undercity Tailoring Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Skinning Trainer' WHERE entry=255; /* icon_name: Undercity Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Mining Trainer' WHERE entry=256; /* icon_name: Undercity Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Leatherworking Trainer' WHERE entry=257; /* icon_name: Undercity Leatherworking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Herbalism Trainer' WHERE entry=259; /* icon_name: Undercity Herbalism Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Fishing Trainer' WHERE entry=260; /* icon_name: Undercity Fishing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity First Aid Trainer' WHERE entry=261; /* icon_name: Undercity First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Engineering Trainer' WHERE entry=262; /* icon_name: Undercity Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Enchanting Trainer' WHERE entry=263; /* icon_name: Undercity Enchanting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Cooking Trainer' WHERE entry=264; /* icon_name: Undercity Cooking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Blacksmithing Trainer' WHERE entry=265; /* icon_name: Undercity Blacksmithing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Warrior Trainers' WHERE entry=267; /* icon_name: Undercity Warrior Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Warlock Trainers' WHERE entry=268; /* icon_name: Undercity Warlock Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Rogue Trainers' WHERE entry=269; /* icon_name: Undercity Rogue Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Priest Trainers' WHERE entry=270; /* icon_name: Undercity Priest Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Mage Trainers' WHERE entry=272; /* icon_name: Undercity Mage Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Zeppelin' WHERE entry=273; /* icon_name: Undercity Zeppelin */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Mailbox' WHERE entry=276; /* icon_name: Undercity Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Locksmith' WHERE entry=277; /* icon_name: Undercity Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Inn' WHERE entry=278; /* icon_name: Undercity Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Guild Master' WHERE entry=279; /* icon_name: Undercity Guild Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Undercity' WHERE entry=280; /* icon_name: Battlemasters Undercity */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Bat Handler' WHERE entry=281; /* icon_name: Undercity Bat Handler */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Bank' WHERE entry=283; /* icon_name: Undercity Bank */
UPDATE locales_points_of_interest SET icon_name_loc2='Undercity Auction House' WHERE entry=284; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc2='Gallows\' End Tavern' WHERE entry=299; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc2='Thunder Bluff Zeppelin' WHERE entry=300; /* icon_name: Thunder Bluff Zeppelin */
UPDATE locales_points_of_interest SET icon_name_loc2='Pools of Vision' WHERE entry=315; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc2='Battlemasters Thunder Bluff' WHERE entry=317; /* icon_name: Battlemasters Thunder Bluff */
UPDATE locales_points_of_interest SET icon_name_loc2='Thunder Bluff Auction house' WHERE entry=320; /* icon_name: Thunder Bluff Auction house */
UPDATE locales_points_of_interest SET icon_name_loc2='Thunder Bluff Mailbox' WHERE entry=321; /* icon_name: Thunder Bluff Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Thunder Bluff Inn' WHERE entry=322; /* icon_name: Thunder Bluff Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Wind Rider Roost' WHERE entry=324; /* icon_name: Wind Rider Roost */
UPDATE locales_points_of_interest SET icon_name_loc2='Bloodhoof Village Inn' WHERE entry=338; /* icon_name: Bloodhoof Village Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Cantina' WHERE entry=340; /* icon_name: Shattrath Cantina */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Taxi' WHERE entry=341; /* icon_name: Shattrath Taxi */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Alchemist' WHERE entry=342; /* icon_name: Shattrath Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Armor/Weapon Crafter' WHERE entry=343; /* icon_name: Shattrath Armor/Weapon Crafter */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Cook' WHERE entry=344; /* icon_name: Shattrath Cook */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Enchanters' WHERE entry=345; /* icon_name: Shattrath Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath First Aid' WHERE entry=346; /* icon_name: Shattrath First Aid */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Jewelcrafter' WHERE entry=347; /* icon_name: Shattrath Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Leatherworker' WHERE entry=348; /* icon_name: Shattrath Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Skinner' WHERE entry=349; /* icon_name: Shattrath Skinner */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Mana Loom' WHERE entry=350; /* icon_name: Shattrath Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Alchemy Lab' WHERE entry=351; /* icon_name: Shattrath Alchemy Lab */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Bank Aldor' WHERE entry=352; /* icon_name: Shattrath Bank Aldor */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Bank Scryer' WHERE entry=353; /* icon_name: Shattrath Bank Scryer */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Inn Aldor' WHERE entry=354; /* icon_name: Shattrath Inn Aldor */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Inn Scryer' WHERE entry=355; /* icon_name: Shattrath Inn Scryer */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Stable Aldor' WHERE entry=356; /* icon_name: Shattrath Stable Aldor */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Stable Scryer' WHERE entry=357; /* icon_name: Shattrath Stable Scryer */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Battlemasters Alliance' WHERE entry=358; /* icon_name: Shattrath Battlemasters Alliance */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Battlemasters Horde' WHERE entry=359; /* icon_name: Shattrath Battlemasters Horde */
UPDATE locales_points_of_interest SET icon_name_loc2='Shattrath Arena Battlemasters' WHERE entry=360; /* icon_name: Shattrath Arena Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc2='Aldor Gem Vendor' WHERE entry=361; /* icon_name: Aldor Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc2='Scryer Gem Vendor' WHERE entry=362; /* icon_name: Scryer Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc2='Temple of the Moon' WHERE entry=364; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Auction House' WHERE entry=367; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Auction House' WHERE entry=368; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Bank' WHERE entry=369; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Bank' WHERE entry=370; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Flight Master' WHERE entry=371; /* icon_name: Silvermoon City, Flight Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Guild House' WHERE entry=372; /* icon_name: Silvermoon City, Guild House */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Inn' WHERE entry=373; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Inn' WHERE entry=374; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Mailbox' WHERE entry=375; /* icon_name: Silvermoon City, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Stable Master' WHERE entry=376; /* icon_name: Silvermoon City, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Weapon Master' WHERE entry=377; /* icon_name: Silvermoon City, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Battlemasters' WHERE entry=378; /* icon_name: Silvermoon City, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Druid Trainer' WHERE entry=379; /* icon_name: Silvermoon City, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Hunter Trainer' WHERE entry=380; /* icon_name: Silvermoon City, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Mage Trainer' WHERE entry=381; /* icon_name: Silvermoon City, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Paladin Trainer' WHERE entry=382; /* icon_name: Silvermoon City, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Priest Trainer' WHERE entry=383; /* icon_name: Silvermoon City, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Rogue Trainer' WHERE entry=384; /* icon_name: Silvermoon City, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Warlock Trainers' WHERE entry=385; /* icon_name: Silvermoon City, Warlock Trainers */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Alchemy' WHERE entry=386; /* icon_name: Silvermoon City, Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Blacksmithing' WHERE entry=387; /* icon_name: Silvermoon City, Blacksmithing */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Cooking' WHERE entry=388; /* icon_name: Silvermoon City, Cooking */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Enchanting' WHERE entry=389; /* icon_name: Silvermoon City, Enchanting */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Engineering' WHERE entry=390; /* icon_name: Silvermoon City, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, First Aid' WHERE entry=391; /* icon_name: Silvermoon City, First Aid */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Fishing' WHERE entry=392; /* icon_name: Silvermoon City, Fishing */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Herbalism' WHERE entry=393; /* icon_name: Silvermoon City, Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Jewelcrafting' WHERE entry=395; /* icon_name: Silvermoon City, Jewelcrafting */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Leatherworking' WHERE entry=396; /* icon_name: Silvermoon City, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Mining' WHERE entry=397; /* icon_name: Silvermoon City, Mining */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Skinning' WHERE entry=398; /* icon_name: Silvermoon City, Skinning */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Tailoring' WHERE entry=399; /* icon_name: Silvermoon City, Tailoring */
UPDATE locales_points_of_interest SET icon_name_loc2='Silvermoon City, Mana Loom' WHERE entry=400; /* icon_name: Silvermoon City, Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Innkeeper' WHERE entry=401; /* icon_name: Falconwing Square, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Stable Master' WHERE entry=402; /* icon_name: Falconwing Square, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Hunter Trainer' WHERE entry=403; /* icon_name: Falconwing Square, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Mage Trainer' WHERE entry=404; /* icon_name: Falconwing Square, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Paladin Trainer' WHERE entry=405; /* icon_name: Falconwing Square, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Priest Trainer' WHERE entry=406; /* icon_name: Falconwing Square, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Rogue Trainer' WHERE entry=407; /* icon_name: Falconwing Square, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Warlock Trainer' WHERE entry=408; /* icon_name: Falconwing Square, Warlock Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Saltheril\'s Haven, Alchemist' WHERE entry=409; /* icon_name: Saltheril\'s Haven, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc2='Farstrider Retreat, Blacksmith' WHERE entry=410; /* icon_name: Farstrider Retreat, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Cook' WHERE entry=411; /* icon_name: Falconwing Square, Cook */
UPDATE locales_points_of_interest SET icon_name_loc2='Saltheril\'s Haven, Enchanter' WHERE entry=412; /* icon_name: Saltheril\'s Haven, Enchanter */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, First Aid Trainer' WHERE entry=413; /* icon_name: Falconwing Square, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Saltheril\'s Haven, Herbalist' WHERE entry=414; /* icon_name: Saltheril\'s Haven, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc2='Falconwing Square, Jewelcrafter' WHERE entry=415; /* icon_name: Falconwing Square, Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc2='Eversong Woods, Leatherworker' WHERE entry=416; /* icon_name: Eversong Woods, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc2='Eversong Woods, Skinner' WHERE entry=417; /* icon_name: Eversong Woods, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc2='Saltheril\'s Haven, Tailor' WHERE entry=418; /* icon_name: Saltheril\'s Haven, Tailor */
UPDATE locales_points_of_interest SET icon_name_loc2='Orgrimmar Hunter\'s Hall' WHERE entry=420; /* icon_name: Orgrimmar Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Mage Trainer' WHERE entry=438; /* icon_name: Darnassus Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Paladin Trainer' WHERE entry=439; /* icon_name: Darnassus Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Darnassus Herbalism Trainer' WHERE entry=440; /* icon_name: Darnassus Herbalism Trainer */
UPDATE locales_points_of_interest SET icon_name_loc2='Exodar, Battlemasters' WHERE entry=441; /* icon_name: Exodar, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc2='Arena Battlemaster Exodar' WHERE entry=442; /* icon_name: Arena Battlemaster Exodar */

SET NAMES 'latin1';
