-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc4='[PH] SD2 unknown text' WHERE entry=-3000000; /* content: [PH] SD2 unknown text */
UPDATE gossip_texts SET content_loc4='Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc4='I am ready, Anchorite. Let us begin the exorcism.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc4='Your bondage is at an end, Doom\'rel. I challenge you!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc4='You challenged us and we have come. Where is this master you speak of?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc4='Teleport me to the Guardian\'s Library' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc4='Control Human Charger' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc4='Control Conjured Water Elemental' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc4='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */

SET NAMES 'latin1';
