-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc1='피의 투기장으로 들어가게, $n. 곧 대전이 시작될 걸세!' WHERE entry=2000000001; /* content: Get in the Ring of Blood, $N. The fight is about to start! */
UPDATE db_script_string SET content_loc1='전투가 곧 시작됩니다!' WHERE entry=2000000002; /* content: The battle is about to begin! */
UPDATE db_script_string SET content_loc1='좋아요, 어서 가요!' WHERE entry=2000000017; /* content: Ok, let\'s go! */
UPDATE db_script_string SET content_loc1='앗, 나의 실수!' WHERE entry=2000000026; /* content: Whoops! */
UPDATE db_script_string SET content_loc1='이리 오게, $n. 군주님께서 기다리시네.' WHERE entry=2000000034; /* content: Come, $N. Lord Stormrage awaits. */
UPDATE db_script_string SET content_loc1='용아귀 부족의 용사들이여, 모두 모여라! 너희 중 한 용사가 군주가 되었다! 고개를 숙여 경의를 표하라! 너희의 군주이신 $n 님께 존경과 충성을 바치거라!' WHERE entry=2000000035; /* content: Warriors of Dragonmaw, gather \'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N! */
UPDATE db_script_string SET content_loc1='일리단 님께서 곧 도착할 것이네.' WHERE entry=2000000036; /* content: Lord Illidan will be here shortly. */
UPDATE db_script_string SET content_loc1='모두 일리단 님을 맞이하라!' WHERE entry=2000000037; /* content: All hail Lord Illidan! */
UPDATE db_script_string SET content_loc1='일리단 님, 이 오크가 저와 다른 이들이 이야기하던 용아귀 부족의 용사입니다. 이 용사가 우리에게 승리를 가져다줄 것입니다!' WHERE entry=2000000038; /* content: Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory! */
UPDATE db_script_string SET content_loc1='군주님이시여... 저는 이해를 하지 못하겠습니다. 이 오크는...' WHERE entry=2000000039; /* content: But... My lord, I do not understand. $N... He is the orc that has... */
UPDATE db_script_string SET content_loc1='분부대로 하겠습니다, 군주님!' WHERE entry=2000000040; /* content: It will be done, my lord. */
UPDATE db_script_string SET content_loc1='그래, 네놈이 모르고르를 속이려고 했단 말이구나, 그렇지? 일리단 님께 가기 전에 살아서는 구경도 못할 고통을 선사해주마. 기꺼이 내가 당한 복수를 해 주지.' WHERE entry=2000000041; /* content: So you thought to make a fool of Mor\'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance. */
UPDATE db_script_string SET content_loc1='또 보자고, 용감한 친구.' WHERE entry=2000000042; /* content: Until we meet again, brave one. */
UPDATE db_script_string SET content_loc1='휴, 다 됐소.' WHERE entry=2000000044; /* content: It is done... */
UPDATE db_script_string SET content_loc1='던 모로에서 쌀쌀한 하루를 잘 시작하려면 뜨거운 새벽주 만한 게 없소이다!' WHERE entry=2000000045; /* content: There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right! */
UPDATE db_script_string SET content_loc1='개굴! 안 돼!! 감히 나한테 이럴... 개굴... 수가! 더러운 속임수로 날... 개굴... 속이다니! 개굴!' WHERE entry=2000000047; /* content: Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit! */
UPDATE db_script_string SET content_loc1='이제 이 귀한 흙을 내 화단에 넣읍시다.' WHERE entry=2000000048; /* content: Now let us place this rare earth in my planter... */
UPDATE db_script_string SET content_loc1='도대체 얼마나 많은 보병이 시체가 되어 고향으로 돌아가야만 불타는 군단의 살인 부대로 뛰어드는 것이 자살 행위라는 것을 알겠는가? 그리고 마치 내 말을 이해한다는 듯이 그 큰 머리 좀 끄덕이지 말라!' WHERE entry=2000000055; /* content: How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about! */
UPDATE db_script_string SET content_loc1='별의 힘으로! 아... 영혼이 소환되었소!' WHERE entry=2000000060; /* content: By the stars! A spirit has been summoned! */
UPDATE db_script_string SET content_loc1='아까 우리가 본 것은 참으로 과거의 신비라 하지 않을 수 없소! 동시에 미래에 대한 중요한 열쇠이기도 하오!' WHERE entry=2000000061; /* content: It\'s a mystery of the past indeed! But a key to our future! */
UPDATE db_script_string SET content_loc1='위험은 끝났습니다! $n|1이;가; 우리를 구했습니다!' WHERE entry=2000000062; /* content: The threat be over! $N be savin\' us all! */
UPDATE db_script_string SET content_loc1='어떤 악마의 앞잡이도 우리 땅에 발을 들이도록 허락할 수 없다!' WHERE entry=2000000065; /* content: We will suffer no demon\'s servant in our lands! */
UPDATE db_script_string SET content_loc1='$n, 평화와 인내가 그대와 함께하기를. 항상 강함을 유지하시기 바랍니다.' WHERE entry=2000000066; /* content: Peace and patience be with you, $N. Remain strong always. */
UPDATE db_script_string SET content_loc1='침입자여, 이세라 님의 영역에서 뭘 하는 거지? 우리를 떠나게! 이곳은 그대 종족을 환영하지 않아!' WHERE entry=2000000067; /* content: What are you doing in Ysera\'s realm, interloper? Leave us, I say! Your kind are not welcome here! */
UPDATE db_script_string SET content_loc1='그대는... 저들과 한패가 아니로군! 놈들이 우릴 발각하기 전에 어서 벗어나자고! 서두르게!' WHERE entry=2000000068; /* content: You -- you\'re not one of them! Let\'s get out of sight before they find us! Hurry! */
UPDATE db_script_string SET content_loc1='$r|1이여;여;, 놈들이 날 쫓고 있어! 놈들에게 발각되기 전에 이곳에 왜 왔는지부터 말하게! 놈들이 날 잡으면, 나와 그대는 끝장이란 말이야!' WHERE entry=2000000069; /* content: They\'re following me, $R! Quickly, tell me why you\'re here before we\'re discovered! If they catch up to me, it will mean my death and yours! */
UPDATE db_script_string SET content_loc1='새매야, 정말 고맙구나. 네가 없었으면 우린 몇 년이고 까마귀 경전을 찾느라 헤맸을지도 몰라. 이제 나그란드에 있는 네 집으로 돌아가거라.' WHERE entry=2000000070; /* content: It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude. */
UPDATE db_script_string SET content_loc1='이거야! 진짜 까마귀 경전을 우리 손에 넣었네요!' WHERE entry=2000000071; /* content: This is it! This is really it -- the Book of the Raven! */
UPDATE db_script_string SET content_loc1='예상대로 이 경전에서 필요한 정보를 얻어냈습니다. 놈이 에메랄드의 꿈에 더 피해를 주기 전에, 이 정보를 이용해 안주를 끌어내 쓰러뜨려야 합니다!' WHERE entry=2000000074; /* content: The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream! */
UPDATE db_script_string SET content_loc1='새매가 까마귀석의 위치 추적에 성공한 이후로, 엘라이라가 무척 먼 거리에 내 목소리를 전하기 위해 다른 새매 녀석을 훈련시키고 있답니다. 그가 당신이 서판에서 밝혀진 새 영혼을 조사하면서 우리와 교신하는데 도움을 줄 겁니다.' WHERE entry=2000000075; /* content: Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet! */
UPDATE db_script_string SET content_loc1='이 영혼석을 깨는 건 아주 간단한 일이지!' WHERE entry=2000000077; /* content: A simple enough task to break this soulstone! */
UPDATE db_script_string SET content_loc1='이제 애스리쿠스 나라신을 처단해야 합니다. 영혼이여, 우리가 그의 마법을 풀 영혼의 보석을 발견할 수 있겠습니까?' WHERE entry=2000000079; /* content: Then we must put an end to Athrikus Narassin. Tell me, spirit, where might we find the other soulgems, to undo his magic? */
UPDATE db_script_string SET content_loc1='대지를 감싸는 공포 속에서 아메스아란은 분리의 고통을 겪었어. 그 속에선 살아남을 수 있는 희망은 거의 없었지.' WHERE entry=2000000081; /* content: In the throes of the Sundering, Ameth\'Aran was at the whim of the terror that gripped the land. There was little hope for survival. */
UPDATE db_script_string SET content_loc1='그때 애스리쿠스가 왔어. 그는 우리를 고통에서 구해주겠다고 했지. 그러곤 보호의 마법을 시전했어.' WHERE entry=2000000082; /* content: Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm. */
UPDATE db_script_string SET content_loc1='마법의 진동이 멈추자 그의 숨겨진 목적이 밝혀졌어. 우린 함정에 빠졌고 그는 천천히 우리의 힘을 빼앗아갔어.' WHERE entry=2000000083; /* content: When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers. */
UPDATE db_script_string SET content_loc1='수백 명이 그의 주문에 갇혀 버렸지. 하지만 이제 그의 주문에 속박된 자는 얼마 안 남게 됐지. 그래도 그는 가끔 우리에게 말을 걸곤 했어.' WHERE entry=2000000084; /* content: There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes. */
UPDATE db_script_string SET content_loc1='그는 자신의 힘이 약해질까 봐 걱정했지. 그리고 자신에게 마지막으로 남은 귀중한 영혼의 보석인 우리마저 사라져 최후를 맞이할까 봐 걱정하고 있었어.' WHERE entry=2000000085; /* content: He worried that his power weakened, that soon even we last of his precious soulgems would fade and die. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 비약의 냄새를 맡고는 게걸스럽게 먹습니다!' WHERE entry=2000000087; /* content: %s sniffs the elixir then eagerly digs in! */
UPDATE db_script_string SET content_loc1='%s|1이;가; 전령을 소환합니다...' WHERE entry=2000000092; /* content: %s summons a messenger... */
UPDATE db_script_string SET content_loc1='아차!' WHERE entry=2000000097; /* content: ... oops. */
UPDATE db_script_string SET content_loc1='흠... 이걸 배달한 다음에 저 치즈 가게에 들러 뭘 좀 먹어야겠군.' WHERE entry=2000000143; /* content: Hm...after dropping this off, I think I\'ll head to that cheese shop for a snack. */
UPDATE db_script_string SET content_loc1='이제 뭘 좀 먹어 볼까...' WHERE entry=2000000151; /* content: Now for that snack... */
UPDATE db_script_string SET content_loc1='정말, 장사가 아주 잘 되더라고!' WHERE entry=2000000156; /* content: Yes ma\'am, business is brisk! */
UPDATE db_script_string SET content_loc1='치즈 고맙습니다!' WHERE entry=2000000157; /* content: Thanks for the cheese! */
UPDATE db_script_string SET content_loc1='가게에 돌아가야 할 시간이군.' WHERE entry=2000000158; /* content: Time to get back to the shop... */
UPDATE db_script_string SET content_loc1='다녀왔소!' WHERE entry=2000000159; /* content: I\'m back! */
UPDATE db_script_string SET content_loc1='크아아아!!' WHERE entry=2000000161; /* content: ROARRRRR!! */
UPDATE db_script_string SET content_loc1='어둠골... 난 배가 고프다!!' WHERE entry=2000000162; /* content: DARKSHIRE...I HUNGER!! */
UPDATE db_script_string SET content_loc1='다시 돌아온다면 광란심장 일족 손에 죽을 것이다. 우리는 이제 너 환영하지 않는다!' WHERE entry=2000000163; /* content: Frenzyheart kill you if you come back. You no welcome here no more! */
UPDATE db_script_string SET content_loc1='%s|1이;가; 북서쪽을 바라보며 긴 울음을 내지릅니다.' WHERE entry=2000000168; /* content: %s stares to the northwest and lets out a long, drawn out howl. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 앞쪽으로 아주 큰 울음을 내지릅니다.' WHERE entry=2000000169; /* content: %s lets forth a mighty howl. */
UPDATE db_script_string SET content_loc1='네가 바란다면...' WHERE entry=2000000195; /* content: As you wish... */
UPDATE db_script_string SET content_loc1='라리크 너한테 교훈 가르쳐 준다!' WHERE entry=2000000196; /* content: Raliq teach you lesson now! */
UPDATE db_script_string SET content_loc1='플루우우우우우운! 쿠쉬쿠쉬 아무것도 못 받았다! 죽어라!' WHERE entry=2000000197; /* content: F\'woooroonn! Coosh\'coosh pay nothing! Die! */
UPDATE db_script_string SET content_loc1='저는 세 번째 방법을 선택하겠습니다. 죽어라!' WHERE entry=2000000198; /* content: I choose the third option: KILLING YOU! */
UPDATE db_script_string SET content_loc1='드디어 자유다! 물의 정령이 우리 일족에게 돌아올 것이오. 그러면 우리는 이 험난한 땅에서 살아남을 수 있는 지혜를 얻을 수 있소이다. 당신에게 빚을 졌구려, $n.' WHERE entry=2000000199; /* content: I\'m free!  The spirit of water returns to my people.  It will bring us the wisdom we need to survive in this harsh land.  I am in your debt, $N. */
UPDATE db_script_string SET content_loc1='당신이 날 구해 줬구려! 다시 한 번 바람이 우리 일족에게 말을 하고 힘을 주고 있소이다. 정말 고맙소.' WHERE entry=2000000200; /* content: You\'ve freed me!  The winds speak to my people once again and grant us their strength.  I thank you, stranger. */
UPDATE db_script_string SET content_loc1='오랜만일세, 베소르, 내 친구여.' WHERE entry=2000000208; /* content: It has been a long time, Bethor, my friend. */
UPDATE db_script_string SET content_loc1='언제 시간 날 때 더 얘기 나누세. 할 얘기가 너무 많다네.' WHERE entry=2000000209; /* content: When time permits, we must speak at length.  For we have much to discuss. */
UPDATE db_script_string SET content_loc1='그리고 고맙네, $n. 자네 도움이 없었다면 결코 포세이큰의 길로 접어들지 못했을 걸세.' WHERE entry=2000000210; /* content: And thank you, $N.  Without your aid I may never have found my way to the Forsaken. */
UPDATE db_script_string SET content_loc1='잘 가게, 친구.' WHERE entry=2000000211; /* content: Farewell, my friend. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 연금술사 자마에게 전갈을 전합니다.' WHERE entry=2000000214; /* content: %s gives message to Apothecary Zamah. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 말루카즈의 부름에 응답하여 포효합니다.' WHERE entry=2000000224; /* content: %s howls in response to Malukaz\'s call. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 자신이 도착했음을 울음소리로 표현합니다.' WHERE entry=2000000225; /* content: %s expresses its approval. */
UPDATE db_script_string SET content_loc1='정령이여, 우리의 결속이 또다시 깨어지는 일이 없기를...' WHERE entry=2000000226; /* content: May our bond with you never be broken again, spirit. */
UPDATE db_script_string SET content_loc1='아롱이가 굶주림에 가득 찬 눈으로 비에라 선위스퍼를 쳐다봅니다.' WHERE entry=2000000390; /* content: Twinkle looks at Viera Sunwhisper with very hungry eyes. */
UPDATE db_script_string SET content_loc1='이게 그 흰 고양이를 얼마나 멀리 날려보낼지 궁금하네요...' WHERE entry=2000000406; /* content: I wonder how far this would launch that white cat... */
UPDATE db_script_string SET content_loc1='중화제를 호수에 섞자 수정에 오염된 물이 깨끗해지는 것 같습니다.' WHERE entry=2000000633; /* content: As the neutralizing agent mixes into the waters of the lake, the water that was irradiated by the crystal seems to clear. */
UPDATE db_script_string SET content_loc1='테돈, 이제 변이된 생물에게 중화제를 시험해 보십시오.' WHERE entry=2000000634; /* content: Tedon, go ahead and try the neutralizing agent on the mutated creature. */
UPDATE db_script_string SET content_loc1='너를 철창에서 꺼내 줄 시간이 된 것 같구나.' WHERE entry=2000000635; /* content: Looks like it\'s time to let you out of this cage. */
UPDATE db_script_string SET content_loc1='자, 이제 중화제를 뿌려 주면...' WHERE entry=2000000636; /* content: Now, to put the neutralizing agent on it... */
UPDATE db_script_string SET content_loc1='성공적입니다!' WHERE entry=2000000637; /* content: Success! */
UPDATE db_script_string SET content_loc1='이건 아무 소용도 없습니다! 지지대로 떠받치지 않으면 건물이 무너지고 말 겁니다.' WHERE entry=2000000645; /* content: This won\'t work at all! The buildings will surely collapse if we do not shore up the support beams. */
UPDATE db_script_string SET content_loc1='소용없다고 하지 않았습니까! 기초를 튼튼히 하지 않으면 건물 전체가 무너질 겁니다!' WHERE entry=2000000646; /* content: This won\'t do at all! We have to secure the foundation or the entire structure will crumble! */
UPDATE db_script_string SET content_loc1='이 건물은 적어도 8가지 이상의 건축 규정을 위반했습니다!' WHERE entry=2000000647; /* content: This structure violates at least 8 different ordinances! */
UPDATE db_script_string SET content_loc1='흠, 훨씬 좋아 보이는군. 안을 한번 살펴볼까...' WHERE entry=2000000649; /* content: Hrm, this looks much better. Let\'s have a look on the inside. */
UPDATE db_script_string SET content_loc1='킬제덴의 썩은 몸통에서 스며 나오는 더러운 기운에 뒤쪽 전체가 날아갔습니다! 어떻게 이런 곳에서 사람이 살겠습니까? 볼만큼 봤단 말입니다!' WHERE entry=2000000650; /* content: By the foul teat of Kil\'Jaeden\'s rotted torso, the entire backside is blown out! How can someone be expected to live in here? I\'ve seen enough! */
UPDATE db_script_string SET content_loc1='이거면 될 것이오...' WHERE entry=2000000655; /* content: This should do it... */
UPDATE db_script_string SET content_loc1='일어나십시오, 작은 친구. 그만 잠에서 깨십시오... 당신은 이제 안전합니다.' WHERE entry=2000000656; /* content: Wake up little creature. Wake up from your slumber... You are safe now. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 신음합니다.' WHERE entry=2000000657; /* content: %s groans. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 일어나 앉습니다.' WHERE entry=2000000658; /* content: %s sits up. */
UPDATE db_script_string SET content_loc1='여... 여기가 어디지? 내... 내가 어디 있는거지?' WHERE entry=2000000659; /* content: Whe... Where am I? What... What is this place? */
UPDATE db_script_string SET content_loc1='%s|1이;가; 다시 의식을 잃습니다.' WHERE entry=2000000661; /* content: %s falls back into a coma. */
UPDATE db_script_string SET content_loc1='이단을 퍼트리는 저런 자와 함께 일을 할 수 있을 거라고 생각하세요?' WHERE entry=2000000663; /* content: How can I be expected to get any work done with that thing spreading its heresy? */
UPDATE db_script_string SET content_loc1='여기에 당신 같은 부류는 필요 없어요.' WHERE entry=2000000665; /* content: We do not need your kind here. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 자기를 따라오라고 합니다.' WHERE entry=2000000666; /* content: %s urges you to follow him. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 쿠우의 토템을 가리킵니다.' WHERE entry=2000000667; /* content: %s points to the totem of Coo. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 자기를 따라오라고 손짓합니다.' WHERE entry=2000000668; /* content: %s motions for you to follow him. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 릭트 킨칙스 아줄 하늘 꼭대기...' WHERE entry=2000000669; /* content: [Furbolg] Ritk kin\'chikx azul azure summit... */
UPDATE db_script_string SET content_loc1='[펄볼그어] 쿠우 시프 플라이... 로스 강을 건너라. 티크티를 찾아라.' WHERE entry=2000000670; /* content: [Furbolg] Coo xip fly... Jump ilos river. Find Tikti. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 강 건너편을 가리킵니다.' WHERE entry=2000000671; /* content: %s points across the river. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 자기를 따라오라고 합니다.' WHERE entry=2000000672; /* content: %s asks that you follow him. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 멀리까지 믹식 탁 너 가라. 강을 키취칼 자세히 보라. 따라오너라. 요르까지 일로그.' WHERE entry=2000000673; /* content: [Furbolg] Far you mixik tak come. Gaze upon the kitch\'kal river. Follow. Ilog to Yor. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 가라... 이틱스킬 강 바닥을 조사해 보라. 남쪽이다!' WHERE entry=2000000674; /* content: [Furbolg] Go... Search yitix\'kil bottom river. South! */
UPDATE db_script_string SET content_loc1='[펄볼그어] 이리 오라, $n. 정화된 채로 함께 물을 떠나자꾸나.' WHERE entry=2000000675; /* content: [Furbolg] Come, $n. Let us leave the water together, purified. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 이제 우리는 함께 가는 것이다. 바르크를 찾아야 한다.' WHERE entry=2000000676; /* content: [Furbolg] We go now, together. We will seek Vark. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 바르크로 가야하니 날 따라오라.' WHERE entry=2000000677; /* content: [Furbolg] Follow me to Vark. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 서두르라, $n. 바르크가 당신을 기다리고 있다.' WHERE entry=2000000678; /* content: [Furbolg] Hurry, $n. Vark awaits you. */
UPDATE db_script_string SET content_loc1='[펄볼그어] 감사합니다, $n!' WHERE entry=2000000680; /* content: [Furbolg] Thank you, $n! */
UPDATE db_script_string SET content_loc1='[펄볼그어] 오, 예언이 사실이로군요! 구해주셔서 감사합니다.' WHERE entry=2000000681; /* content: [Furbolg] The prophecy is true! */
UPDATE db_script_string SET content_loc1='[펄볼그어] 너울소나무 펄볼그는 당신의 용감한 행동을 잊지 못할 것입니다!' WHERE entry=2000000682; /* content: [Furbolg] The Stillpine furbolgs will not soon forget your bravery! */
UPDATE db_script_string SET content_loc1='[펄볼그어] 감사합니다. 너울소나무 요새에 남아 있는 이들이 당신을 영웅으로 환영할 겁니다!' WHERE entry=2000000683; /* content: [Furbolg] Those remaining at Stillpine Hold will welcome you as a hero! */
UPDATE db_script_string SET content_loc1='아다만트 님, 이 서판을 좀 보시고 룬 문자를 해독해 주시겠어요?' WHERE entry=2000000691; /* content: Adamant, could you please take a look at this tablet and try to decipher the runes? */
UPDATE db_script_string SET content_loc1='오, 물론입니다! 아름다우신 여사제님, 당신을 위해서라면 무엇이든지 합지요!' WHERE entry=2000000692; /* content: Of course! Anything for you, darling! */
UPDATE db_script_string SET content_loc1='자. 어디 서판을 좀 볼까요?' WHERE entry=2000000693; /* content: Alright, let me take a look at that tablet. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 드워프어로 중얼거리며 천천히 서판을 읽습니다.' WHERE entry=2000000694; /* content: %s slowly reads the tablet, mouthing the words in their native tongue. */
UPDATE db_script_string SET content_loc1='나가 장군! 오, 이런...' WHERE entry=2000000695; /* content: Naga warlord! Oh dear... */
UPDATE db_script_string SET content_loc1='아름다우신 여사제님, 제가 말씀드릴 내용이 심기를 불편하게 해드릴지도 모르겠군요. 이 서판은 나가의 통신 수단입니다. 나가의 지도자인 장군 스리스티즈가 부하들에게 섬의 나머지 지역을 무력으로 점령하라고 명령한 내용이 담겨 있습니다.' WHERE entry=2000000696; /* content: Well, you aren\'t going to like what I have to tell you, young missy. This tablet is a naga communication. Their leader, Warlord Sriss\'tiz, has ordered his naga to take the rest of the island by force. */
UPDATE db_script_string SET content_loc1='그리고 나즈자타에서 나가 증원군이 온 것 같군요!' WHERE entry=2000000697; /* content: And it looks like he\'s got reinforcements comin\' from Nazjatar! */
UPDATE db_script_string SET content_loc1='뭔가 손을 써야 합니다!' WHERE entry=2000000698; /* content: We\'ve got to do something about this! */
UPDATE db_script_string SET content_loc1='고맙습니다, 아다만트씨. 이 일에 딱 맞는 사람을 알고 있어요.' WHERE entry=2000000699; /* content: Thank you, Adamant. I think I know just the person for the job. */
UPDATE db_script_string SET content_loc1='당신들은 우편물을 확인도 안 합니까?' WHERE entry=2000000827; /* content: Don\'t you people ever check the mail? */
UPDATE db_script_string SET content_loc1='어떻게 저 혼자서 이 모든 편지를 배달하라는 겁니까?' WHERE entry=2000000828; /* content: How am I expected to deliver all of these messages? */
UPDATE db_script_string SET content_loc1='배치를 다시 받고 싶은 심정이로군요. 이 일은 정말 너무 힘들단 말입니다...' WHERE entry=2000000829; /* content: I need to be re-assigned. This job is pushing me over the edge... */
UPDATE db_script_string SET content_loc1='그는 자기가 굉장히 중요한 자라고 생각하지요. 언제나 저를 찬밥 취급하고 말입니다... 그에게 보여주고야 말 겁니다. 모두에게 보여줄 거라고요!' WHERE entry=2000000830; /* content: He thinks he\'s so damned important. Always pushing me around... I\'ll show him. I\'ll show all of them! */
UPDATE db_script_string SET content_loc1='버섯이 잔뜩 난 곳을 찾았으면 좋겠는데... 지금까지 살면서 그런 곳은 한 번도 보지 못했다오!' WHERE entry=2000000831; /* content: If only I could get back to the mushroom thicket. I have not seen such a mature cluster in my lifetime! */
UPDATE db_script_string SET content_loc1='불쌍한 도리우스... 망할 검은무쇠 놈들, 내 손에 걸리기만 해봐. 날 좀 도와...' WHERE entry=2000005000; /* content: Poor Dorius. If I ever get my hands on those Dark Irons, so help me... */
UPDATE db_script_string SET content_loc1='오푸스는 쿠에르고 골드 원해... 나 벌레 좋아해.' WHERE entry=2000005001; /* content: Opus wants some Cuergo\'s Gold... with worm. */
UPDATE db_script_string SET content_loc1='키블러는 조사를 받으러 식약청에 끌려갔어요.' WHERE entry=2000005003; /* content: Kibler is being investigated by G.E.T.A. */
UPDATE db_script_string SET content_loc1='보물 숨겨진 장소 비쥬가 알아.' WHERE entry=2000005004; /* content: Bijou knows where treasures are hidden. */
UPDATE db_script_string SET content_loc1='용이 오크를 지배해? 꽤액!' WHERE entry=2000005005; /* content: Dragons controlling orcs!? SQUAWK! */
UPDATE db_script_string SET content_loc1='보물? 키블러에게 물어봐! 꽤액!' WHERE entry=2000005007; /* content: Ask Kibler about the treasure! SQUAWK! */
UPDATE db_script_string SET content_loc1='꽤액!! 콜록... 콜록! 담배를 끊어야겠군!' WHERE entry=2000005008; /* content: SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE db_script_string SET content_loc1='잘했다, 제군들! 편히 쉬도록!' WHERE entry=2000005009; /* content: Well done, soldiers! At ease! */
UPDATE db_script_string SET content_loc1='저그 저그! 남을 돕는다는 건 정말 행복한 일 같아요!' WHERE entry=2000005010; /* content: Zug zug! Happy to help! */
UPDATE db_script_string SET content_loc1='알 수 없는 발굽 자국에, 검게 그을린 방패, 휘장은 떨어져 있고... 이 모든 현상을 어떻게 이해해야 하겠습니까?' WHERE entry=2000005012; /* content: Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this? */
UPDATE db_script_string SET content_loc1='드라짓에게 행운이 따라 랩터를 잡아줄 분이 불쑥 나타날 것 같진 않네요. 벌써 보상금을 두 번이나 올렸던 터라 하는 말이에요...' WHERE entry=2000005013; /* content: I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice... */
UPDATE db_script_string SET content_loc1='그래도 브록에게 맞는 집 여기밖에 없다! 고블린은 집 너무 작게 만든다!!' WHERE entry=2000005014; /* content: But this the only building that fit Brogg! Goblins make buildings too small! */
UPDATE db_script_string SET content_loc1='이 얘기는 이미 했다고 생각하는데, 브록. 이 건물 안에서 지낼 수는 없어. 너를 재울 수도 있지만, 그러면 다른 사람들은 아무도 못 잔다고!' WHERE entry=2000005015; /* content: I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else! */
UPDATE db_script_string SET content_loc1='그래, 여기서 지내도 좋다고 우리가 그랬는데, 하지만 이 건물은 우리 본부라고! 우리 작전 설명서와 계획서가 여기 전부 있단 말이야!' WHERE entry=2000005016; /* content: Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here! */
UPDATE db_script_string SET content_loc1='오우거가 너무 큰 거라고 말하고 싶어! 너를 설득해서 당장 나가게 할 수 없다는 건 아는데, 그렇다고 영원히 이대로 머물 수 있을 거라고는 생각하지 말라고!' WHERE entry=2000005017; /* content: I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent! */
UPDATE db_script_string SET content_loc1='물러서 계시는 게 좋을 겁니다. 물고기를 손질하느라 더러운 게 튈 수도 있으니까요.' WHERE entry=2000005019; /* content: You might wanna stand back. Fish guttin\' is a dirty job. */
UPDATE db_script_string SET content_loc1='자네가 긍지를 갖고 테라모어를 지키는 걸 보니 기쁘군, 친구.' WHERE entry=2000005020; /* content: It\'s good to see you defending Theramore with pride, friend. */
UPDATE db_script_string SET content_loc1='비번일 때 함께 여관에 가세. 내가 한잔 살 테니. 좋았던 옛날 얘기나 나눠 보세나.' WHERE entry=2000005021; /* content: When you\'re off duty, let\'s go to the inn. I\'ll buy a round and we can reminisce about the good old days. */
UPDATE db_script_string SET content_loc1='개구리가 달아나려 해요!' WHERE entry=2000005024; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc1='와서 나의 예언을 들으라. 불확실한 미래가 수정 거울처럼 분명해지리라.' WHERE entry=2000005026; /* content: Come speak with me, and what once was cloudy shall become crystal clear. */
UPDATE db_script_string SET content_loc1='내일 장래가 유망한 우리 어린 용들의 훈련이 시작되니 개껌... 아니 용껌은 꼭 지참하도록.' WHERE entry=2000005028; /* content: Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys. */
UPDATE db_script_string SET content_loc1='난 저 밑에 있는 세계에서 왔습니다... 고통과 질병에 남녀차별이 없는 평등한 곳이죠.' WHERE entry=2000005031; /* content: I come from the land down under... where women plague and men sunder. */
UPDATE db_script_string SET content_loc1='개구리가 달아나려 해요!' WHERE entry=2000005035; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc1='놈의 목에 현상금이 걸렸으니 그 버림받은 자를 사냥하러 가야 할지도 모르겠소.' WHERE entry=2000005037; /* content: I might just have to go hunting for that Wretched beast now that there\'s a bounty on his head. */
UPDATE db_script_string SET content_loc1='근무가 끝나면 바로 현상금 사냥을 시작할 생각입니다.' WHERE entry=2000005046; /* content: I\'m up to looking into that bounty after this shift. */
UPDATE db_script_string SET content_loc1='즐거운 시간 보내고 계신가요?' WHERE entry=2000005048; /* content: Having a good time? */
UPDATE db_script_string SET content_loc1='황천으로부터 또 다른 수치가 탐지되었습니다.' WHERE entry=2000005049; /* content: I have another reading from the nether. */
UPDATE db_script_string SET content_loc1='대단한 가즈로 님!' WHERE entry=2000005051; /* content: Great Gazlowe! */
UPDATE db_script_string SET content_loc1='삐!' WHERE entry=2000005053; /* content: Bip! */
UPDATE db_script_string SET content_loc1='삐!' WHERE entry=2000005054; /* content: Bip! */
UPDATE db_script_string SET content_loc1='삐!' WHERE entry=2000005055; /* content: Bip! */
UPDATE db_script_string SET content_loc1='울보래요! 울보래요!' WHERE entry=2000005057; /* content: Crybaby! Crybaby! */
UPDATE db_script_string SET content_loc1='울보가 인형 달라고 운대요!' WHERE entry=2000005058; /* content: Baby wants her dolly! */
UPDATE db_script_string SET content_loc1='네 인형이 수영도 할 수 있을지 궁금한걸!' WHERE entry=2000005059; /* content: I wonder if your dolly can swim! */
UPDATE db_script_string SET content_loc1='하하! 타미는 나한테 있지롱!' WHERE entry=2000005060; /* content: Ha ha! I have Betsy! */
UPDATE db_script_string SET content_loc1='네 인형 내가 갖고 있지롱! 케케!' WHERE entry=2000005061; /* content: I have your dolly! Nyah nyah! */
UPDATE db_script_string SET content_loc1='타미를 아프게 하지마!' WHERE entry=2000005063; /* content: Don\'t hurt Betsy, you meanie! */
UPDATE db_script_string SET content_loc1='길 건너에 있는 블러드 엘프들이 내가 첩자라고 오해하지 말아야 할 텐데!' WHERE entry=2000005064; /* content: I hope those blood elves across the way don\'t think that I\'m spying on them! */
UPDATE db_script_string SET content_loc1='이것들 봐라. 땅속에 묻히지만 않았지 완전히 죽은 녀석들 같군. 죽을 힘을 다해서 해 보란 말이야!' WHERE entry=2000005069; /* content: You\'re dead, not buried. Now show me your best! */
UPDATE db_script_string SET content_loc1='좋아, 말라깽이 친구들. 얼마나 잘 배웠는지 한번 볼까? 내가 멈추라고 할 때까지 계속 공격하도록.' WHERE entry=2000005070; /* content: Alright you sorry sacks of bones. Let\'s see what you\'ve got. Strike your opponent, and don\'t stop till I say so. */
UPDATE db_script_string SET content_loc1='에드워드. 타일러. 첫 번째 시험을 준비하도록.' WHERE entry=2000005071; /* content: Edward. Tyler. Prepare for your first challenge. */
UPDATE db_script_string SET content_loc1='리스타, 포로를 소환하도록!' WHERE entry=2000005072; /* content: Lysta, summon in the captives. */
UPDATE db_script_string SET content_loc1='리스타, 언데드 포로들을 불러내라.' WHERE entry=2000005074; /* content: Lysta, summon in undead captives. */
UPDATE db_script_string SET content_loc1='리스타, 누더기골렘을 데려오너라!' WHERE entry=2000005076; /* content: Lysta, summon forth... the abomination! */
UPDATE db_script_string SET content_loc1='에드워드, 타일러. 잘했다. 훈련 성과가 꽤 좋군. 얼마 후에 자네들의 기질을 다시 한번 시험해 볼 테니 준비하고 있도록.' WHERE entry=2000005077; /* content: Well done Edward and Tyler. You are progressing along in your training quite nicely. We shall test your mettle again soon. */
UPDATE db_script_string SET content_loc1='드럴은 아직 풀어 주지 않았소? 그가 어디에 갇혀 있는지는 나도 잘 모르오.' WHERE entry=2000005078; /* content: Have you freed Drull yet? I don\'t know where he\'s being held. */
UPDATE db_script_string SET content_loc1='난 당신의 임무에 걸림돌이 될 지도 모르오. 난 저 분홍빛 인간들에게 잡히진 않을 것이니 걱정하지 말고 어서 가시오!' WHERE entry=2000005079; /* content: I will only slow you down, but no pink-skinned humans will keep me from freedom! */
UPDATE db_script_string SET content_loc1='%s|1이;가; 부품 상자를 바닥에 내려놓습니다.' WHERE entry=2000005080; /* content: %s places the crate of parts on the ground. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 부품을 집어 주머니에 넣습니다...' WHERE entry=2000005081; /* content: %s grabs a part and puts it in his pocket... */
UPDATE db_script_string SET content_loc1='그래, 이거면 될 거야...' WHERE entry=2000005082; /* content: There, that should do it... */
UPDATE db_script_string SET content_loc1='내가 도와줄게요.' WHERE entry=2000005085; /* content: Let me help you with those. */
UPDATE db_script_string SET content_loc1='이걸 마시세요. 한결 나아질 거예요.' WHERE entry=2000005086; /* content: Drink this, it will help. */
UPDATE db_script_string SET content_loc1='곧 다 나을 거예요.' WHERE entry=2000005087; /* content: You\'re going to be just fine. */
UPDATE db_script_string SET content_loc1='온몸으로 나의 힘을 느껴라! 나의 힘에 도취하라! 호드의 영광을 위해 싸우라!' WHERE entry=2000005091; /* content: Be bathed in my power! Drink in my might! Battle for the glory of the Horde! */
UPDATE db_script_string SET content_loc1='땅문서는 내 겁니다, 형님! 내 앞길을 가로막지 못하도록 곧 영원히 제거해 드리지요!' WHERE entry=2000005092; /* content: The deeds are mine, brother! Soon you shall be out of my way for good! */
UPDATE db_script_string SET content_loc1='자, 저를 따라 오세요.' WHERE entry=2000005094; /* content: Please, follow me. */
UPDATE db_script_string SET content_loc1='아직 확실하게는 모르겠지만 이 온천에는 뭔가 이상한 점이 있어요...' WHERE entry=2000005095; /* content: I haven\'t really figured out what it is, but there\'s something strange about the hot springs... */
UPDATE db_script_string SET content_loc1='%s|1이;가; 얕은 물웅덩이 속으로 칼을 던집니다.' WHERE entry=2000005096; /* content: %s tosses the sword into the shallow pool. */
UPDATE db_script_string SET content_loc1='이 온천수에 뭔가를 넣었다가 꺼내면 성능이 엄청나게 향상된다는 걸 최근에 알아냈어요.' WHERE entry=2000005097; /* content: I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it. */
UPDATE db_script_string SET content_loc1='이유야 어쨌건 간에 아주 효과가 좋더라고요!' WHERE entry=2000005098; /* content: Well, whatever it is, it works quite well! */
UPDATE db_script_string SET content_loc1='그는 때때로 까마귀로 변신할 수도 있다고 하더라.' WHERE entry=2000005109; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc1='그는 때때로 까마귀로 변신할 수도 있다고 하더라.' WHERE entry=2000005110; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc1='그러고는 토끼가 그의 손가락을 물어뜯어 버렸어... 정말이라니까.' WHERE entry=2000005111; /* content: And then the rabbit just bit his head off... I swear. */
UPDATE db_script_string SET content_loc1='으... 물고기가 아니잖아!' WHERE entry=2000005116; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc1='신발에 벌레 내장이 묻었어.' WHERE entry=2000005117; /* content: I got worm guts on my shoes. */
UPDATE db_script_string SET content_loc1='뭔가 보인 것 같아.' WHERE entry=2000005118; /* content: I think i see something. */
UPDATE db_script_string SET content_loc1='으... 물고기가 아니잖아!' WHERE entry=2000005119; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc1='뭔가 보인 것 같아.' WHERE entry=2000005120; /* content: I think i see something. */
UPDATE db_script_string SET content_loc1='물고기였으면 좋았을 텐데!' WHERE entry=2000005121; /* content: I hope that was a fish! */
UPDATE db_script_string SET content_loc1='상상이 되니?' WHERE entry=2000005123; /* content: Can you imagine? */
UPDATE db_script_string SET content_loc1='정말요?' WHERE entry=2000005124; /* content: Really? */
UPDATE db_script_string SET content_loc1='우와!' WHERE entry=2000005125; /* content: Wow. */
UPDATE db_script_string SET content_loc1='우리 아빠가 그건 그냥 지어낸 얘기라고 하셨어.' WHERE entry=2000005126; /* content: My father says that\'s just a story. */
UPDATE db_script_string SET content_loc1='정말요?' WHERE entry=2000005127; /* content: Really? */
UPDATE db_script_string SET content_loc1='우와!' WHERE entry=2000005128; /* content: Wow. */
UPDATE db_script_string SET content_loc1='멋지다.' WHERE entry=2000005129; /* content: That\'s neat. */
UPDATE db_script_string SET content_loc1='우와!' WHERE entry=2000005130; /* content: Wow. */
UPDATE db_script_string SET content_loc1='정말요?' WHERE entry=2000005131; /* content: Really? */
UPDATE db_script_string SET content_loc1='모두 정신 바짝 차려! 여기서 작전을 수행해야 한다!' WHERE entry=2000005132; /* content: Look alive, dogs! We got an operation to run here! */
UPDATE db_script_string SET content_loc1='즐거운 시간 보내고 계신가요?' WHERE entry=2000005133; /* content: Having a good time? */
UPDATE db_script_string SET content_loc1='이곳 빛의 대성당은 스톰윈드의 영혼 계몽의 중심이랍니다.' WHERE entry=2000005134; /* content: Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind. */
UPDATE db_script_string SET content_loc1='네, 그래요. 성기사와 사제들은 모두 대성당 안에서 기술을 익히고 위대한 진리를 연구하는 거랍니다.' WHERE entry=2000005135; /* content: Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral. */
UPDATE db_script_string SET content_loc1='여러분, 이곳이 스톰윈드 왕궁이랍니다. 1차 대전쟁 당시 호드에 의해 파괴된 스톰윈드 성의 폐허 위에 건설된 것이죠.' WHERE entry=2000005137; /* content: Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War. */
UPDATE db_script_string SET content_loc1='호드를 물리친 후, 인간들은 이곳으로 돌아와서 우리의 생존을 기념해 과거의 위대한 도시를 재건하기 시작했어요.' WHERE entry=2000005138; /* content: When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival. */
UPDATE db_script_string SET content_loc1='좋아요, 음... 이제 두 차례의 대전쟁 당시 큰 공을 세웠던 영웅들을 기념하기 위해 만든 기념물을 보러 영웅의 계곡으로 가 보겠어요. 자, 선생님을 따라오세요.' WHERE entry=2000005139; /* content: Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me. */
UPDATE db_script_string SET content_loc1='여러분, 놀랍죠? 도시로 들어가는 이는 모두 이 땅의 위대한 영웅들이 위에서 지켜보고 있는 이 아래를 지나가야만 해요.' WHERE entry=2000005140; /* content: Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands. */
UPDATE db_script_string SET content_loc1='여러분, 잠시 쉬죠, 학교로 돌아가면 각자 이 전설적인 인물 중 한 명에 대해 발표해 보도록 하겠어요.' WHERE entry=2000005141; /* content: Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people. */
UPDATE db_script_string SET content_loc1='자, 마법사 지구와 빛의 대성당으로 가기 전에 다시 한번 천천히 잘 봐 두도록 하세요.' WHERE entry=2000005142; /* content: Now, take another long look before we make our way to the Holy District and the great Cathedral of Light. */
UPDATE db_script_string SET content_loc1='호수에 가까이 가지 마세요! 유령이 나온대요!' WHERE entry=2000005147; /* content: Don\'t go close to the lake! It\'s haunted! */
UPDATE db_script_string SET content_loc1='12개의 초점 중심을 만들면 마법의 힘이 보다 충만하게 되어 안정성을 충분히 확보할 수 있을 거예요.' WHERE entry=2000005148; /* content: Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability. */
UPDATE db_script_string SET content_loc1='하지만 생성되는 힘이 소실될 수도 있고 몇 주 동안 두통을 일으킬 만한 힘의 유입을 유발할 수도 있어요.' WHERE entry=2000005151; /* content: The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks. */
UPDATE db_script_string SET content_loc1='같이 주문을 시도할 사람 20명만 구하면 성공할 것 같군요.' WHERE entry=2000005156; /* content: I suppose that could work, if we had twenty people to cast it with. */
UPDATE db_script_string SET content_loc1='그러다 그에 따른 진동수 변경으로 흐름에 마법적인 영향을 미치면 어쩌죠?' WHERE entry=2000005157; /* content: But what if the resulting frequency shift were to send magical feedback up the flows? */
UPDATE db_script_string SET content_loc1='그건 마법 초점의 균형을 깨뜨려 공중에 역진동을 일으킬 거예요.' WHERE entry=2000005159; /* content: That will unbalance the magical focus, though, and cause a reverse vibration in the ether. */
UPDATE db_script_string SET content_loc1='배열을 변경해서 유입되는 흐름의 변동을 보완할 수 있지 않을까요?' WHERE entry=2000005161; /* content: Why can\'t we just shift the array to compensate for the variance in the flux? */
UPDATE db_script_string SET content_loc1='아니라고 생각해요. 다시 폭발하는 일은 없을 거예요.' WHERE entry=2000005163; /* content: I think not, I don\'t need to be blown up again. */
UPDATE db_script_string SET content_loc1='매기노르의 이론에 의하면 양의 에너지 교류 흐름을 왜곡시키면 실제로 보다 안정된 흐름을 얻을 수 있다고 해요.' WHERE entry=2000005164; /* content: Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow. */
UPDATE db_script_string SET content_loc1='선생님, 성기사 분들이 정말로 여기서 훈련을 하나요?' WHERE entry=2000005167; /* content: Is it true that the paladins train here? */
UPDATE db_script_string SET content_loc1='이걸 왜 배워야 하나요?' WHERE entry=2000005168; /* content: Why do we have to learn this stuff anyway? */
UPDATE db_script_string SET content_loc1='근본 요소의 흐름을 역전시킬 수 있다면 극성을 바꿀 수 있을 거예요.' WHERE entry=2000005169; /* content: If we reverse the Essence flows perhaps we can alter the polarity. */
UPDATE db_script_string SET content_loc1='타이리안 형태로 3개의 초점을 사용하는 게 어떨까요? 그러면 문제가 해결될 것 같은데...' WHERE entry=2000005170; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc1='올바른 과정을 따르면 괜찮을 거예요. 다만 시작하기 전에 신중하게 연구해 봐야겠어요.' WHERE entry=2000005172; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc1='그렇지만 힘의 핵심을 정확하게 고정하면 성공할 것 같군요.' WHERE entry=2000005175; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc1='타이리안 형태로 3개의 초점을 사용하는 게 어떨까요? 그러면 문제가 해결될 것 같은데...' WHERE entry=2000005176; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc1='올바른 과정을 따르면 괜찮을 거예요. 다만 시작하기 전에 신중하게 연구해 봐야겠어요.' WHERE entry=2000005177; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc1='그렇지만 힘의 핵심을 정확하게 고정하면 성공할 것 같군요.' WHERE entry=2000005178; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc1='반가워요, 차리스. 목록은 여기 있어요. 여기 적힌 걸 모두 구해 준다면 고맙겠는데... 특히 마지막 재료가 구하기 쉽지 않을 거 같아요.' WHERE entry=2000005180; /* content: Hello, Charys. I have my list, could you get me all of that, especially the last ingredient. */
UPDATE db_script_string SET content_loc1='고마워요, 차리스. 페이지, 이리 오렴, 사랑스러운 내 딸.' WHERE entry=2000005182; /* content: Thanks, Charys. C\'mon Paige, sweetie. */
UPDATE db_script_string SET content_loc1='엄마? 삑삑이 키워도 되나요?' WHERE entry=2000005183; /* content: Mommy? Can I pet Fizzles? */
UPDATE db_script_string SET content_loc1='마법 공부로 지치셨다고요? 그럴 때 고독한 은둔자 선술집에 가서 정신이 맑아지는 음료수 한잔 하시기 바랍니다!' WHERE entry=2000005185; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc1='스톰윈드 최고의 술이 있는 곳!' WHERE entry=2000005186; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc1='고독한 은둔자 선술집으로 오십시오. 그곳에서는 모두 단골손님으로 대접한답니다!' WHERE entry=2000005187; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc1='기분이 우울하신가요? 그렇다면 고독한 은둔자 선술집으로 오셔서 즐거운 시간을 보내십시오!' WHERE entry=2000005188; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc1='스톰윈드 최고의 술이 있는 곳!' WHERE entry=2000005189; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc1='마법 공부로 지치셨다고요? 그럴 때 고독한 은둔자 선술집에 가서 정신이 맑아지는 음료수 한잔 하시기 바랍니다!' WHERE entry=2000005190; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc1='고독한 은둔자 선술집으로 오십시오. 그곳에서는 모두 단골손님으로 대접한답니다!' WHERE entry=2000005192; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc1='고독한 은둔자 선술집에서 공짜 술을 제공합니다!' WHERE entry=2000005193; /* content: Free drinks at the Blue Recluse! */
UPDATE db_script_string SET content_loc1='기분이 우울하신가요? 그렇다면 고독한 은둔자 선술집으로 오셔서 즐거운 시간을 보내십시오!' WHERE entry=2000005194; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc1='마법 공부로 지치셨다고요? 그럴 때 고독한 은둔자 선술집에 가서 정신이 맑아지는 음료수 한잔 하시기 바랍니다!' WHERE entry=2000005195; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc1='스톰윈드 최고의 술이 있는 곳!' WHERE entry=2000005196; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc1='고독한 은둔자 선술집으로 오십시오. 그곳에서는 모두 단골손님으로 대접한답니다!' WHERE entry=2000005198; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc1='스톰윈드 최고의 술이 있는 곳!' WHERE entry=2000005199; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc1='돌격!' WHERE entry=2000005200; /* content: Charge! */
UPDATE db_script_string SET content_loc1='돌격!' WHERE entry=2000005201; /* content: Charge! */
UPDATE db_script_string SET content_loc1='아, 나의 소중한 아미나! 다시 만나서 얼마나 기쁜지 모르겠군.' WHERE entry=2000005202; /* content: Ahh, my precious Ameenah! How wonderful to see you again. */
UPDATE db_script_string SET content_loc1='흠, 내가 그런다고 그렇게 꺼려하지는 말아!' WHERE entry=2000005204; /* content: Hmm, don\'t mind if I do! */
UPDATE db_script_string SET content_loc1='조사하는 중입니다, 와플프라이 씨. 뭐 다른 할 일 없으신가요? 새로운 기계 장치를 시험해 봐야 한다든가...' WHERE entry=2000005205; /* content: It\'s coming along, Wafflefry. Haven\'t you got a product demonstration to do or something? */
UPDATE db_script_string SET content_loc1='놀랍기 그지없는 얼룩 제거용 정전기학 광선총을 동네에서 제일 먼저 소유하는 기쁨을 누리시죠!' WHERE entry=2000005206; /* content: Be the first on your block to own the incredible Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc1='포도주 흘린 자국, 풀물, 심지어 애완동물 배설물 자국도 얼룩 제거용 정전기학 광선총 앞에선 상대가 안 되죠!' WHERE entry=2000005208; /* content: Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc1='자, 망설이지 마세요! 지금 당장 주문하시면 제가 만든 와플제 초강력 다리미를 끼워드리죠!' WHERE entry=2000005209; /* content: Don\'t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge! */
UPDATE db_script_string SET content_loc1='난 멈추지 않아. 절대로...' WHERE entry=2000005210; /* content: I\'ll never stop. Never... */
UPDATE db_script_string SET content_loc1='여기, 누가 이 개구리 좀 잡아 주세요!' WHERE entry=2000005211; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc1='이보시오, 요새 밥은 제대로 먹고 다니시나요?' WHERE entry=2000005214; /* content: Hey! Do you like the sauce? The sauce is good, no? */
UPDATE db_script_string SET content_loc1='무슨 인도자라고? 아, 파멸의 인도자 말인가요? 난 그런 거 모릅니다. 뭡니까? 성가시게 하지 마세요!' WHERE entry=2000005215; /* content: The what-bringer? Oh, ASHbringer? Never heard of it... What? Stop bothering me! */
UPDATE db_script_string SET content_loc1='여기, 누가 이 개구리 좀 잡아 주세요!' WHERE entry=2000005218; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc1='이제 텔라아르의 평화와 안전을 지키는 데 필요한 도움을 얻을 수 있겠군!' WHERE entry=2000005219; /* content: That should get Telaar the assistance it needs! */
UPDATE db_script_string SET content_loc1='간식거리와 기념품 사시는 것도 잊지 마세요!' WHERE entry=2000005223; /* content: Don\'t forget to buy refreshments and souvenirs! */
UPDATE db_script_string SET content_loc1='아, 그 노란 알약을 먹었어야 하는 건데.' WHERE entry=2000005228; /* content: I should have taken the translucent pill. */
UPDATE db_script_string SET content_loc1='보수는 쥐꼬리만큼 받으면서 이런 지저분한 일을 해야 하다니!' WHERE entry=2000005229; /* content: I don\'t get paid enough for this bull excrement! */
UPDATE db_script_string SET content_loc1='운명을 놓고 우물쭈물할 시간이 있는가? 그만큼 불확실한 미래가 늘어날 뿐인데...' WHERE entry=2000005232; /* content: The longer you wait, the less future you have for me to foretell. */
UPDATE db_script_string SET content_loc1='이렇게 부담스러운 세금은 도저히 용납 못 하겠습니다! 동부 왕국 연금으로 안정된 노후 대비라고요? 흥!' WHERE entry=2000005234; /* content: I can\'t take these taxes! F.I.C.A. me? F.I.C.A. YOU! */
UPDATE db_script_string SET content_loc1='잠시 후 페리 가트너가 벌이는 희극을 맘껏 즐겨주십시오!' WHERE entry=2000005302; /* content: Check out the comedy stylings of Perry Gatner in just a few minutes! */
UPDATE db_script_string SET content_loc1='배꼽이 빠져라 웃고 싶은 분은 세상의 끝 선술집으로 오십시오!' WHERE entry=2000005303; /* content: If you are ready to laugh, head over to the World\'s End Tavern! */
UPDATE db_script_string SET content_loc1='지금, 샤트라스에 타우렌 족장들을 모셨습니다! 그들이 매시간 정각에 세상의 끝 선술집에서 펼치는 멋진 공연에 여러분 모두를 초대합니다!' WHERE entry=2000005304; /* content: Now, in Shattrath City: The Tauren Chieftains! Playing in the World\'s End Tavern at the top of the hour! */
UPDATE db_script_string SET content_loc1='브록 여기서 지내도 된다고 네가 말했다! 돌망치 일족 땅 다시 찾게 도와준다고 너 브록한테 약속했다!' WHERE entry=2000005306; /* content: You said Brogg could stay here! You promised Brogg you\'d help regain Stonemaul clan mound! */
UPDATE db_script_string SET content_loc1='흐음... 낚싯바늘을 어디다 뒀더라? 아, 저기 있네.' WHERE entry=2000005307; /* content: Hmmm... Where is my fishing hook? Oh, there it is. */
UPDATE db_script_string SET content_loc1='고기들이 좀 무는지 어디 한번 볼까.' WHERE entry=2000005308; /* content: Let\'s see if the fish are biting. */
UPDATE db_script_string SET content_loc1='흐음... 더 좋은 미끼가 필요할 것 같아. 아빠 짐마차에 좀 다녀와야겠어.' WHERE entry=2000005309; /* content: Hmmm... I think I need better bait. I\'ll check my father\'s wagon. */
UPDATE db_script_string SET content_loc1='가시멧돼지 고기야! 좋았어! 물고기들은 돼지고기라면 아주 환장하지.' WHERE entry=2000005310; /* content: Quillboar scraps! These should do the trick. Fish love Quillboar. */
UPDATE db_script_string SET content_loc1='한 마리 잡았다! 혹시 경비병들이 배고플지도 몰라. 가자, 검둥아!' WHERE entry=2000005311; /* content: Caught one! I\'ll see if any of the guards are hungry. Come on Fang! */
UPDATE db_script_string SET content_loc1='물고기 한 마리 잡았는데 혹시 배고프면...' WHERE entry=2000005312; /* content: I caught a fish if you are hungry... */
UPDATE db_script_string SET content_loc1='월척이네! 호드 어린이의 명예를 드높이는 꼬마로군! 고맙다!' WHERE entry=2000005313; /* content: A nice catch it is at that! You bring honor to the Horde boy, We thank you! */
UPDATE db_script_string SET content_loc1='뭐 좀 더 드실래요?' WHERE entry=2000005314; /* content: Would you like something more to eat sir? */
UPDATE db_script_string SET content_loc1='빵 더 가져와!' WHERE entry=2000005315; /* content: More bread boy! */
UPDATE db_script_string SET content_loc1='알았어요.' WHERE entry=2000005316; /* content: Right away sir. */
UPDATE db_script_string SET content_loc1='여기 빵 가지고 왔어요.' WHERE entry=2000005317; /* content: Here is your bread sir. */
UPDATE db_script_string SET content_loc1='이야... 좋아, 좋아. 그럼 가봐!' WHERE entry=2000005318; /* content: Aaahh... Very good. Now scat! */
UPDATE db_script_string SET content_loc1='알았어요.' WHERE entry=2000005319; /* content: As you wish sir. */
UPDATE db_script_string SET content_loc1='아빠, 목걸이 만들 돌멩이 모으러 나가도 돼요?' WHERE entry=2000005320; /* content: Can I go collect more rocks for my necklace, Papa? */
UPDATE db_script_string SET content_loc1='다부! 조심할게요, 아빠!' WHERE entry=2000005322; /* content: Dabu! I will be careful Papa! */
UPDATE db_script_string SET content_loc1='와아! 이 돌은 모양도 색깔도 정말 예쁘네. 이런 게 더 있나 어디 한번 볼까...' WHERE entry=2000005323; /* content: Ooohh... This rock is nice and colorful. Let\'s see if I can find more like it... */
UPDATE db_script_string SET content_loc1='흠... 저 돌은 예쁜데 너무 작아.' WHERE entry=2000005324; /* content: Hmm... That rock is nice, but too small. */
UPDATE db_script_string SET content_loc1='이 돌은 창 만드는 친구한테 줘야겠다! 아주 날카로운 게... 그루크가 진짜 좋아 할거야.' WHERE entry=2000005326; /* content: I bet my friend Gruk would like this rock for the spear he is making! It\'s very sharp... I hope he likes it. */
UPDATE db_script_string SET content_loc1='뭐... 이 정도면 목걸이 하나는 만들고도 남겠지. 얼른 집에 가야겠다.' WHERE entry=2000005327; /* content: There... That should be enough rocks to make a necklace. I should probably get home now anyway. */
UPDATE db_script_string SET content_loc1='집들이 선물 가져왔네, 자를.' WHERE entry=2000005328; /* content: I brought you a housewarming gift, Jarl. */
UPDATE db_script_string SET content_loc1='어서 열어보게. 맘에 들 것 같은데...' WHERE entry=2000005329; /* content: Go on, open it. I think you\'ll like it. */
UPDATE db_script_string SET content_loc1='자를?' WHERE entry=2000005330; /* content: Jarl? */
UPDATE db_script_string SET content_loc1='먹을 게 아니면, 받고 싶지 않네.' WHERE entry=2000005331; /* content: Unless it\'s something I can eat, I don\'t want it. */
UPDATE db_script_string SET content_loc1='자를, 내가 왔을 때부터 여태까지 계속 정신을 못 차리고 있잖아. 무슨 일이라도 있나?' WHERE entry=2000005332; /* content: Jarl, you haven\'t been yourself ever since I arrived. What\'s going on? */
UPDATE db_script_string SET content_loc1='아무 일도 없네. 이 개구리 다리 스튜 만드는 거나 도와주겠나?' WHERE entry=2000005333; /* content: Nothing. Wanna help me whip up some frog leg stew? */
UPDATE db_script_string SET content_loc1='여기까지 온 건 자넬 보고 싶어서네, 자를! 그랬더니 이런 알 수 없는 곳에 텅텅 빈 오두막집에서 개구리 타령이나 하며 살고 있다니! 절망 그 자체로군!' WHERE entry=2000005334; /* content: I came out here to visit you, Jarl! And I find you living in an empty cabin in the middle of nowhere, babbling about frogs? You\'re hopeless! */
UPDATE db_script_string SET content_loc1='그래서 더 연구를 해보려고요... 또 제 도움이 필요하시면 이곳으로 언제든지 절 찾아오세요.' WHERE entry=2000005335; /* content: And I am determined to find out more... So if you need my help again, you know where I\'ll be. */
UPDATE db_script_string SET content_loc1='아나야? 내가 지금 꿈을 꾸고 있는 건가? 정말 당신이오?' WHERE entry=2000005336; /* content: Anaya...? Do my eyes deceive me? Is it really you? */
UPDATE db_script_string SET content_loc1='우리에겐 지나간 세월이 너무 가혹했던 것 같아요. 내 사랑, 결국 이렇게 당신과 다시 마주하게 되었군요.' WHERE entry=2000005337; /* content: The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited. */
UPDATE db_script_string SET content_loc1='천 년을 떨어져 지내고 난 후에도 이 정도밖에 허락하지 않다니... 가혹한 운명이 너무나 원망스럽구려.' WHERE entry=2000005338; /* content: That the fates should be so cruel as to permit us only this after a thousand years apart... */
UPDATE db_script_string SET content_loc1='날 미워하는 거요, 내 사랑? 그 고통스러운 불행의 속박에서 당신의 영혼을 풀어주기 위해서 다른 이의 손을 빌려 당신을 해칠 수밖에 없었던 나를...' WHERE entry=2000005339; /* content: Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage. */
UPDATE db_script_string SET content_loc1='나 때문에 마음 아파하지 마세요, 내 사랑. 당신은 나를 속박에서 자유롭게 해주었고... 이제 저는 당신을 더욱 깊게 사랑하게 되었어요.' WHERE entry=2000005340; /* content: Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more. */
UPDATE db_script_string SET content_loc1='슬프게도, 재회의 시간도 곧 끝나겠군요... 나를 이 세계에 묶고 있는 끈이 약해지고 있어요. 나를 먼 곳으로 데려 가려 하네요...' WHERE entry=2000005341; /* content: Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away... */
UPDATE db_script_string SET content_loc1='안 돼! 아나야... 아나야! 나를 떠나지 마시오! 제발...' WHERE entry=2000005342; /* content: No! Anaya... Anaya! Don\'t leave me! Please... */
UPDATE db_script_string SET content_loc1='잘 있어요, 세렐리안. 다시 만날 때까지...' WHERE entry=2000005343; /* content: Farewell, Cerellean, until we are joined once again... */
UPDATE db_script_string SET content_loc1='어떻게... 나더러 당신 없이 이 세상을 살아가란 말이오, 내 사랑...' WHERE entry=2000005345; /* content: How, my love? How will I find the strength to face the ages of the world without you by my side... */
UPDATE db_script_string SET content_loc1='인사드립니다, 게제 님! 하라사미드 구역에서 17건의 주문이 추가로 들어왔습니다. 예측하신 대로 벨다라이트 시장이 붕괴됐습니다.' WHERE entry=2000005362; /* content: Hail, Gezhe!  Seventeen more orders have been placed in the Hara\'samid Sector.  The markets of heavy veldarite have all but collapsed, as you predicted. */
UPDATE db_script_string SET content_loc1='헤라지 수출이 증가 추세입니다. 이미 세관원을 매수해 놨으니 며칠 안으로 밀수품이 도착할 겁니다.' WHERE entry=2000005363; /* content: Heraazi exports are on the rise, sir.  We\'ve already bribed the appropriate taxation officers and contraband will begin to arrive within days. */
UPDATE db_script_string SET content_loc1='놀랄 만한 내용은 하나도 없군. 제대로 된 소식을 가지고 오도록. 알겠나?' WHERE entry=2000005364; /* content: Nothing surprising there.  Come back with some real news, will you? */
UPDATE db_script_string SET content_loc1='예상한 대로군. 아주 좋아. 이만 가 보도록.' WHERE entry=2000005365; /* content: As expected.  Very well, dismissed. */
UPDATE db_script_string SET content_loc1='그럼 물러가도록 하겠습니다.' WHERE entry=2000005366; /* content: By your leave, sir. */
UPDATE db_script_string SET content_loc1='여기 온 걸 보니 악의 무리를 소환하여 부리는 법을 공부할 준비가 됐나 보군. 자네가 부를 수 있을 만한 가장 저급한 생물부터 시작하지. 자, 시작해 볼까?' WHERE entry=2000005367; /* content: If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. */
UPDATE db_script_string SET content_loc1='가장 소환하기 쉬운 생물은 임프라네. 자네도 이미 임프 정도는 소환할 줄 알겠지만, 빠진 것이 없도록 이놈부터 설명하겠네.' WHERE entry=2000005368; /* content: The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him. */
UPDATE db_script_string SET content_loc1='이 사악하고 작은 짐승이 바로 임프지. 작고 약해서 고기 방패처럼 거의 쓸모가 없어. 물론 공격력도 보잘것없고. 이 짐승은 파티를 지원하는 정도의 용도로 사용하는 게 가장 좋지.' WHERE entry=2000005369; /* content: This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. */
UPDATE db_script_string SET content_loc1='임프는 공부했으니 이제 다음 소환수를 소환해 보지. 다음은 공허방랑자라네.' WHERE entry=2000005370; /* content: Now that you have had a chance to study the imp, let us move on to the next minion you will be able to summon, the voidwalker. */
UPDATE db_script_string SET content_loc1='이 악마는 공허방랑자라고 알려져 있지. 힘과 맷집이 대단해서 방어용으로 이상적이야. 공허방랑자가 먼저 적을 공격하게 한 뒤, 녀석을 방패 삼아 자네의 주문이나 능력을 사용하게.' WHERE entry=2000005371; /* content: This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life. */
UPDATE db_script_string SET content_loc1='자, 한 번도 본 적이 없다면 잘 봐 두라고. 전장 안팎에서 모두 아주 유용한 녀석이니까 말이야. 다음은 남성들이라면 모두 기대하고 있을 서큐버스를 소환해 보지.' WHERE entry=2000005372; /* content: If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. */
UPDATE db_script_string SET content_loc1='좋아. 서큐버스는 남성 적들을 매혹시켜 교란을 유도할 수 있을 뿐만 아니라 상당한 타격도 입힐 수 있지. 하지만 방어력이 약해서 방패로는 거의 쓸모가 없어.' WHERE entry=2000005373; /* content: All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. */
UPDATE db_script_string SET content_loc1='열심히 공부하다 보면 언젠가 직접 소환할 수 있을 걸세. 하지만 지금은 우선 지옥사냥개로 넘어가 보지.' WHERE entry=2000005374; /* content: Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter. */
UPDATE db_script_string SET content_loc1='앞에 보이는 것이 지옥사냥개일세. 이 야수는 주문 잠금을 비롯한 여러 가지 능력을 타고났기 때문에, 마법을 사용하는 적을 상대하는 데 탁월하지.' WHERE entry=2000005375; /* content: What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. */
UPDATE db_script_string SET content_loc1='마법을 사용하는 모든 적들을 상대할 때는 이 무시무시한 짐승이 가장 유용할 거야. 이제 약간 다른 녀석을 살펴볼까? 자네의 여행을 도와주고 앞으로 여정을 훨씬 편하게 해줄 친구지. 자, 지옥마를 살펴보자고.' WHERE entry=2000005376; /* content: When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed. */
UPDATE db_script_string SET content_loc1='자, 이것으로 소환에 대한 수업은 모두 마치도록 하겠네. 곧 다음 수업이 시작될 테니, 복습하고 싶다면 여기 계속 머물러 있어도 좋네.' WHERE entry=2000005378; /* content: There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. */
UPDATE db_script_string SET content_loc1='휴! 내 행운의 모자가 여기 있었네. 사방을 뒤져도 없더니만.' WHERE entry=2000005379; /* content: Phew! There\'s my lucky hat. I\'ve been looking for it everywhere. */
UPDATE db_script_string SET content_loc1='검을 두고 나가다니 제정신이 아닌가 봅니다. 그런데 제가 검이 여기 있는 것을 봤다면 그냥 놔두고 갔을 리는 없는데...' WHERE entry=2000005380; /* content: I don\'t know what I was thinking, going out without my sword. I would\'ve put it on if I\'d seen it here... */
UPDATE db_script_string SET content_loc1='망토 없이 외출할 수는 없지. 이 안에 망토가 있으면 좋겠어...' WHERE entry=2000005381; /* content: I can\'t possibly go out without my cloak. I hope it\'s in here... */
UPDATE db_script_string SET content_loc1='여기 있었군! 마지막에 확인할 때만 해도 분명 여기 없었는데...' WHERE entry=2000005382; /* content: There it is! I could\'ve sworn it wasn\'t here last time I checked... */
UPDATE db_script_string SET content_loc1='저는 침대에서 재미있는 얘기를 읽어야 잠이 옵니다. 이제 편히 잠들 수 있겠네요.' WHERE entry=2000005383; /* content: I can\'t sleep without a good bedtime story. Now I\'m certain to rest well. */
UPDATE db_script_string SET content_loc1='사제가 무릎을 꿇고 조용히 기도합니다.' WHERE entry=2000005409; /* content: The priest kneels in silent prayer. */
UPDATE db_script_string SET content_loc1='성스러운 빛이여, 제게 힘을 주소서!' WHERE entry=2000005410; /* content: Light, give me strength. */
UPDATE db_script_string SET content_loc1='성스러운 빛이여, 타락한 이들을 거짓에서 진실로, 어둠에서 빛으로, 죽음에서 영생으로 이끌어 주소서.' WHERE entry=2000005411; /* content: Light, lead the fallen from untruth to truth, from darkness to Light and from death to immortality. */
UPDATE db_script_string SET content_loc1='안 돼애애애애!!!!' WHERE entry=2000005415; /* content: NOOOOO!!! */
UPDATE db_script_string SET content_loc1='동지들이여... 실망시켜서 미안합니다...' WHERE entry=2000005416; /* content: Friends... I\'ve failed you... */
UPDATE db_script_string SET content_loc1='아니오... 우리가 당신을 실망시켰소... 바로 우리가 말이오...' WHERE entry=2000005417; /* content: No my friend... we failed you... we failed you. */
UPDATE db_script_string SET content_loc1='%s|1이;가; 나가 깃발을 집어듭니다.' WHERE entry=2000005418; /* content: %s picks up the naga flag. */
UPDATE db_script_string SET content_loc1='무슨 일이라도 있습니까, 불똥 님? 모이라고 하신 이유가 뭡니까?' WHERE entry=2000005419; /* content: What\'s the big idea, Spark? Why\'d you call for this meeting? */
UPDATE db_script_string SET content_loc1='무슨 짓인가? 너 때문에 내 정체가 거의 드러날 뻔했잖아, 멍청한 녀석! 내가 분명 나침반하고 항해 지도를 안전한 곳에 두라고 하지 않았나. 바보도 쉽게 찾을 수 있는 뻥 뚫린 곳 말고!' WHERE entry=2000005420; /* content: What\'s the big idea? You nearly blew my cover, idiot! I told you to put the compass and navigation maps somewhere safe - not out in the open for any fool to discover. */
UPDATE db_script_string SET content_loc1='주인님께서는 엑소다르의 소재에 관한 정보를 지키려고 엄청난 노력을 하셨다. 너 때문에 내부 첩자가 발각될 뻔했을 뿐만 아니라 우리 계획도 전부 엉망이 될 뻔했다는 걸 아나?' WHERE entry=2000005421; /* content: The Master has gone to great lengths to secure information about the whereabouts of the Exodar. You could have blown the entire operation, including the cover of our spy on the inside. */
UPDATE db_script_string SET content_loc1='진정하십시오, 불똥 님! 모든 것이 제 통제 하에 있습니다. 우리는 그들 몰래 엑소다르에서 채굴을 할 것이고 불똥님과 저는 아주 큰 부자가 될 겁니다.' WHERE entry=2000005422; /* content: Relax, Spark! I have it all under control. We\'ll strip mine the Exodar right out from under \'em - making both you and I very, very rich in the process. */
UPDATE db_script_string SET content_loc1='진정하라고? 캘타스 님께서 그분께 실망을 안겨준 자들에게 어떻게 하시는지 알고나 하는 소린가, 기즐? 영원한 고통과 괴로움에 몸부림치는 거다... 이번 일을 망치면 알아서 해, 멍청한 고블린 녀석.' WHERE entry=2000005423; /* content: Relax? Do you know what Kael\'thas does to those that fail him, Geezle? Eternal suffering and pain... Do NOT screw this up, fool. */
UPDATE db_script_string SET content_loc1='우리 핏빛안개 척후병들이 우리 정보원의 위치를 파악했다. 그 멍청이 벨렌은 곧 무방비 상태가 될 것이다. 우리가 습격하기에 충분한 시간이지! 이제, 네놈을 없애 버리기 전에 눈앞에서 사라져라...' WHERE entry=2000005424; /* content: Our Bloodmyst scouts have located our contact. The fool, Velen, will soon leave himself open and defenseless -- long enough for us to strike! Now get out of my sight before I vaporize you... */
UPDATE db_script_string SET content_loc1='네, 알겠습니다. 다시는 이런 일이 없도록 하겠습니다...' WHERE entry=2000005425; /* content: Yes, sir. It won\'t happen again... */
UPDATE db_script_string SET content_loc1='정말 감사합니다!' WHERE entry=2000005544; /* content: You have my thanks! */
UPDATE db_script_string SET content_loc1='살아생전에는 나의 검 아키우스가 아주 쓸모 있었지. 하지만 비참했던 삶에서 자유로워진 지금은 아무런 필요가 없네.' WHERE entry=2000005546; /* content: My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer. */
UPDATE db_script_string SET content_loc1='내 딸에 대한 사랑과 추억은 절대 잊을 수 없을 것이야. 이젠 정의의 이름으로 내 죄를 용서 받을 수 있기를 바라네.' WHERE entry=2000005547; /* content: I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins. */

SET NAMES 'latin1';
