-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_creature SET subname_loc6='Crocilisk Trainer' WHERE entry=2876; -- subname: Crocilisk Trainer
UPDATE locales_creature SET subname_loc6='Magic Skill Trainer *Temp*' WHERE entry=2896; -- subname: Magic Skill Trainer *Temp*
UPDATE locales_creature SET subname_loc6='Toughness/Resist Trainer *Temp*' WHERE entry=2899; -- subname: Toughness/Resist Trainer *Temp*
UPDATE locales_creature SET name_loc6='Jackson Bayne',subname_loc6='Boar Trainer' WHERE entry=2939; -- name: Jackson Bayne -- subname: Boar Trainer
UPDATE locales_creature SET name_loc6='Kyln Longclaw',subname_loc6='Boar Trainer' WHERE entry=3697; -- name: Kyln Longclaw -- subname: Boar Trainer
UPDATE locales_creature SET subname_loc6='Cat Trainer' WHERE entry=3699; -- subname: Cat Trainer
UPDATE locales_creature SET subname_loc6='NEED MODEL' WHERE entry=3831; -- subname: NEED MODEL
UPDATE locales_creature SET name_loc6='[UNUSED] JEFF CHOW TEST',subname_loc6='No Clothes NPC' WHERE entry=4045; -- name: [UNUSED] JEFF CHOW TEST -- subname: No Clothes NPC
UPDATE locales_creature SET subname_loc6='Foraging Trainer' WHERE entry=4149; -- subname: Foraging Trainer
UPDATE locales_creature SET subname_loc6='Cat Trainer' WHERE entry=4153; -- subname: Cat Trainer
UPDATE locales_creature SET subname_loc6='Cartography Trainer' WHERE entry=4157; -- subname: Cartography Trainer
UPDATE locales_creature SET subname_loc6='Cartography Trainer' WHERE entry=4579; -- subname: Cartography Trainer
UPDATE locales_creature SET subname_loc6='Raptor Trainer' WHERE entry=4621; -- subname: Raptor Trainer
UPDATE locales_creature SET subname_loc6='Wolf Pet Trainer' WHERE entry=4994; -- subname: Wolf Pet Trainer
UPDATE locales_creature SET subname_loc6='Bird Pet Trainer' WHERE entry=5001; -- subname: Bird Pet Trainer
UPDATE locales_creature SET subname_loc6='Cat Pet Trainer' WHERE entry=5003; -- subname: Cat Pet Trainer
UPDATE locales_creature SET subname_loc6='Crawler Pet Trainer' WHERE entry=5004; -- subname: Crawler Pet Trainer
UPDATE locales_creature SET subname_loc6='Crocodile Pet Trainer' WHERE entry=5005; -- subname: Crocodile Pet Trainer
UPDATE locales_creature SET name_loc6='World Demon Trainer',subname_loc6='Demon Trainer' WHERE entry=5006; -- name: World Demon Trainer -- subname: Demon Trainer
UPDATE locales_creature SET subname_loc6='Gorilla Pet Trainer' WHERE entry=5008; -- subname: Gorilla Pet Trainer
UPDATE locales_creature SET subname_loc6='Horse Pet Trainer' WHERE entry=5009; -- subname: Horse Pet Trainer
UPDATE locales_creature SET subname_loc6='Scorpid Pet Trainer' WHERE entry=5012; -- subname: Scorpid Pet Trainer
UPDATE locales_creature SET subname_loc6='Spider Pet Trainer' WHERE entry=5013; -- subname: Spider Pet Trainer
UPDATE locales_creature SET subname_loc6='Tallstrider Pet Trainer' WHERE entry=5015; -- subname: Tallstrider Pet Trainer
UPDATE locales_creature SET subname_loc6='Turtle Pet Trainer' WHERE entry=5017; -- subname: Turtle Pet Trainer
UPDATE locales_creature SET subname_loc6='Lockpicking Trainer' WHERE entry=5027; -- subname: Lockpicking Trainer
UPDATE locales_creature SET subname_loc6='Tiger Riding Trainer' WHERE entry=5030; -- subname: Tiger Riding Trainer
UPDATE locales_creature SET subname_loc6='Brewing Trainer' WHERE entry=5034; -- subname: Brewing Trainer
UPDATE locales_creature SET subname_loc6='Cartography Trainer' WHERE entry=5035; -- subname: Cartography Trainer
UPDATE locales_creature SET name_loc6='World Guild Tabbard Vendor',subname_loc6='Guild Tabard Vendor' WHERE entry=5061; -- name: World Guild Tabbard Vendor -- subname: Guild Tabard Vendor
UPDATE locales_creature SET subname_loc6='Gun Trainer' WHERE entry=5104; -- subname: Gun Trainer
UPDATE locales_creature SET subname_loc6='Tallstrider Trainer' WHERE entry=5507; -- subname: Tallstrider Trainer
UPDATE locales_creature SET name_loc6='Innkeeper Sentinel Hill',subname_loc6='Innkeeper' WHERE entry=8999; -- name: Innkeeper Sentinel Hill -- subname: Innkeeper
UPDATE locales_creature SET subname_loc6='Dagger Trainer' WHERE entry=10292; -- subname: Dagger Trainer
UPDATE locales_creature SET subname_loc6='Fist Weapons Trainer' WHERE entry=10294; -- subname: Fist Weapons Trainer
UPDATE locales_creature SET subname_loc6='Bow Trainer' WHERE entry=10297; -- subname: Bow Trainer
UPDATE locales_creature SET subname_loc6='Crossbow Trainer' WHERE entry=10446; -- subname: Crossbow Trainer
UPDATE locales_creature SET subname_loc6='Crossbow Trainer' WHERE entry=10450; -- subname: Crossbow Trainer
UPDATE locales_creature SET subname_loc6='Mace Trainer' WHERE entry=10452; -- subname: Mace Trainer
UPDATE locales_creature SET subname_loc6='Axe Trainer' WHERE entry=10453; -- subname: Axe Trainer
UPDATE locales_creature SET subname_loc6='Crossbow Trainer' WHERE entry=10454; -- subname: Crossbow Trainer
UPDATE locales_creature SET name_loc6='Wynne Larsone',subname_loc6='Robe Merchant' WHERE entry=11111; -- name: Wynne Larsone -- subname: Robe Merchant
UPDATE locales_creature SET subname_loc6='The Head of The Black Flight' WHERE entry=11583; -- subname: The Head of The Black Flight
UPDATE locales_creature SET subname_loc6='DO NOT DELETE' WHERE entry=12999; -- subname: DO NOT DELETE
UPDATE locales_creature SET name_loc6='Vicious Gladiator\'s Gavel',subname_loc6='Exotic Reagent Merchant' WHERE entry=16015; -- name: Vicious Gladiator\'s Gavel -- subname: Exotic Reagent Merchant
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=16627; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=16628; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=16629; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=16707; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Ammunition Vendor' WHERE entry=17598; -- subname: Ammunition Vendor
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=17627; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=17628; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=17629; -- subname: Auctioneer
UPDATE locales_creature SET name_loc6='Hellfire Sentry (1)',subname_loc6='Herald\'s Sentry' WHERE entry=18057; -- name: Hellfire Sentry (1) -- subname: Herald\'s Sentry
UPDATE locales_creature SET name_loc6='Hellfire Watcher (1)',subname_loc6='Watchkeeper\'s Subordinate' WHERE entry=18058; -- name: Hellfire Watcher (1) -- subname: Watchkeeper\'s Subordinate
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=18348; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=18349; -- subname: Auctioneer
UPDATE locales_creature SET name_loc6='Nazan (1)',subname_loc6='Vazruden\'s Mount' WHERE entry=18432; -- name: Nazan (1) -- subname: Vazruden\'s Mount
UPDATE locales_creature SET subname_loc6='Auctioneer' WHERE entry=18761; -- subname: Auctioneer
UPDATE locales_creature SET subname_loc6='Horse Pet Trainer' WHERE entry=19145; -- subname: Horse Pet Trainer
UPDATE locales_creature SET subname_loc6='Aldor: Quartermaster' WHERE entry=19321; -- subname: Aldor: Quartermaster
UPDATE locales_creature SET name_loc6='Barnu Cragcrush',subname_loc6='Stable Master' WHERE entry=19325; -- name: Barnu Cragcrush -- subname: Stable Master
UPDATE locales_creature SET subname_loc6='Scryers: Quartermaster' WHERE entry=19331; -- subname: Scryers: Quartermaster
UPDATE locales_creature SET name_loc6='Alchemist of Orgrimmar',subname_loc6='Phoenix God' WHERE entry=19514; -- name: Alchemist of Orgrimmar -- subname: Phoenix God
UPDATE locales_creature SET name_loc6='Whoa! This is way more than what I bargained for, you\'re on your own, Slim!',subname_loc6='Shady Dealer' WHERE entry=19679; -- name: Whoa! This is way more than what I bargained for, you\'re on your own, Slim! -- subname: Shady Dealer
UPDATE locales_creature SET name_loc6='Hurlog Horde',subname_loc6='Warsong Gulch Battlemaster' WHERE entry=20002; -- name: Hurlog Horde -- subname: Warsong Gulch Battlemaster
UPDATE locales_creature SET subname_loc6='Silverwing Supply Officer (Neutral)' WHERE entry=20010; -- subname: Silverwing Supply Officer (Neutral)
UPDATE locales_creature SET subname_loc6='Silverwing Supply Officer (Friendly)' WHERE entry=20011; -- subname: Silverwing Supply Officer (Friendly)
UPDATE locales_creature SET subname_loc6='Silverwing Supply Officer (Honored)' WHERE entry=20012; -- subname: Silverwing Supply Officer (Honored)
UPDATE locales_creature SET subname_loc6='Silverwing Supply Officer (Revered)' WHERE entry=20013; -- subname: Silverwing Supply Officer (Revered)
UPDATE locales_creature SET subname_loc6='Silverwing Supply Officer (Exalted)' WHERE entry=20014; -- subname: Silverwing Supply Officer (Exalted)
UPDATE locales_creature SET subname_loc6='Warsong Supply Officer (Honored)' WHERE entry=20022; -- subname: Warsong Supply Officer (Honored)
UPDATE locales_creature SET name_loc6='Claw (1)',subname_loc6='Swamplord Musel\'ek\'s Pet' WHERE entry=20165; -- name: Claw (1) -- subname: Swamplord Musel\'ek\'s Pet
UPDATE locales_creature SET name_loc6='Murkblood Henchman (1)',subname_loc6='Murkblood Foreman\'s Flunky' WHERE entry=20178; -- name: Murkblood Henchman (1) -- subname: Murkblood Foreman\'s Flunky
UPDATE locales_creature SET subname_loc6='Windrider Keeper' WHERE entry=20494; -- subname: Windrider Keeper
UPDATE locales_creature SET name_loc6='Inscriber Saalyn',subname_loc6='Aldor Inscriptions' WHERE entry=20807; -- name: Inscriber Saalyn -- subname: Aldor Inscriptions
UPDATE locales_creature SET name_loc6='Inscriber Veredis',subname_loc6='Scryer Inscriptions' WHERE entry=20808; -- name: Inscriber Veredis -- subname: Scryer Inscriptions
UPDATE locales_creature SET subname_loc6='Ammunition' WHERE entry=21483; -- subname: Ammunition
UPDATE locales_creature SET subname_loc6='Ammunition' WHERE entry=21488; -- subname: Ammunition
UPDATE locales_creature SET name_loc6='Coilfang Ray (1)',subname_loc6='Observer\'s Pet' WHERE entry=21841; -- name: Coilfang Ray (1) -- subname: Observer\'s Pet
UPDATE locales_creature SET name_loc6='Athramanis (1)',subname_loc6='Bounty Hunter' WHERE entry=22528; -- name: Athramanis (1) -- subname: Bounty Hunter
UPDATE locales_creature SET name_loc6='Frostwolf Stable Master (1)',subname_loc6='Stable Master' WHERE entry=22551; -- name: Frostwolf Stable Master (1) -- subname: Stable Master
UPDATE locales_creature SET name_loc6='Ravak Grimtotem (1)',subname_loc6='Bounty Hunter' WHERE entry=22569; -- name: Ravak Grimtotem (1) -- subname: Bounty Hunter
UPDATE locales_creature SET name_loc6='Stormpike Stable Master (1)',subname_loc6='Stable Master' WHERE entry=22577; -- name: Stormpike Stable Master (1) -- subname: Stable Master
UPDATE locales_creature SET name_loc6='Captain Balinda Stonehearth (1)',subname_loc6='Stormpike Captain' WHERE entry=22605; -- name: Captain Balinda Stonehearth (1) -- subname: Stormpike Captain
UPDATE locales_creature SET name_loc6='Captain Galvangar (1)',subname_loc6='Frostwolf Captain' WHERE entry=22606; -- name: Captain Galvangar (1) -- subname: Frostwolf Captain
UPDATE locales_creature SET name_loc6='Rezrelek (1)',subname_loc6='Winterax Hero' WHERE entry=22631; -- name: Rezrelek (1) -- subname: Winterax Hero
UPDATE locales_creature SET name_loc6='Drek\'Thar (1)',subname_loc6='Frostwolf General' WHERE entry=22641; -- name: Drek\'Thar (1) -- subname: Frostwolf General
UPDATE locales_creature SET name_loc6='Vanndar Stormpike (1)',subname_loc6='Stormpike General' WHERE entry=22644; -- name: Vanndar Stormpike (1) -- subname: Stormpike General
UPDATE locales_creature SET name_loc6='Brogus Thunderbrew (1)',subname_loc6='Food & Drink' WHERE entry=22646; -- name: Brogus Thunderbrew (1) -- subname: Food & Drink
UPDATE locales_creature SET name_loc6='Grelkor (1)',subname_loc6='Blacksmithing Supplies' WHERE entry=22650; -- name: Grelkor (1) -- subname: Blacksmithing Supplies
UPDATE locales_creature SET name_loc6='Jonivera Farmountain (1)',subname_loc6='General Goods' WHERE entry=22651; -- name: Jonivera Farmountain (1) -- subname: General Goods
UPDATE locales_creature SET name_loc6='Kurdrum Barleybeard (1)',subname_loc6='Reagents & Poison Supplies' WHERE entry=22652; -- name: Kurdrum Barleybeard (1) -- subname: Reagents & Poison Supplies
UPDATE locales_creature SET name_loc6='Lana Thunderbrew (1)',subname_loc6='Blacksmithing Supplies' WHERE entry=22653; -- name: Lana Thunderbrew (1) -- subname: Blacksmithing Supplies
UPDATE locales_creature SET name_loc6='Rarck (1)',subname_loc6='General Goods' WHERE entry=22654; -- name: Rarck (1) -- subname: General Goods
UPDATE locales_creature SET name_loc6='Shrye Ragefist (1)',subname_loc6='Food & Drink' WHERE entry=22655; -- name: Shrye Ragefist (1) -- subname: Food & Drink
UPDATE locales_creature SET name_loc6='Svalbrad Farmountain (1)',subname_loc6='Trade Goods' WHERE entry=22659; -- name: Svalbrad Farmountain (1) -- subname: Trade Goods
UPDATE locales_creature SET name_loc6='Yaelika Farclaw (1)',subname_loc6='Reagents & Poison Supplies' WHERE entry=22660; -- name: Yaelika Farclaw (1) -- subname: Reagents & Poison Supplies
UPDATE locales_creature SET name_loc6='Zora Guthrek (1)',subname_loc6='Trade Goods' WHERE entry=22661; -- name: Zora Guthrek (1) -- subname: Trade Goods
UPDATE locales_creature SET name_loc6='Gaelden Hammersmith (1)',subname_loc6='Stormpike Supply Officer' WHERE entry=22680; -- name: Gaelden Hammersmith (1) -- subname: Stormpike Supply Officer
UPDATE locales_creature SET name_loc6='Grunnda Wolfheart (1)',subname_loc6='Frostwolf Supply Officer' WHERE entry=22681; -- name: Grunnda Wolfheart (1) -- subname: Frostwolf Supply Officer
UPDATE locales_creature SET name_loc6='Jekyll Flandring (1)',subname_loc6='Frostwolf Supply Officer' WHERE entry=22682; -- name: Jekyll Flandring (1) -- subname: Frostwolf Supply Officer
UPDATE locales_creature SET name_loc6='Thanthaldis Snowgleam (1)',subname_loc6='Stormpike Supply Officer' WHERE entry=22695; -- name: Thanthaldis Snowgleam (1) -- subname: Stormpike Supply Officer
UPDATE locales_creature SET name_loc6='Dirk Swindle (1)',subname_loc6='Bounty Hunter' WHERE entry=22699; -- name: Dirk Swindle (1) -- subname: Bounty Hunter
UPDATE locales_creature SET name_loc6='Najak Hexxen (1)',subname_loc6='Bounty Hunter' WHERE entry=22712; -- name: Najak Hexxen (1) -- subname: Bounty Hunter
UPDATE locales_creature SET subname_loc6='Ticket Redeemer' WHERE entry=24495; -- subname: Ticket Redeemer
UPDATE locales_creature SET name_loc6='Kael\'thas Sunstrider (1)',subname_loc6='Lord of the Blood Elves' WHERE entry=24857; -- name: Kael\'thas Sunstrider (1) -- subname: Lord of the Blood Elves
UPDATE locales_creature SET subname_loc6='Specialty Ammunition Vendor' WHERE entry=25195; -- subname: Specialty Ammunition Vendor
UPDATE locales_creature SET subname_loc6='Specialty Ammunition Vendor' WHERE entry=25196; -- subname: Specialty Ammunition Vendor
UPDATE locales_creature SET subname_loc6='Earthen Ring' WHERE entry=25344; -- subname: Earthen Ring
UPDATE locales_creature SET subname_loc6='Earthen Ring' WHERE entry=25345; -- subname: Earthen Ring
UPDATE locales_creature SET subname_loc6='Earthen Ring' WHERE entry=25360; -- subname: Earthen Ring
UPDATE locales_creature SET name_loc6='Sliver (1)',subname_loc6='Garaxxas\' Pet' WHERE entry=25564; -- name: Sliver (1) -- subname: Garaxxas\' Pet
UPDATE locales_creature SET subname_loc6='Earthen Ring' WHERE entry=26221; -- subname: Earthen Ring
UPDATE locales_creature SET name_loc6='Ahune (1)',subname_loc6='The Frost Lord' WHERE entry=26338; -- name: Ahune (1) -- subname: The Frost Lord

SET NAMES 'latin1';
