-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc4='告诉我更多。' WHERE entry=-3409000; -- content: Tell me more.
UPDATE gossip_texts SET content_loc4='奇怪的术士？' WHERE entry=-3560005; -- content: Strange wizard?

SET NAMES 'latin1';
