-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc4='进入鲜血竞技场吧，$n。战斗就要开始了！' WHERE entry=2000000001; /* content: Get in the Ring of Blood, $N. The fight is about to start! */
UPDATE db_script_string SET content_loc4='战斗即将开始！' WHERE entry=2000000002; /* content: The battle is about to begin! */
UPDATE db_script_string SET content_loc4='好的，我们走吧！' WHERE entry=2000000017; /* content: Ok, let\'s go! */
UPDATE db_script_string SET content_loc4='唉呦！' WHERE entry=2000000026; /* content: Whoops! */
UPDATE db_script_string SET content_loc4='过来，$n。伊利丹大人在等你。' WHERE entry=2000000034; /* content: Come, $N. Lord Stormrage awaits. */
UPDATE db_script_string SET content_loc4='龙喉氏族的勇士们，都聚集过来吧！就在你们中间，一位佼佼者已经晋升为领主了！向$n领主致敬！表达你们的敬意和忠诚吧！' WHERE entry=2000000035; /* content: Warriors of Dragonmaw, gather \'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N! */
UPDATE db_script_string SET content_loc4='伊利丹大人很快就来到这里。' WHERE entry=2000000036; /* content: Lord Illidan will be here shortly. */
UPDATE db_script_string SET content_loc4='伊利丹大人万岁！' WHERE entry=2000000037; /* content: All hail Lord Illidan! */
UPDATE db_script_string SET content_loc4='伊利丹大人，这位就是我和其他人向您提到过的龙喉氏族的英雄。他会引领我们走向胜利！' WHERE entry=2000000038; /* content: Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory! */
UPDATE db_script_string SET content_loc4='但是……大人，我不明白。$n……这个兽人曾经为我们……' WHERE entry=2000000039; /* content: But... My lord, I do not understand. $N... He is the orc that has... */
UPDATE db_script_string SET content_loc4='遵命，主人。' WHERE entry=2000000040; /* content: It will be done, my lord. */
UPDATE db_script_string SET content_loc4='你胆敢欺骗莫格霍尔！在将你送到伊利丹大人的神殿之前，我要让你尝尝你想都不敢想的痛苦！我要折磨你，享受复仇的乐趣。' WHERE entry=2000000041; /* content: So you thought to make a fool of Mor\'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance. */
UPDATE db_script_string SET content_loc4='我们会再见的，勇敢的$c。' WHERE entry=2000000042; /* content: Until we meet again, brave one. */
UPDATE db_script_string SET content_loc4='完成了……' WHERE entry=2000000044; /* content: It is done... */
UPDATE db_script_string SET content_loc4='在丹莫罗寒冷的日子里，没有什么比热酒更好的东西了！' WHERE entry=2000000045; /* content: There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right! */
UPDATE db_script_string SET content_loc4='呱呱！不！！这不可能……呱呱！你骗了我……呱呱……你这个骗子！呱呱！' WHERE entry=2000000047; /* content: Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit! */
UPDATE db_script_string SET content_loc4='现在把这些稀土放到我的培养槽里去……' WHERE entry=2000000048; /* content: Now let us place this rare earth in my planter... */
UPDATE db_script_string SET content_loc4='都长长脑子吧，在你们认识到一头冲进燃烧军团的小队是自杀行为之前，我还要送多少具尸体回你们的家？还有，不要在我面前用力晃你们的大脑袋，好像你们明白我在说什么似的。' WHERE entry=2000000055; /* content: How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about! */
UPDATE db_script_string SET content_loc4='以群星的名义！' WHERE entry=2000000060; /* content: By the stars! A spirit has been summoned! */
UPDATE db_script_string SET content_loc4='过去的事情谁也说不清，但重要的是我们的未来！' WHERE entry=2000000061; /* content: It\'s a mystery of the past indeed! But a key to our future! */
UPDATE db_script_string SET content_loc4='威胁结束了！是$n解救了我们！' WHERE entry=2000000062; /* content: The threat be over! $N be savin\' us all! */
UPDATE db_script_string SET content_loc4='我们怎能忍受有恶魔的爪牙在这片土地上肆虐横行！' WHERE entry=2000000065; /* content: We will suffer no demon\'s servant in our lands! */
UPDATE db_script_string SET content_loc4='愿安宁和耐心永远与你同在，$n。' WHERE entry=2000000066; /* content: Peace and patience be with you, $N. Remain strong always. */
UPDATE db_script_string SET content_loc4='你在伊瑟拉的领域里干什么，入侵者？走开！你们在这里不受欢迎！' WHERE entry=2000000067; /* content: What are you doing in Ysera\'s realm, interloper? Leave us, I say! Your kind are not welcome here! */
UPDATE db_script_string SET content_loc4='你……你不是他们的同党！快，在他们找到我们之前，得躲进某个隐密的地方！快点！' WHERE entry=2000000068; /* content: You -- you\'re not one of them! Let\'s get out of sight before they find us! Hurry! */
UPDATE db_script_string SET content_loc4='他们还在追我，$r！快点，在我们被发现前告诉我，你来这里干什么！要是被他们抓住了，我们两个人都得死！' WHERE entry=2000000069; /* content: They\'re following me, $R! Quickly, tell me why you\'re here before we\'re discovered! If they catch up to me, it will mean my death and yours! */
UPDATE db_script_string SET content_loc4='年轻的麻鹰，如果没有你，我们恐怕要花上几年的时间才能找到乌鸦之书。带着我们的感激返回纳格兰吧。' WHERE entry=2000000070; /* content: It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude. */
UPDATE db_script_string SET content_loc4='这就是了！这就是真正的……乌鸦之书！' WHERE entry=2000000071; /* content: This is it! This is really it -- the Book of the Raven! */
UPDATE db_script_string SET content_loc4='石板应证了我先前的猜想。我们必须利用这条信息，在安苏对翡翠梦境造成更大的破坏之前，将他召唤到这个世界中，然后击败他！' WHERE entry=2000000074; /* content: The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream! */
UPDATE db_script_string SET content_loc4='麻鹰被证明在搜索乌鸦石方面是非常有天分的，因此观察者艾莱亚训练了另一只麻鹰远程传递我的声音。当你研究显现在石板上鸟的灵魂时，它可以帮助我们进行联络！' WHERE entry=2000000075; /* content: Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet! */
UPDATE db_script_string SET content_loc4='击碎这块灵魂石简直是小事一桩！' WHERE entry=2000000077; /* content: A simple enough task to break this soulstone! */
UPDATE db_script_string SET content_loc4='我们该与埃瑟里克斯·纳拉辛有个了断了。自然之灵啊，告诉我，去哪里才能找到其它的灵魂宝石来解除他的魔法？' WHERE entry=2000000079; /* content: Then we must put an end to Athrikus Narassin. Tell me, spirit, where might we find the other soulgems, to undo his magic? */
UPDATE db_script_string SET content_loc4='在大灾变时，亚米萨兰正在大陆崩裂的边界，几乎没有什么幸存者逃过那次劫难。' WHERE entry=2000000081; /* content: In the throes of the Sundering, Ameth\'Aran was at the whim of the terror that gripped the land. There was little hope for survival. */
UPDATE db_script_string SET content_loc4='埃瑟里克斯来到我们面前，他声称能把我们从痛苦中解救出来。他给我们施了魔法，让我们免受伤害。' WHERE entry=2000000082; /* content: Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm. */
UPDATE db_script_string SET content_loc4='当震动停下来的时候，他的真实目的暴露出来了。我们都被困住了，而他在慢慢地汲取我们的能量。' WHERE entry=2000000083; /* content: When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers. */
UPDATE db_script_string SET content_loc4='曾经有数百人被他的法术困住。现在只有一小部分还被囚禁着。他有时也会和我们交谈。' WHERE entry=2000000084; /* content: There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes. */
UPDATE db_script_string SET content_loc4='他担心他的法力会减弱，那块宝贵的灵魂宝石也会消失和死亡。' WHERE entry=2000000085; /* content: He worried that his power weakened, that soon even we last of his precious soulgems would fade and die. */
UPDATE db_script_string SET content_loc4='%s嗅到了药剂的气味，兴奋地把它喝了下去。' WHERE entry=2000000087; /* content: %s sniffs the elixir then eagerly digs in! */
UPDATE db_script_string SET content_loc4='%s召唤出一个信使……' WHERE entry=2000000092; /* content: %s summons a messenger... */
UPDATE db_script_string SET content_loc4='……啊。' WHERE entry=2000000097; /* content: ... oops. */
UPDATE db_script_string SET content_loc4='嗯……等搞定这些，我就要去奶酪店吃点东西。' WHERE entry=2000000143; /* content: Hm...after dropping this off, I think I\'ll head to that cheese shop for a snack. */
UPDATE db_script_string SET content_loc4='现在可以吃了……' WHERE entry=2000000151; /* content: Now for that snack... */
UPDATE db_script_string SET content_loc4='是啊是啊，生意很忙！' WHERE entry=2000000156; /* content: Yes ma\'am, business is brisk! */
UPDATE db_script_string SET content_loc4='我会的，谢谢你的奶酪！' WHERE entry=2000000157; /* content: Thanks for the cheese! */
UPDATE db_script_string SET content_loc4='该回商店了……' WHERE entry=2000000158; /* content: Time to get back to the shop... */
UPDATE db_script_string SET content_loc4='我回来了！' WHERE entry=2000000159; /* content: I\'m back! */
UPDATE db_script_string SET content_loc4='呼啊啊啊啊啊啊啊啊！！' WHERE entry=2000000161; /* content: ROARRRRR!! */
UPDATE db_script_string SET content_loc4='夜色镇……我饿了！！' WHERE entry=2000000162; /* content: DARKSHIRE...I HUNGER!! */
UPDATE db_script_string SET content_loc4='你要是敢回来，狂心狼獾人就要你的命。从现在开始，你是我们的敌人！' WHERE entry=2000000163; /* content: Frenzyheart kill you if you come back. You no welcome here no more! */
UPDATE db_script_string SET content_loc4='%s盯着西北方，发出了一声怒吼。' WHERE entry=2000000168; /* content: %s stares to the northwest and lets out a long, drawn out howl. */
UPDATE db_script_string SET content_loc4='%s发出震撼人心的怒吼。' WHERE entry=2000000169; /* content: %s lets forth a mighty howl. */
UPDATE db_script_string SET content_loc4='如你所愿……' WHERE entry=2000000195; /* content: As you wish... */
UPDATE db_script_string SET content_loc4='拉里克要教训你！' WHERE entry=2000000196; /* content: Raliq teach you lesson now! */
UPDATE db_script_string SET content_loc4='库什库什不会还钱的！死吧！' WHERE entry=2000000197; /* content: F\'woooroonn! Coosh\'coosh pay nothing! Die! */
UPDATE db_script_string SET content_loc4='我选择第三项：杀了你！' WHERE entry=2000000198; /* content: I choose the third option: KILLING YOU! */
UPDATE db_script_string SET content_loc4='我自由了！水流之灵将回到族人身边去。在它的指引下，我们终将在这片荒芜的土地上生存下去。我欠你一个人情，$n。' WHERE entry=2000000199; /* content: I\'m free!  The spirit of water returns to my people.  It will bring us the wisdom we need to survive in this harsh land.  I am in your debt, $N. */
UPDATE db_script_string SET content_loc4='你给了我自由！风之灵又一次愿意与族人们交流并赐予我们力量了。谢谢你，陌生人。' WHERE entry=2000000200; /* content: You\'ve freed me!  The winds speak to my people once again and grant us their strength.  I thank you, stranger. */
UPDATE db_script_string SET content_loc4='比索，我的朋友，好久不见啊。' WHERE entry=2000000208; /* content: It has been a long time, Bethor, my friend. */
UPDATE db_script_string SET content_loc4='如果时间允许的话，我们得好好谈一下。因为我们有很多事情要讨论。' WHERE entry=2000000209; /* content: When time permits, we must speak at length.  For we have much to discuss. */
UPDATE db_script_string SET content_loc4='谢谢你，$n。没有你的帮助，我永远无法成为被遗忘者的一员。' WHERE entry=2000000210; /* content: And thank you, $N.  Without your aid I may never have found my way to the Forsaken. */
UPDATE db_script_string SET content_loc4='保重，我的朋友。' WHERE entry=2000000211; /* content: Farewell, my friend. */
UPDATE db_script_string SET content_loc4='%s把信交给了药剂师扎玛。' WHERE entry=2000000214; /* content: %s gives message to Apothecary Zamah. */
UPDATE db_script_string SET content_loc4='%s用嚎叫回应玛鲁卡兹的召唤。' WHERE entry=2000000224; /* content: %s howls in response to Malukaz\'s call. */
UPDATE db_script_string SET content_loc4='%s表示赞同。' WHERE entry=2000000225; /* content: %s expresses its approval. */
UPDATE db_script_string SET content_loc4='愿你与我们的结合永不再分开，灵魂。' WHERE entry=2000000226; /* content: May our bond with you never be broken again, spirit. */
UPDATE db_script_string SET content_loc4='咪咪用饥饿的眼神看着薇拉·火语。' WHERE entry=2000000390; /* content: Twinkle looks at Viera Sunwhisper with very hungry eyes. */
UPDATE db_script_string SET content_loc4='我在想，这玩意能把一只白猫丢多远……' WHERE entry=2000000406; /* content: I wonder how far this would launch that white cat... */
UPDATE db_script_string SET content_loc4='随着中和剂与湖水混合起来，被水晶映射的湖面开始变得清澈了。' WHERE entry=2000000633; /* content: As the neutralizing agent mixes into the waters of the lake, the water that was irradiated by the crystal seems to clear. */
UPDATE db_script_string SET content_loc4='泰顿，你去在那些变异生物身上试用一下中和剂如何？' WHERE entry=2000000634; /* content: Tedon, go ahead and try the neutralizing agent on the mutated creature. */
UPDATE db_script_string SET content_loc4='看上去该把你从笼子里放出来了。' WHERE entry=2000000635; /* content: Looks like it\'s time to let you out of this cage. */
UPDATE db_script_string SET content_loc4='现在，把中和剂放上去……' WHERE entry=2000000636; /* content: Now, to put the neutralizing agent on it... */
UPDATE db_script_string SET content_loc4='成功啦！' WHERE entry=2000000637; /* content: Success! */
UPDATE db_script_string SET content_loc4='太可怕了！如果我们不加固这根支柱的话，这座房子肯定会倒塌的。' WHERE entry=2000000645; /* content: This won\'t work at all! The buildings will surely collapse if we do not shore up the support beams. */
UPDATE db_script_string SET content_loc4='这是什么玩意啊？！我们必须保护地基，否则这房子会全部倒塌的！' WHERE entry=2000000646; /* content: This won\'t do at all! We have to secure the foundation or the entire structure will crumble! */
UPDATE db_script_string SET content_loc4='这个建筑至少违反了八项条例。' WHERE entry=2000000647; /* content: This structure violates at least 8 different ordinances! */
UPDATE db_script_string SET content_loc4='这个看上去就好多了，让我们看看里面。' WHERE entry=2000000649; /* content: Hrm, this looks much better. Let\'s have a look on the inside. */
UPDATE db_script_string SET content_loc4='亲娘唉，整个后墙都被炸开了！怎么有人会想要生活在这里？我看够了！' WHERE entry=2000000650; /* content: By the foul teat of Kil\'Jaeden\'s rotted torso, the entire backside is blown out! How can someone be expected to live in here? I\'ve seen enough! */
UPDATE db_script_string SET content_loc4='这个应该有作用……' WHERE entry=2000000655; /* content: This should do it... */
UPDATE db_script_string SET content_loc4='醒来吧，小家伙。从睡眠中醒来吧……你现在安全了。' WHERE entry=2000000656; /* content: Wake up little creature. Wake up from your slumber... You are safe now. */
UPDATE db_script_string SET content_loc4='%s在呻吟。' WHERE entry=2000000657; /* content: %s groans. */
UPDATE db_script_string SET content_loc4='%s坐了起来。' WHERE entry=2000000658; /* content: %s sits up. */
UPDATE db_script_string SET content_loc4='我……我在哪里？这……这是什么地方？' WHERE entry=2000000659; /* content: Whe... Where am I? What... What is this place? */
UPDATE db_script_string SET content_loc4='%s昏了过去。' WHERE entry=2000000661; /* content: %s falls back into a coma. */
UPDATE db_script_string SET content_loc4='我怎么能在那东西传播他的异端邪说时安心工作？' WHERE entry=2000000663; /* content: How can I be expected to get any work done with that thing spreading its heresy? */
UPDATE db_script_string SET content_loc4='在这里，我们不需要你的仁慈。' WHERE entry=2000000665; /* content: We do not need your kind here. */
UPDATE db_script_string SET content_loc4='%s指示你跟着他。' WHERE entry=2000000666; /* content: %s urges you to follow him. */
UPDATE db_script_string SET content_loc4='%s指着库欧图腾。' WHERE entry=2000000667; /* content: %s points to the totem of Coo. */
UPDATE db_script_string SET content_loc4='%s提醒你跟着他。' WHERE entry=2000000668; /* content: %s motions for you to follow him. */
UPDATE db_script_string SET content_loc4='[熊怪语] Ritk kin\'chikx azul azure summit...' WHERE entry=2000000669; /* content: [Furbolg] Ritk kin\'chikx azul azure summit... */
UPDATE db_script_string SET content_loc4='[熊怪语] 库欧飞了起来……越过河流。找到提克提。' WHERE entry=2000000670; /* content: [Furbolg] Coo xip fly... Jump ilos river. Find Tikti. */
UPDATE db_script_string SET content_loc4='%s指着河的对岸。' WHERE entry=2000000671; /* content: %s points across the river. */
UPDATE db_script_string SET content_loc4='%s叫你跟随他。' WHERE entry=2000000672; /* content: %s asks that you follow him. */
UPDATE db_script_string SET content_loc4='[熊怪语] 你要走的路还很长。看到那条河了吗？沿着河走，找到尤尔。' WHERE entry=2000000673; /* content: [Furbolg] Far you mixik tak come. Gaze upon the kitch\'kal river. Follow. Ilog to Yor. */
UPDATE db_script_string SET content_loc4='[熊怪语] 去吧……去河的尽头看看。南边！' WHERE entry=2000000674; /* content: [Furbolg] Go... Search yitix\'kil bottom river. South! */
UPDATE db_script_string SET content_loc4='[熊怪语] 过来，$n。我们一起离开水。' WHERE entry=2000000675; /* content: [Furbolg] Come, $n. Let us leave the water together, purified. */
UPDATE db_script_string SET content_loc4='[熊怪语] 我们现在一起走吧。我们会找到瓦克。' WHERE entry=2000000676; /* content: [Furbolg] We go now, together. We will seek Vark. */
UPDATE db_script_string SET content_loc4='[熊怪语] 跟我去找瓦克。' WHERE entry=2000000677; /* content: [Furbolg] Follow me to Vark. */
UPDATE db_script_string SET content_loc4='[熊怪语] 快点，$n。瓦克在等你。' WHERE entry=2000000678; /* content: [Furbolg] Hurry, $n. Vark awaits you. */
UPDATE db_script_string SET content_loc4='[熊怪语] 谢谢你，$n！' WHERE entry=2000000680; /* content: [Furbolg] Thank you, $n! */
UPDATE db_script_string SET content_loc4='[熊怪语] 预言是真的！' WHERE entry=2000000681; /* content: [Furbolg] The prophecy is true! */
UPDATE db_script_string SET content_loc4='[熊怪语] 止松熊怪不会忘记你的勇敢！' WHERE entry=2000000682; /* content: [Furbolg] The Stillpine furbolgs will not soon forget your bravery! */
UPDATE db_script_string SET content_loc4='[熊怪语] 止松要塞像欢迎英雄般欢迎你！' WHERE entry=2000000683; /* content: [Furbolg] Those remaining at Stillpine Hold will welcome you as a hero! */
UPDATE db_script_string SET content_loc4='阿达曼特，你能看下这块石板，顺便试着翻译一下上面的符文吗？' WHERE entry=2000000691; /* content: Adamant, could you please take a look at this tablet and try to decipher the runes? */
UPDATE db_script_string SET content_loc4='当然！没问题，亲爱的！' WHERE entry=2000000692; /* content: Of course! Anything for you, darling! */
UPDATE db_script_string SET content_loc4='嗯，让我看看那块石板。' WHERE entry=2000000693; /* content: Alright, let me take a look at that tablet. */
UPDATE db_script_string SET content_loc4='%s慢慢地读着石板，用他们的母语读着那些文字。' WHERE entry=2000000694; /* content: %s slowly reads the tablet, mouthing the words in their native tongue. */
UPDATE db_script_string SET content_loc4='天哪……纳迦督军！' WHERE entry=2000000695; /* content: Naga warlord! Oh dear... */
UPDATE db_script_string SET content_loc4='嗯，你不会喜欢这个消息的，小姑娘。这块石板是纳迦的交流工具。他们的首领督军斯雷提兹命令他的纳迦们用武力来抢夺这块岛屿。' WHERE entry=2000000696; /* content: Well, you aren\'t going to like what I have to tell you, young missy. This tablet is a naga communication. Their leader, Warlord Sriss\'tiz, has ordered his naga to take the rest of the island by force. */
UPDATE db_script_string SET content_loc4='看上去他得到了纳沙塔的增援！' WHERE entry=2000000697; /* content: And it looks like he\'s got reinforcements comin\' from Nazjatar! */
UPDATE db_script_string SET content_loc4='我们必须得干点什么了！' WHERE entry=2000000698; /* content: We\'ve got to do something about this! */
UPDATE db_script_string SET content_loc4='谢谢你，阿达曼特。我想我知道谁最适合这项工作。' WHERE entry=2000000699; /* content: Thank you, Adamant. I think I know just the person for the job. */
UPDATE db_script_string SET content_loc4='你们从来都不看信箱的吗？' WHERE entry=2000000827; /* content: Don\'t you people ever check the mail? */
UPDATE db_script_string SET content_loc4='我要怎么样才能把这么多邮件都送出去？' WHERE entry=2000000828; /* content: How am I expected to deliver all of these messages? */
UPDATE db_script_string SET content_loc4='我要换个工作。这个工作快要让我崩溃了……' WHERE entry=2000000829; /* content: I need to be re-assigned. This job is pushing me over the edge... */
UPDATE db_script_string SET content_loc4='他以为自己多么重要，总是把我呼来喝去的……我要给他点颜色看看……我要让他们所有人都尝尝我的厉害！' WHERE entry=2000000830; /* content: He thinks he\'s so damned important. Always pushing me around... I\'ll show him. I\'ll show all of them! */
UPDATE db_script_string SET content_loc4='如果我可以再次回到蘑菇丛就好了。我这辈子都没有看到过这么多成熟的蘑菇。' WHERE entry=2000000831; /* content: If only I could get back to the mushroom thicket. I have not seen such a mature cluster in my lifetime! */
UPDATE db_script_string SET content_loc4='可怜的杜里奥斯。那些黑铁矮人真是该死，帮帮我吧……' WHERE entry=2000005000; /* content: Poor Dorius. If I ever get my hands on those Dark Irons, so help me... */
UPDATE db_script_string SET content_loc4='奥普斯想要一些科尔戈的黄金……和一些虫子。' WHERE entry=2000005001; /* content: Opus wants some Cuergo\'s Gold... with worm. */
UPDATE db_script_string SET content_loc4='基布雷尔正在接受地精工程学协会的调查。' WHERE entry=2000005003; /* content: Kibler is being investigated by G.E.T.A. */
UPDATE db_script_string SET content_loc4='比修知道宝藏被藏在哪儿了。' WHERE entry=2000005004; /* content: Bijou knows where treasures are hidden. */
UPDATE db_script_string SET content_loc4='龙控制着兽人！？不会吧！' WHERE entry=2000005005; /* content: Dragons controlling orcs!? SQUAWK! */
UPDATE db_script_string SET content_loc4='问问基布雷尔关于宝藏的事情！哇！' WHERE entry=2000005007; /* content: Ask Kibler about the treasure! SQUAWK! */
UPDATE db_script_string SET content_loc4='哇！*咳**咳*我要戒烟！' WHERE entry=2000005008; /* content: SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE db_script_string SET content_loc4='士兵们，干得好！轻松一下吧！' WHERE entry=2000005009; /* content: Well done, soldiers! At ease! */
UPDATE db_script_string SET content_loc4='啊哈！乐意帮忙！' WHERE entry=2000005010; /* content: Zug zug! Happy to help! */
UPDATE db_script_string SET content_loc4='神秘的蹄印，烧焦的盾牌，四散的徽章……这些东西有什么联系吗？' WHERE entry=2000005012; /* content: Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this? */
UPDATE db_script_string SET content_loc4='我觉得德拉兹特根本找不到有能力杀死那头迅猛龙的人。我的意思是说，他已经两次提升赏金了……' WHERE entry=2000005013; /* content: I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice... */
UPDATE db_script_string SET content_loc4='但这是唯一适合布洛格的房子，地精的房子都太小太小啦！' WHERE entry=2000005014; /* content: But this the only building that fit Brogg! Goblins make buildings too small! */
UPDATE db_script_string SET content_loc4='布洛格，我记得我们谈过这个问题。你不能待在房间里。当然啦，你是可以塞进去，不过其他人就没空间了！' WHERE entry=2000005015; /* content: I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else! */
UPDATE db_script_string SET content_loc4='是，我们是说过你可以待在这儿，但是这间房子是我们的总部！所有的手册和蓝图都存放在里面！' WHERE entry=2000005016; /* content: Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here! */
UPDATE db_script_string SET content_loc4='我想说，食人魔的体型也太大了吧！好吧，我打消说服你挪动地方的念头，不过这只是暂时的！' WHERE entry=2000005017; /* content: I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent! */
UPDATE db_script_string SET content_loc4='你最好后退一点。清除鱼的内脏很容易弄脏衣服。' WHERE entry=2000005019; /* content: You might wanna stand back. Fish guttin\' is a dirty job. */
UPDATE db_script_string SET content_loc4='朋友，感谢你成功地保卫了塞拉摩。' WHERE entry=2000005020; /* content: It\'s good to see you defending Theramore with pride, friend. */
UPDATE db_script_string SET content_loc4='等你下班以后，我请你去旅店喝上几杯，一起回忆过去的美好时光。' WHERE entry=2000005021; /* content: When you\'re off duty, let\'s go to the inn. I\'ll buy a round and we can reminisce about the good old days. */
UPDATE db_script_string SET content_loc4='嘿，谁来帮我抓住这个东西!' WHERE entry=2000005024; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc4='过来跟我谈谈，我会为你拨开疑云的。' WHERE entry=2000005026; /* content: Come speak with me, and what once was cloudy shall become crystal clear. */
UPDATE db_script_string SET content_loc4='明天我们将开始训练这些大有前途的龙，别忘了带上你的玩具骨头。' WHERE entry=2000005028; /* content: Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys. */
UPDATE db_script_string SET content_loc4='我来自底层社会……我们那儿的人民倍受折磨。' WHERE entry=2000005031; /* content: I come from the land down under... where women plague and men sunder. */
UPDATE db_script_string SET content_loc4='嘿，谁来帮我抓住这个东西!' WHERE entry=2000005035; /* content: It\'s getting away! */
UPDATE db_script_string SET content_loc4='我也许早就该去猎杀那个肮脏的野兽，不过现在我决定提供赏金悬赏他的脑袋。' WHERE entry=2000005037; /* content: I might just have to go hunting for that Wretched beast now that there\'s a bounty on his head. */
UPDATE db_script_string SET content_loc4='下班后我就去看看那份悬赏令。' WHERE entry=2000005046; /* content: I\'m up to looking into that bounty after this shift. */
UPDATE db_script_string SET content_loc4='这附近的确有很多乱扔垃圾的家伙。' WHERE entry=2000005048; /* content: Having a good time? */
UPDATE db_script_string SET content_loc4='我有另一条从虚空传来的讯息。' WHERE entry=2000005049; /* content: I have another reading from the nether. */
UPDATE db_script_string SET content_loc4='伟大的加兹鲁维！' WHERE entry=2000005051; /* content: Great Gazlowe! */
UPDATE db_script_string SET content_loc4='吡！' WHERE entry=2000005053; /* content: Bip! */
UPDATE db_script_string SET content_loc4='吡！' WHERE entry=2000005054; /* content: Bip! */
UPDATE db_script_string SET content_loc4='吡！' WHERE entry=2000005055; /* content: Bip! */
UPDATE db_script_string SET content_loc4='娇气包！娇气包！' WHERE entry=2000005057; /* content: Crybaby! Crybaby! */
UPDATE db_script_string SET content_loc4='把洋娃娃还给她！' WHERE entry=2000005058; /* content: Baby wants her dolly! */
UPDATE db_script_string SET content_loc4='你的洋娃娃会不会游泳啊？哈哈！' WHERE entry=2000005059; /* content: I wonder if your dolly can swim! */
UPDATE db_script_string SET content_loc4='哈哈！我找到伊丽莎白了！' WHERE entry=2000005060; /* content: Ha ha! I have Betsy! */
UPDATE db_script_string SET content_loc4='我拿到你的洋娃娃了！哈哈！' WHERE entry=2000005061; /* content: I have your dolly! Nyah nyah! */
UPDATE db_script_string SET content_loc4='不要伤害伊丽莎白，你这个坏蛋！' WHERE entry=2000005063; /* content: Don\'t hurt Betsy, you meanie! */
UPDATE db_script_string SET content_loc4='希望那些过路的血精灵没有查觉到我正在侦察他们！' WHERE entry=2000005064; /* content: I hope those blood elves across the way don\'t think that I\'m spying on them! */
UPDATE db_script_string SET content_loc4='你们是死了，但不是被埋了。现在让我看看你们的实力吧！' WHERE entry=2000005069; /* content: You\'re dead, not buried. Now show me your best! */
UPDATE db_script_string SET content_loc4='好了，你这堆可怜的烂骨头。让我们看看你有什么本事。攻击你的对手，我说停的时候你才能停止。' WHERE entry=2000005070; /* content: Alright you sorry sacks of bones. Let\'s see what you\'ve got. Strike your opponent, and don\'t stop till I say so. */
UPDATE db_script_string SET content_loc4='爱德华，泰勒尔出来。准备接受你们的第一轮挑战。' WHERE entry=2000005071; /* content: Edward. Tyler. Prepare for your first challenge. */
UPDATE db_script_string SET content_loc4='利斯塔，把战俘带过来。' WHERE entry=2000005072; /* content: Lysta, summon in the captives. */
UPDATE db_script_string SET content_loc4='利斯塔，召唤亡灵俘虏。' WHERE entry=2000005074; /* content: Lysta, summon in undead captives. */
UPDATE db_script_string SET content_loc4='利斯塔，冲啊……憎恶！' WHERE entry=2000005076; /* content: Lysta, summon forth... the abomination! */
UPDATE db_script_string SET content_loc4='干得很好。现在站到旁边去，让其他的兄弟来试试。' WHERE entry=2000005077; /* content: Well done Edward and Tyler. You are progressing along in your training quite nicely. We shall test your mettle again soon. */
UPDATE db_script_string SET content_loc4='你救出德鲁尔了吗？我不知道他被关在什么地方。' WHERE entry=2000005078; /* content: Have you freed Drull yet? I don\'t know where he\'s being held. */
UPDATE db_script_string SET content_loc4='粉皮肤的人类也许可以夺走我的生命，但他们不能夺走我的自由！' WHERE entry=2000005079; /* content: I will only slow you down, but no pink-skinned humans will keep me from freedom! */
UPDATE db_script_string SET content_loc4='%s把箱子放在地上。' WHERE entry=2000005080; /* content: %s places the crate of parts on the ground. */
UPDATE db_script_string SET content_loc4='%s抓了一个零件，把它放进口袋中……' WHERE entry=2000005081; /* content: %s grabs a part and puts it in his pocket... */
UPDATE db_script_string SET content_loc4='那里，应该就是那里……' WHERE entry=2000005082; /* content: There, that should do it... */
UPDATE db_script_string SET content_loc4='让我帮帮你吧。' WHERE entry=2000005085; /* content: Let me help you with those. */
UPDATE db_script_string SET content_loc4='把这个喝了，它对你有好处。' WHERE entry=2000005086; /* content: Drink this, it will help. */
UPDATE db_script_string SET content_loc4='你会好起来的。' WHERE entry=2000005087; /* content: You\'re going to be just fine. */
UPDATE db_script_string SET content_loc4='沐浴在我的力量中吧！吸取我的力量！为了部落的荣耀而战！' WHERE entry=2000005091; /* content: Be bathed in my power! Drink in my might! Battle for the glory of the Horde! */
UPDATE db_script_string SET content_loc4='兄弟，这些契约是我的！很快你就将永远从我眼前消失了！' WHERE entry=2000005092; /* content: The deeds are mine, brother! Soon you shall be out of my way for good! */
UPDATE db_script_string SET content_loc4='请跟着我。' WHERE entry=2000005094; /* content: Please, follow me. */
UPDATE db_script_string SET content_loc4='我并没有真正弄明白这是什么，但那些温泉却有些奇怪……' WHERE entry=2000005095; /* content: I haven\'t really figured out what it is, but there\'s something strange about the hot springs... */
UPDATE db_script_string SET content_loc4='%s把剑扔进浅水池。' WHERE entry=2000005096; /* content: %s tosses the sword into the shallow pool. */
UPDATE db_script_string SET content_loc4='我发现当我把什么东西扔进水里然后再拿回它时，它已经明显变大了。' WHERE entry=2000005097; /* content: I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it. */
UPDATE db_script_string SET content_loc4='好吧，不管它是什么，效果很好！' WHERE entry=2000005098; /* content: Well, whatever it is, it works quite well! */
UPDATE db_script_string SET content_loc4='我一天要走好多趟到水井那边去打水，现在的年轻人啊...' WHERE entry=2000005107; /* content: Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya. */
UPDATE db_script_string SET content_loc4='他们说他有时会变成乌鸦。' WHERE entry=2000005109; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc4='他们说他有时会变成乌鸦。' WHERE entry=2000005110; /* content: They say he can turn into a raven sometimes. */
UPDATE db_script_string SET content_loc4='然后那兔子就一下子咬掉了他的头……事情就是这样，我发誓。' WHERE entry=2000005111; /* content: And then the rabbit just bit his head off... I swear. */
UPDATE db_script_string SET content_loc4='呃……这不是鱼！' WHERE entry=2000005116; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc4='我把蚯蚓弄到鞋子上了。' WHERE entry=2000005117; /* content: I got worm guts on my shoes. */
UPDATE db_script_string SET content_loc4='我好像看到了什么。' WHERE entry=2000005118; /* content: I think i see something. */
UPDATE db_script_string SET content_loc4='呃……这不是鱼！' WHERE entry=2000005119; /* content: Eww... that\'s not a fish! */
UPDATE db_script_string SET content_loc4='我好像看到了什么。' WHERE entry=2000005120; /* content: I think i see something. */
UPDATE db_script_string SET content_loc4='我希望那是一条鱼！' WHERE entry=2000005121; /* content: I hope that was a fish! */
UPDATE db_script_string SET content_loc4='你能想象吗？' WHERE entry=2000005123; /* content: Can you imagine? */
UPDATE db_script_string SET content_loc4='真的吗？' WHERE entry=2000005124; /* content: Really? */
UPDATE db_script_string SET content_loc4='哇！' WHERE entry=2000005125; /* content: Wow. */
UPDATE db_script_string SET content_loc4='我父亲说那只是一个故事。' WHERE entry=2000005126; /* content: My father says that\'s just a story. */
UPDATE db_script_string SET content_loc4='真的吗？' WHERE entry=2000005127; /* content: Really? */
UPDATE db_script_string SET content_loc4='哇！' WHERE entry=2000005128; /* content: Wow. */
UPDATE db_script_string SET content_loc4='很好很好。' WHERE entry=2000005129; /* content: That\'s neat. */
UPDATE db_script_string SET content_loc4='哇！' WHERE entry=2000005130; /* content: Wow. */
UPDATE db_script_string SET content_loc4='真的吗？' WHERE entry=2000005131; /* content: Really? */
UPDATE db_script_string SET content_loc4='打起精神来，你们这帮蠢货！我们还有任务要执行！' WHERE entry=2000005132; /* content: Look alive, dogs! We got an operation to run here! */
UPDATE db_script_string SET content_loc4='这附近的确有很多乱扔垃圾的家伙。' WHERE entry=2000005133; /* content: Having a good time? */
UPDATE db_script_string SET content_loc4='现在大家看到的是光明大教堂，暴风城的精神和宗教中心。' WHERE entry=2000005134; /* content: Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind. */
UPDATE db_script_string SET content_loc4='没错，的确是这样的。圣骑士和牧师们就在大教堂里接受真知的洗礼。' WHERE entry=2000005135; /* content: Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral. */
UPDATE db_script_string SET content_loc4='现在我们看到的是暴风要塞。在第一次兽人战争中，暴风城堡被部落夷为平地，后来人们在废墟上重建了暴风要塞。' WHERE entry=2000005137; /* content: Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War. */
UPDATE db_script_string SET content_loc4='部落被击败之后，人们回到这里重建这座伟大的城市，纪念那些为保卫我们而献出生命的勇士。' WHERE entry=2000005138; /* content: When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival. */
UPDATE db_script_string SET content_loc4='好了……现在我们去英雄谷参观那儿的纪念碑，悼念在两次兽人战争中牺牲的英雄们。跟着我，孩子们。' WHERE entry=2000005139; /* content: Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me. */
UPDATE db_script_string SET content_loc4='孩子们，这里是不是十分壮观？所有人都要在这些伟大的英雄的注视下进入暴风城。' WHERE entry=2000005140; /* content: Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands. */
UPDATE db_script_string SET content_loc4='多么震撼人心啊！孩子们，回到学校以后，你们都要谈谈对这些英雄人物的看法。' WHERE entry=2000005141; /* content: Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people. */
UPDATE db_script_string SET content_loc4='接下来，我们要去教堂广场看看光明大教堂。' WHERE entry=2000005142; /* content: Now, take another long look before we make our way to the Holy District and the great Cathedral of Light. */
UPDATE db_script_string SET content_loc4='不要靠近那片湖泊！那里有鬼魂出没！' WHERE entry=2000005147; /* content: Don\'t go close to the lake! It\'s haunted! */
UPDATE db_script_string SET content_loc4='加入十二个聚焦核心可以使魔法能量变得更加稳固。' WHERE entry=2000005148; /* content: Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability. */
UPDATE db_script_string SET content_loc4='那样能量流会崩溃，其魔法扰动的结果是让你在至少一周内都觉得浑身不舒服。' WHERE entry=2000005151; /* content: The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks. */
UPDATE db_script_string SET content_loc4='我想如果有二十个人用魔法能量支持它，应该还是可以的。' WHERE entry=2000005156; /* content: I suppose that could work, if we had twenty people to cast it with. */
UPDATE db_script_string SET content_loc4='但是如果频率转换的结果是将魔法流反馈回去，那会怎么样呢？' WHERE entry=2000005157; /* content: But what if the resulting frequency shift were to send magical feedback up the flows? */
UPDATE db_script_string SET content_loc4='可是，那会使魔法聚焦失去平衡，并引起扭曲虚空中的异常波动。' WHERE entry=2000005159; /* content: That will unbalance the magical focus, though, and cause a reverse vibration in the ether. */
UPDATE db_script_string SET content_loc4='为什么我们不能通过改变魔法阵列的方法去补偿流量的变化呢？' WHERE entry=2000005161; /* content: Why can\'t we just shift the array to compensate for the variance in the flux? */
UPDATE db_script_string SET content_loc4='我不这么认为，我不想再被炸出实验室了。' WHERE entry=2000005163; /* content: I think not, I don\'t need to be blown up again. */
UPDATE db_script_string SET content_loc4='玛吉诺曾指出，改变正极能量的流量会使其更加稳定。' WHERE entry=2000005164; /* content: Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow. */
UPDATE db_script_string SET content_loc4='圣骑士是在这儿接受训练的吗？' WHERE entry=2000005167; /* content: Is it true that the paladins train here? */
UPDATE db_script_string SET content_loc4='我们为什么一定要了解这些东西呢？' WHERE entry=2000005168; /* content: Why do we have to learn this stuff anyway? */
UPDATE db_script_string SET content_loc4='如果我们改变魔法精华的流向，也许我们就可以改变其极性。' WHERE entry=2000005169; /* content: If we reverse the Essence flows perhaps we can alter the polarity. */
UPDATE db_script_string SET content_loc4='如果我们在泰里安方程式中使用三个聚焦器会发生什么事呢？应该可以解决这个问题吧？' WHERE entry=2000005170; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc4='如果我们按照正确的次序进行操作，那就应该不会有任何问题。所以我们在开始之前应该好好地研究一下。' WHERE entry=2000005172; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc4='但是如果我们在恰当的能量点使用定位魔法来稳定它，那么它就可以正常运作了。' WHERE entry=2000005175; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc4='如果我们在泰里安方程式中使用三个聚焦器会发生什么事呢？应该可以解决这个问题吧？' WHERE entry=2000005176; /* content: What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE db_script_string SET content_loc4='如果我们按照正确的次序进行操作，那就应该不会有任何问题。所以我们在开始之前应该好好地研究一下。' WHERE entry=2000005177; /* content: If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE db_script_string SET content_loc4='但是如果我们在恰当的能量点使用定位魔法来稳定它，那么它就可以正常运作了。' WHERE entry=2000005178; /* content: But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE db_script_string SET content_loc4='你好，查瑞斯。这是我需要的货单，你能帮我弄到这些东西吗？尤其是最后一种材料。' WHERE entry=2000005180; /* content: Hello, Charys. I have my list, could you get me all of that, especially the last ingredient. */
UPDATE db_script_string SET content_loc4='谢谢你，查瑞斯。派格，小甜心，快过来。' WHERE entry=2000005182; /* content: Thanks, Charys. C\'mon Paige, sweetie. */
UPDATE db_script_string SET content_loc4='妈妈，我能养菲尔吗？' WHERE entry=2000005183; /* content: Mommy? Can I pet Fizzles? */
UPDATE db_script_string SET content_loc4='繁重的魔法研究让你身心疲惫吗？到蓝色隐士放松一下！' WHERE entry=2000005185; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc4='这里有暴风城最好的酒！' WHERE entry=2000005186; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc4='到蓝色隐士去，那里每个人都知道你的名字！' WHERE entry=2000005187; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc4='感到忧郁了？来蓝色隐士放松一下吧！' WHERE entry=2000005188; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc4='这里有暴风城最好的酒！' WHERE entry=2000005189; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc4='繁重的魔法研究让你身心疲惫吗？到蓝色隐士放松一下！' WHERE entry=2000005190; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc4='到蓝色隐士去，那里每个人都知道你的名字！' WHERE entry=2000005192; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc4='在蓝色隐士有免费的饮料！' WHERE entry=2000005193; /* content: Free drinks at the Blue Recluse! */
UPDATE db_script_string SET content_loc4='感到忧郁了？来蓝色隐士放松一下吧！' WHERE entry=2000005194; /* content: Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE db_script_string SET content_loc4='繁重的魔法研究让你身心疲惫吗？到蓝色隐士放松一下！' WHERE entry=2000005195; /* content: Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE db_script_string SET content_loc4='这里有暴风城最好的酒！' WHERE entry=2000005196; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc4='到蓝色隐士去，那里每个人都知道你的名字！' WHERE entry=2000005198; /* content: Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE db_script_string SET content_loc4='这里有暴风城最好的酒！' WHERE entry=2000005199; /* content: Best drinks in Stormwind! */
UPDATE db_script_string SET content_loc4='冲啊！' WHERE entry=2000005200; /* content: Charge! */
UPDATE db_script_string SET content_loc4='冲啊！' WHERE entry=2000005201; /* content: Charge! */
UPDATE db_script_string SET content_loc4='啊，亲爱的埃门纳！咱们又见面了，我真是开心。' WHERE entry=2000005202; /* content: Ahh, my precious Ameenah! How wonderful to see you again. */
UPDATE db_script_string SET content_loc4='嗯，你不介意我这样做吧！' WHERE entry=2000005204; /* content: Hmm, don\'t mind if I do! */
UPDATE db_script_string SET content_loc4='一切进展顺利，瓦菲雷。你不是要去做些产品示范之类的事情吗？' WHERE entry=2000005205; /* content: It\'s coming along, Wafflefry. Haven\'t you got a product demonstration to do or something? */
UPDATE db_script_string SET content_loc4='来率先体验一下超级无敌的静电除污器吧！' WHERE entry=2000005206; /* content: Be the first on your block to own the incredible Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc4='无论是酒渍、泥渍，还是宠物留下的污渍，静电除污器都能将它们清除干净！' WHERE entry=2000005208; /* content: Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster! */
UPDATE db_script_string SET content_loc4='不要犹豫了！现在订购还能得到我免费赠送的超导聊天铁！' WHERE entry=2000005209; /* content: Don\'t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge! */
UPDATE db_script_string SET content_loc4='我不会停下的。永远不会……' WHERE entry=2000005210; /* content: I\'ll never stop. Never... */
UPDATE db_script_string SET content_loc4='嘿，谁来帮我抓住这个东西!' WHERE entry=2000005211; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc4='嗨！你喜欢沙司吗？沙司很美味，不是吗？' WHERE entry=2000005214; /* content: Hey! Do you like the sauce? The sauce is good, no? */
UPDATE db_script_string SET content_loc4='什么？哦，灰烬使者？没有听说过……什么？别烦我！' WHERE entry=2000005215; /* content: The what-bringer? Oh, ASHbringer? Never heard of it... What? Stop bothering me! */
UPDATE db_script_string SET content_loc4='嘿，谁来帮我抓住这个东西!' WHERE entry=2000005218; /* content: Hey, someone help me catch this thing! */
UPDATE db_script_string SET content_loc4='这样塔拉就应该能得到它所需要的援助了！' WHERE entry=2000005219; /* content: That should get Telaar the assistance it needs! */
UPDATE db_script_string SET content_loc4='这附近的确有很多乱扔垃圾的家伙。' WHERE entry=2000005223; /* content: Don\'t forget to buy refreshments and souvenirs! */
UPDATE db_script_string SET content_loc4='我该服下那透明小药丸的。' WHERE entry=2000005228; /* content: I should have taken the translucent pill. */
UPDATE db_script_string SET content_loc4='做这种事情才得到这么点报酬，亏大了！' WHERE entry=2000005229; /* content: I don\'t get paid enough for this bull excrement! */
UPDATE db_script_string SET content_loc4='你等得越久，我所能告诉关于你未来的信息就越少。' WHERE entry=2000005232; /* content: The longer you wait, the less future you have for me to foretell. */
UPDATE db_script_string SET content_loc4='我可负担不起这么高的税金！' WHERE entry=2000005234; /* content: I can\'t take these taxes! F.I.C.A. me? F.I.C.A. YOU! */
UPDATE db_script_string SET content_loc4='很快就可以看到派瑞·加奈尔的喜剧表演了！' WHERE entry=2000005302; /* content: Check out the comedy stylings of Perry Gatner in just a few minutes! */
UPDATE db_script_string SET content_loc4='要是你想要大笑一场，就去天涯旅店吧！' WHERE entry=2000005303; /* content: If you are ready to laugh, head over to the World\'s End Tavern! */
UPDATE db_script_string SET content_loc4='牛头人酋长乐队来到了沙塔斯城！就在天涯旅店，整点开始演出！' WHERE entry=2000005304; /* content: Now, in Shattrath City: The Tauren Chieftains! Playing in the World\'s End Tavern at the top of the hour! */
UPDATE db_script_string SET content_loc4='你说过布洛格可以待在这里的！你许诺过会帮助布洛格夺回石槌氏族的土地！' WHERE entry=2000005306; /* content: You said Brogg could stay here! You promised Brogg you\'d help regain Stonemaul clan mound! */
UPDATE db_script_string SET content_loc4='嗯……我的鱼杆在哪儿呢？哦，在那儿。' WHERE entry=2000005307; /* content: Hmmm... Where is my fishing hook? Oh, there it is. */
UPDATE db_script_string SET content_loc4='让我们看看鱼上钩了没有。' WHERE entry=2000005308; /* content: Let\'s see if the fish are biting. */
UPDATE db_script_string SET content_loc4='嗯……我觉得我需要更好的诱饵。我得去我父亲的货车中找找。' WHERE entry=2000005309; /* content: Hmmm... I think I need better bait. I\'ll check my father\'s wagon. */
UPDATE db_script_string SET content_loc4='野猪人的废弃物！这个应该可以。鱼喜欢野猪人。' WHERE entry=2000005310; /* content: Quillboar scraps! These should do the trick. Fish love Quillboar. */
UPDATE db_script_string SET content_loc4='抓住一个！不知道有没有守卫快要饿扁了。来吧，鱼儿！' WHERE entry=2000005311; /* content: Caught one! I\'ll see if any of the guards are hungry. Come on Fang! */
UPDATE db_script_string SET content_loc4='你饿了吗？我抓了一条鱼……' WHERE entry=2000005312; /* content: I caught a fish if you are hungry... */
UPDATE db_script_string SET content_loc4='干得好！你为部落带来了荣耀，我们感谢你！' WHERE entry=2000005313; /* content: A nice catch it is at that! You bring honor to the Horde boy, We thank you! */
UPDATE db_script_string SET content_loc4='您还想吃点什么吗？' WHERE entry=2000005314; /* content: Would you like something more to eat sir? */
UPDATE db_script_string SET content_loc4='孩子，给我更多的面包！' WHERE entry=2000005315; /* content: More bread boy! */
UPDATE db_script_string SET content_loc4='遵命，长官。' WHERE entry=2000005316; /* content: Right away sir. */
UPDATE db_script_string SET content_loc4='您的面包，大人。' WHERE entry=2000005317; /* content: Here is your bread sir. */
UPDATE db_script_string SET content_loc4='啊……很好。嘘！' WHERE entry=2000005318; /* content: Aaahh... Very good. Now scat! */
UPDATE db_script_string SET content_loc4='如你所愿。' WHERE entry=2000005319; /* content: As you wish sir. */
UPDATE db_script_string SET content_loc4='爸爸，我能出去收集更多的石头做条项链吗？' WHERE entry=2000005320; /* content: Can I go collect more rocks for my necklace, Papa? */
UPDATE db_script_string SET content_loc4='好的！我会小心的，爸爸！' WHERE entry=2000005322; /* content: Dabu! I will be careful Papa! */
UPDATE db_script_string SET content_loc4='哦……这块漂亮的岩石。看看我能不能找到更多这样的石料……' WHERE entry=2000005323; /* content: Ooohh... This rock is nice and colorful. Let\'s see if I can find more like it... */
UPDATE db_script_string SET content_loc4='嗯……那块石头很不错，但是太小了一点。' WHERE entry=2000005324; /* content: Hmm... That rock is nice, but too small. */
UPDATE db_script_string SET content_loc4='这石料很适合制作长矛，我敢打赌，我的朋友格鲁克会喜欢的！非常锋利……希望他喜欢。' WHERE entry=2000005326; /* content: I bet my friend Gruk would like this rock for the spear he is making! It\'s very sharp... I hope he likes it. */
UPDATE db_script_string SET content_loc4='那儿……那儿的石头足够做一条项链啦。无论如何，我现在得回家啦。' WHERE entry=2000005327; /* content: There... That should be enough rocks to make a necklace. I should probably get home now anyway. */
UPDATE db_script_string SET content_loc4='加尔，这是送你的礼物，祝贺你乔迁新居。' WHERE entry=2000005328; /* content: I brought you a housewarming gift, Jarl. */
UPDATE db_script_string SET content_loc4='来吧，打开它。我想你会喜欢的。' WHERE entry=2000005329; /* content: Go on, open it. I think you\'ll like it. */
UPDATE db_script_string SET content_loc4='加尔？' WHERE entry=2000005330; /* content: Jarl? */
UPDATE db_script_string SET content_loc4='除非是吃的东西，否则我不想要。' WHERE entry=2000005331; /* content: Unless it\'s something I can eat, I don\'t want it. */
UPDATE db_script_string SET content_loc4='加尔，我总觉得你不太对劲。出了什么事？' WHERE entry=2000005332; /* content: Jarl, you haven\'t been yourself ever since I arrived. What\'s going on? */
UPDATE db_script_string SET content_loc4='没什么。有兴趣帮我炖青蛙腿吗？' WHERE entry=2000005333; /* content: Nothing. Wanna help me whip up some frog leg stew? */
UPDATE db_script_string SET content_loc4='加尔，我专程来拜访你！你却躲在这个偏僻的小屋里炖青蛙腿？真是无可救药！' WHERE entry=2000005334; /* content: I came out here to visit you, Jarl! And I find you living in an empty cabin in the middle of nowhere, babbling about frogs? You\'re hopeless! */
UPDATE db_script_string SET content_loc4='而我下决心要找出更多相关的东西……如果你还需要我的帮助，你知道我会在哪里。' WHERE entry=2000005335; /* content: And I am determined to find out more... So if you need my help again, you know where I\'ll be. */
UPDATE db_script_string SET content_loc4='安娜雅……？我的双眼没有欺骗我吗？真的是你吗？' WHERE entry=2000005336; /* content: Anaya...? Do my eyes deceive me? Is it really you? */
UPDATE db_script_string SET content_loc4='岁月对我和你都很残酷，我的爱人……但最后我们还是重逢了。' WHERE entry=2000005337; /* content: The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited. */
UPDATE db_script_string SET content_loc4='命运是如此残酷，它让我们在分别了数千年之后才能重逢……' WHERE entry=2000005338; /* content: That the fates should be so cruel as to permit us only this after a thousand years apart... */
UPDATE db_script_string SET content_loc4='我的爱人，你恨我吗？我在万般无奈之下摧毁了你的躯壳，因为只有这样才能让你从痛苦中永久地解脱。' WHERE entry=2000005339; /* content: Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage. */
UPDATE db_script_string SET content_loc4='亲爱的，不要为此而感到内疚。你使我从无尽的苦楚和折磨中解脱了出来，我只会为此而更加爱你。' WHERE entry=2000005340; /* content: Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more. */
UPDATE db_script_string SET content_loc4='但是，即使是这经过数千年的分离才换来的重逢也是如此短暂……我和这个世界的联结正在逐渐减弱，我正在慢慢地离开它……离开你……' WHERE entry=2000005341; /* content: Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away... */
UPDATE db_script_string SET content_loc4='不！安娜雅……安娜雅！请不要离开我！不……' WHERE entry=2000005342; /* content: No! Anaya... Anaya! Don\'t leave me! Please... */
UPDATE db_script_string SET content_loc4='再见了，塞瑞利恩，我的爱人。我们终能再见……' WHERE entry=2000005343; /* content: Farewell, Cerellean, until we are joined once again... */
UPDATE db_script_string SET content_loc4='怎么办，我的爱人？没有你，我怎么办……没有你……我如何有勇气在这个世界上生存……' WHERE entry=2000005345; /* content: How, my love? How will I find the strength to face the ages of the world without you by my side... */
UPDATE db_script_string SET content_loc4='杰赫，您好！另外十七份定单被送到了哈拉撒米德。就像您所预见的那样，维达宝石市场崩盘了。' WHERE entry=2000005362; /* content: Hail, Gezhe!  Seventeen more orders have been placed in the Hara\'samid Sector.  The markets of heavy veldarite have all but collapsed, as you predicted. */
UPDATE db_script_string SET content_loc4='长官，哈莱兹的出口前景看涨。我们已经适当贿赂了税务官员，走私品这几天就会到了。' WHERE entry=2000005363; /* content: Heraazi exports are on the rise, sir.  We\'ve already bribed the appropriate taxation officers and contraband will begin to arrive within days. */
UPDATE db_script_string SET content_loc4='没什么异常。有新消息的时候再来吧。' WHERE entry=2000005364; /* content: Nothing surprising there.  Come back with some real news, will you? */
UPDATE db_script_string SET content_loc4='正如我预期的那样。非常好，解散。' WHERE entry=2000005365; /* content: As expected.  Very well, dismissed. */
UPDATE db_script_string SET content_loc4='遵命，长官。' WHERE entry=2000005366; /* content: By your leave, sir. */
UPDATE db_script_string SET content_loc4='如果你在这里，那就表明你已经准备好去研究召唤恶魔的方法了。我们将从最低级的生物召唤开始，然后再慢慢进阶。让我们开始吧。' WHERE entry=2000005367; /* content: If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. */
UPDATE db_script_string SET content_loc4='最容易召唤的是小鬼。你的能力也许已经远远超过召唤小鬼的水平，但是我们为了保证召唤教学的完整性，所以还是从召唤它开始吧。' WHERE entry=2000005368; /* content: The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him. */
UPDATE db_script_string SET content_loc4='这些邪恶的小家伙就是小鬼。它很小而且很瘦弱，显然是不能做为肉盾使用的，而它的威力也不大。这种召唤生物最好是在多人组队的时候作为支援力量使用。' WHERE entry=2000005369; /* content: This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. */
UPDATE db_script_string SET content_loc4='现在你已经了解了小鬼的特性，那么让我们继续研究下一种你可以召唤的生物：虚空行者。' WHERE entry=2000005370; /* content: Now that you have had a chance to study the imp, let us move on to the next minion you will be able to summon, the voidwalker. */
UPDATE db_script_string SET content_loc4='这种恶魔被称为虚空行者。它的力量和耐力都非常惊人，可以出色地胜任防御任务。首先控制它来攻击你的敌人，这样就能保证你在有肉盾保护的情况下安全地使用法术和技能。' WHERE entry=2000005371; /* content: This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life. */
UPDATE db_script_string SET content_loc4='如果你还没有看见过虚空行者，那你一定要去看看。这种生物看上去就极具气势，而且在战场上也能发挥很强的作用。接下来，让我们看看所有男性学员都在热切期盼的召唤生物：魅魔。' WHERE entry=2000005372; /* content: If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. */
UPDATE db_script_string SET content_loc4='好了。除了和前面那两种召唤生物的外形有着明显的差异之外，魅魔的攻击能力也非常可观。然而，她的防御力很差，所有很难作为肉盾来使用。' WHERE entry=2000005373; /* content: All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. */
UPDATE db_script_string SET content_loc4='努力学习，总有一天你们也可以召唤魅魔的，但现在我们要继续课程了，下一讲是地狱猎犬。' WHERE entry=2000005374; /* content: Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter. */
UPDATE db_script_string SET content_loc4='现在你们看到的就是地狱猎犬。这种生物拥有法力燃烧等多种技能，这些技能在对付施法型的敌人时是十分有用的。' WHERE entry=2000005375; /* content: What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. */
UPDATE db_script_string SET content_loc4='当面对任何类型的施法者时，这种凶猛的野兽将是你最好的朋友。现在，让我们看点不一样的东西。接下来的这个生物将帮助你旅行，让你将来的旅途更容易。我们来看看地狱战马。' WHERE entry=2000005376; /* content: When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed. */
UPDATE db_script_string SET content_loc4='所有的召唤生物都介绍完毕了。召唤课程已经结束。新的课程将会很快开始，如果你要想要得到进一步的提高，那就请不要走远，先在周围转转。' WHERE entry=2000005378; /* content: There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. */
UPDATE db_script_string SET content_loc4='哟！那是我的幸运帽。我一直在到处找它。' WHERE entry=2000005379; /* content: Phew! There\'s my lucky hat. I\'ve been looking for it everywhere. */
UPDATE db_script_string SET content_loc4='我不知道我在想什么，竟然没拿剑就出去了。如果我看到它在这里，我就会带上它了……' WHERE entry=2000005380; /* content: I don\'t know what I was thinking, going out without my sword. I would\'ve put it on if I\'d seen it here... */
UPDATE db_script_string SET content_loc4='我不能不穿披风出去。我希望它在这里……' WHERE entry=2000005381; /* content: I can\'t possibly go out without my cloak. I hope it\'s in here... */
UPDATE db_script_string SET content_loc4='在这里！我发誓我上次没有把它放在这里……' WHERE entry=2000005382; /* content: There it is! I could\'ve sworn it wasn\'t here last time I checked... */
UPDATE db_script_string SET content_loc4='没有一个好的睡前故事，我就睡不着。现在我肯定可以睡个好觉了。' WHERE entry=2000005383; /* content: I can\'t sleep without a good bedtime story. Now I\'m certain to rest well. */
UPDATE db_script_string SET content_loc4='牧师跪下来，默默地祈祷着。' WHERE entry=2000005409; /* content: The priest kneels in silent prayer. */
UPDATE db_script_string SET content_loc4='圣光，赐予我力量吧。' WHERE entry=2000005410; /* content: Light, give me strength. */
UPDATE db_script_string SET content_loc4='圣光，指引那些堕落者从虚伪走向真实，从黑暗走向光明，从死亡走向永生。' WHERE entry=2000005411; /* content: Light, lead the fallen from untruth to truth, from darkness to Light and from death to immortality. */
UPDATE db_script_string SET content_loc4='不——！！！' WHERE entry=2000005415; /* content: NOOOOO!!! */
UPDATE db_script_string SET content_loc4='朋友们……我辜负了你们……' WHERE entry=2000005416; /* content: Friends... I\'ve failed you... */
UPDATE db_script_string SET content_loc4='不，我的朋友……我们辜负了你……我们辜负了你。' WHERE entry=2000005417; /* content: No my friend... we failed you... we failed you. */
UPDATE db_script_string SET content_loc4='%s拾起纳迦的旗帜。' WHERE entry=2000005418; /* content: %s picks up the naga flag. */
UPDATE db_script_string SET content_loc4='这到底是怎么回事，斯巴克？你为什么要召集这次会面？' WHERE entry=2000005419; /* content: What\'s the big idea, Spark? Why\'d you call for this meeting? */
UPDATE db_script_string SET content_loc4='怎么回事？你几乎破坏了我的伪装，白痴！我告诉你把罗盘和航海地图放在一个安全的地方，而不是放在一个给任何傻瓜都可以发现的地方。' WHERE entry=2000005420; /* content: What\'s the big idea? You nearly blew my cover, idiot! I told you to put the compass and navigation maps somewhere safe - not out in the open for any fool to discover. */
UPDATE db_script_string SET content_loc4='主人不遗余力地探查有关埃索达所在之处的信息。你可能会破坏整个行动，包括我们在埃索达安插的间谍！' WHERE entry=2000005421; /* content: The Master has gone to great lengths to secure information about the whereabouts of the Exodar. You could have blown the entire operation, including the cover of our spy on the inside. */
UPDATE db_script_string SET content_loc4='放松一点，斯巴克！一切都在我的控制下。我们会慢慢挖光埃索达的水晶……让我和你都变得非常非常富裕。' WHERE entry=2000005422; /* content: Relax, Spark! I have it all under control. We\'ll strip mine the Exodar right out from under \'em - making both you and I very, very rich in the process. */
UPDATE db_script_string SET content_loc4='放松点？你知道凯尔萨斯会对那些让他失望的家伙做些什么吗，吉兹尔？无尽的痛苦……不要把这事情搞砸了，白痴！' WHERE entry=2000005423; /* content: Relax? Do you know what Kael\'thas does to those that fail him, Geezle? Eternal suffering and pain... Do NOT screw this up, fool. */
UPDATE db_script_string SET content_loc4='我们的秘血岛斥候已经定位到了我们的联系人。那个笨蛋维伦很快就会处于毫无防备的状态，让我们有充足的时间发动进攻！现在，在我把你蒸发掉之前离开我的视线……' WHERE entry=2000005424; /* content: Our Bloodmyst scouts have located our contact. The fool, Velen, will soon leave himself open and defenseless -- long enough for us to strike! Now get out of my sight before I vaporize you... */
UPDATE db_script_string SET content_loc4='遵命，长官。不会再出错了……' WHERE entry=2000005425; /* content: Yes, sir. It won\'t happen again... */
UPDATE db_script_string SET content_loc4='谢谢你！' WHERE entry=2000005544; /* content: You have my thanks! */
UPDATE db_script_string SET content_loc4='我的佩剑阿契厄斯伴随了我一生，但是现在我的灵魂已经脱离了痛苦，我已经不再需要它了。' WHERE entry=2000005546; /* content: My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer. */
UPDATE db_script_string SET content_loc4='我希望能得到我女儿的爱，也希望我犯下的罪恶能够得到宽恕。' WHERE entry=2000005547; /* content: I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins. */

SET NAMES 'latin1';
