-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc4='伊瑟基尔说你可能有那本书……' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc4='请转告温德索尔元帅我已准备就绪。' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc4='我准备好了，我的军队也整装待命。让我们结束这次假面舞会吧！' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc4='我需要占用一点你的时间，先生。' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc4='我准备好了，欧鲁诺克。让我们消灭森卢肯，解救这些元素吧！' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc4='转动钥匙，启动了机器。' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc4='请打开庭院的大门。' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc4='活动开始了！' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc4='我准备好了。' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc4='你自由了，杜格哈尔！快出去！' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc4='出去吧，图比亚斯，你自由了！' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc4='告诉我更多。' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc4='你还想说什么？' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc4='我从不犯错。' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc4='你已经失去理智了，奈法里奥斯。你在胡言乱语。' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc4='请继续。' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc4='我做不到，瓦拉斯塔兹！一定有什么办法可以拯救你！' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc4='瓦拉斯塔兹，不！！！' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc4='动手吧！' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc4='让我们看看你有些什么。' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc4='我不是个演员。' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc4='好吧，那么我试试看。' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc4='我从来没有如此准备充足过！' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc4='这只狼快要死了。' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc4='兽人步兵' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc4='控制兽人座狼' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc4='控制被召唤的恶魔' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc4='控制兽人术士' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc4='控制兽人通灵师' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc4='控制黑手酋长' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc4='控制人类步兵' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc4='控制人类召唤师' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc4='控制人类祭司' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc4='控制莱恩国王' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc4='请重置棋盘，我们想再玩一次。' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc4='喔，奶奶，你的耳朵怎么这么尖？' WHERE entry=-3532019; /* content: Oh, grandmother, what big ears you have. */
UPDATE gossip_texts SET content_loc4='喔，奶奶，你的眼睛怎么这么大？' WHERE entry=-3532020; /* content: Oh, grandmother, what big eyes you have. */
UPDATE gossip_texts SET content_loc4='喔，奶奶，你的衣服怎么这么紫？' WHERE entry=-3532021; /* content: Oh, grandmother, what phat lewts you have. */
UPDATE gossip_texts SET content_loc4='我和我的伙伴们将与您并肩作战，普罗德摩尔女士。' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc4='我们已经准备好对付阿克蒙德的任何爪牙了，普罗德摩尔女士。' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc4='再会，普罗德摩尔女士。' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc4='我与你并肩作战，萨尔。' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc4='我们无所畏惧。' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc4='再会，萨尔。' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc4='女祭司，无论你给予我什么样的帮助，我都会感激你的。' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc4='我们准备好带你离开这里了，萨尔。出发吧！' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc4='我需要燃烧弹包。' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc4='塔蕾莎不能见你，萨尔。' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc4='现在的处境非常复杂，萨尔。对你来说，最好在更多布莱克摩尔的人出现前离开这里。我们会保证塔蕾莎的安全。' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc4='我们准备好了，萨尔。' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc4='奇怪的术士？' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc4='塔伦米尔。' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc4='我与你同在，阿卡玛。' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc4='我准备好了，阿卡玛。' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc4='我们已经作好面对伊利丹的准备了。' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc4='感谢关心，不过我们有意要探索祖阿曼。' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */

SET NAMES 'latin1';
