-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc2='[PH] SD3 texte inconnu' WHERE entry=-3000000; /* content: [PH] SD3 unknown text */
UPDATE gossip_texts SET content_loc2='Ezekiel m\'a dit que vous pourriez être en possession d\'un certain livre…' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc2='Faites savoir au maréchal Windsor que je suis prête.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc2='Mes forces sont prêtes, tout comme moi. Mettons fin à cette plaisanterie !' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc2='Pourriez-vous me consacrer un moment, monsieur ?' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc2='Je suis prête, Oronok. Détruisons Cyrukh et libérons les éléments !' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc2='Pourquoi ... oui, bien sûr. J\'ai quelque chose à vous montrer à l\'intérieur de ce bâtiment, M. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc2='Tournez la clé afin de démarrer la machine.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc2='I am ready, Anchorite. Let us begin the exorcism.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc2='Veuillez déverrouiller la porte de la cour.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc2='Que la cérémonie commence !' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc2='Je peux commencer.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc2='Vous êtes libre, Dughal ! Sortez d\'ici !' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc2='Hors d\'ici, Tobias, vous êtes libre !' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc2='Votre servitude est finie, Doom\'rel. Je te met au défi!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc2='Dites-m\'en plus.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc2='Qu\'avez-vous d\'autre à dire ?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc2='Vous nous avez mis au défi et nous sommes venus. Où est ce maître dont tu parles?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc2='Je n\'ai commis aucune faute.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc2='Vous avez perdu la tête, Nefarius. Vous parlez en énigmes.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc2='Faites.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc2='Je ne peux pas, Vaelastrasz ! Il doit sûrement y avoir un moyen de vous guérir !' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc2='Vaelastrasz, non !!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc2='Allons voir.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc2='Voyons voir ce que vous avez là.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc2='Téléporte moi à la bibliothèque du gardien' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc2='Je ne suis pas une comédienne.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc2='D\'accord, je veux bien essayer, alors.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc2='Je n\'ai jamais été aussi prête.' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc2='Le loup descend.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc2='Contrôle de grunt orc' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc2='Contrôle de loup d\'orc' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc2='Contrôle de daemon invoqué' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc2='Contrôle de démoniste orc' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc2='Contrôle de nécrolyte orc' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc2='Contrôle du chef de guerre Main-noire' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc2='Contrôle de fantassin humain' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc2='Contrôler le chargeur humain' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc2='Contrôle élémentaire d\'eau invoqué' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc2='Contrôle d\'adjurateur humain' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc2='Contrôle de clerc humain' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc2='Contrôle du roi Llane' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc2='Réinitialisez l\'échiquier s\'il vous plaît, nous voudrions faire une autre partie.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc2='Oh, mère-grand, que vous avez de grandes oreilles.' WHERE entry=-3532019; /* content: Oh, grandmother, what big ears you have. */
UPDATE gossip_texts SET content_loc2='Oh, mère-grand, que vous avez de grands yeux.' WHERE entry=-3532020; /* content: Oh, grandmother, what big eyes you have. */
UPDATE gossip_texts SET content_loc2='Oh, mère-grand, que vous avez de gros... butins.' WHERE entry=-3532021; /* content: Oh, grandmother, what phat lewts you have. */
UPDATE gossip_texts SET content_loc2='Mes compagnons et moi sommes à vos côtés, dame Portvaillant.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc2='Nous sommes prêts à affronter tout ce qu\'Archimonde pourra mettre sur notre chemin, dame Portvaillant.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc2='À notre prochaine rencontre, dame Portvaillant.' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc2='Je suis avec vous, Thrall.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc2='Nous n\'avons rien à craindre.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc2='À notre prochaine rencontre, Thrall.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc2='Je vous serais reconnaissante de m\'apporter votre aide, prêtresse.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc2='Nous allons vous faire sortir de là, Thrall. On y va !' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc2='J\'ai besoin d\'un paquet de bombes incendiaires.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc2='Taretha ne peut pas vous voir, Thrall.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc2='La situation est assez compliquée, Thrall. Il vaudrait mieux que vous filiez vers les montagnes dès maintenant, avant que d\'autres hommes de Landenoire ne se montrent. Nous veillerons à la sécurité de Taretha.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc2='Nous sommes prêts, Thrall.' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc2='Un sorcier bizarre ?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc2='Nous allons vous sortir. Taretha. Ne t\'inquiète pas. Je doute que le sorcier se promène trop loin.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc2='Moulin-de-Tarren.' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc2='Je suis avec vous, Akama.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc2='Je suis prête, Akama.' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc2='Nous sommes prêts à affronter Illidan.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc2='C\'est gentil de vous inquiéter, mais nous avons bien l\'intention d\'explorer Zul\'Aman quand même.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */

SET NAMES 'latin1';
