-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE trans_words SET content_loc5='[PH] SD3 unknown text' WHERE word_id = 127703;
UPDATE trans_words SET content_loc5='Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward.' WHERE word_id = 127689;
UPDATE trans_words SET content_loc5='I am ready, Anchorite. Let us begin the exorcism.' WHERE word_id = 127744;
UPDATE trans_words SET content_loc5='Your bondage is at an end, Doom\'rel. I challenge you!' WHERE word_id = 127682;
UPDATE trans_words SET content_loc5='You challenged us and we have come. Where is this master you speak of?' WHERE word_id = 127680;
UPDATE trans_words SET content_loc5='Teleport me to the Guardian\'s Library' WHERE word_id = 127704;
UPDATE trans_words SET content_loc5='Control Human Charger' WHERE word_id = 127717;
UPDATE trans_words SET content_loc5='Control Conjured Water Elemental' WHERE word_id = 127718;
UPDATE trans_words SET content_loc5='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE word_id = 127736;

SET NAMES 'latin1';
